import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AIPlatformService } from '../ai-platform/ai-platform.service';
import { KnowledgePlatformService } from '../knowledge-platform/knowledge-platform.service';
import { CopilotFeedbackDto, CreateConversationDto, CreateSuggestedActionDto, SendCopilotMessageDto } from './dto';
@Injectable()
export class CopilotService {
 constructor(private readonly prisma:PrismaService,private readonly ai:AIPlatformService,private readonly knowledge:KnowledgePlatformService){}
 private db(){return this.prisma as any;}
 list(org:string,userId:string){return this.db().copilotConversation.findMany({where:{organizationId:org,userId},include:{messages:{orderBy:{createdAt:'desc'},take:1}},orderBy:{updatedAt:'desc'}})}
 create(org:string,userId:string,d:CreateConversationDto){return this.db().copilotConversation.create({data:{organizationId:org,userId,domain:d.domain,title:d.title,context:d.context??{}}})}
 async get(org:string,userId:string,id:string){const c=await this.db().copilotConversation.findFirst({where:{id,organizationId:org,userId},include:{messages:{include:{feedback:true},orderBy:{createdAt:'asc'}},actions:{orderBy:{createdAt:'desc'}}}});if(!c)throw new NotFoundException('Copilot conversation not found');return c;}
 private context(org:string,userId:string,query:string){return this.knowledge.context(org,userId,query,8);}
 async send(org:string,userId:string,id:string,d:SendCopilotMessageDto){const c=await this.get(org,userId,id);const ctx=await this.context(org,userId,d.content);await this.db().copilotMessage.create({data:{organizationId:org,conversationId:id,role:'USER',content:d.content}});const history=c.messages.slice(-10).map((m:any)=>({role:m.role.toLowerCase(),content:m.content}));const result=await this.ai.execute(org,userId,{modelId:d.modelId,module:`copilot.${c.domain}`,messages:[{role:'system',content:`You are the AchieveX enterprise copilot for ${c.domain}. Ground answers in the supplied tenant records, state uncertainty, and never claim an action was executed. Retrieved enterprise context: ${ctx.context}`},...history,{role:'user',content:d.content}],storeContent:false});const message=await this.db().copilotMessage.create({data:{organizationId:org,conversationId:id,role:'ASSISTANT',content:typeof result.response==='string'?result.response:JSON.stringify(result.response),citations:ctx.citations,correlationId:result.correlationId}});await this.db().copilotConversation.update({where:{id},data:{title:c.title??d.content.slice(0,80),updatedAt:new Date()}});return{message,citations:ctx.citations,usage:result.usage};}
 async feedback(org:string,userId:string,messageId:string,d:CopilotFeedbackDto){const m=await this.db().copilotMessage.findFirst({where:{id:messageId,organizationId:org,conversation:{userId}}});if(!m)throw new NotFoundException('Copilot message not found');return this.db().copilotFeedback.upsert({where:{messageId},create:{organizationId:org,messageId,userId,...d},update:{rating:d.rating,comment:d.comment}})}
 async suggest(org:string,userId:string,id:string,d:CreateSuggestedActionDto){await this.get(org,userId,id);return this.db().copilotSuggestedAction.create({data:{organizationId:org,conversationId:id,requestedByUserId:userId,...d,status:'SUGGESTED'}})}
 async decide(org:string,userId:string,actionId:string,decision:'APPROVED'|'REJECTED'){const action=await this.db().copilotSuggestedAction.findFirst({where:{id:actionId,organizationId:org}});if(!action)throw new NotFoundException('Suggested action not found');if(action.requestedByUserId===userId&&decision==='APPROVED')throw new ForbiddenException('A suggested action requires independent approval');return this.db().copilotSuggestedAction.update({where:{id:actionId},data:{status:decision,approvedByUserId:decision==='APPROVED'?userId:undefined,approvedAt:decision==='APPROVED'?new Date():undefined}})}
}
