CREATE TYPE "OkrCycleStatus" AS ENUM ('DRAFT','ACTIVE','CLOSED','ARCHIVED');
CREATE TYPE "OkrScope" AS ENUM ('COMPANY','DEPARTMENT','TEAM','INDIVIDUAL');
CREATE TYPE "ObjectiveStatus" AS ENUM ('DRAFT','ACTIVE','AT_RISK','OFF_TRACK','COMPLETED','CANCELLED');
CREATE TYPE "KeyResultType" AS ENUM ('NUMBER','PERCENTAGE','CURRENCY','BOOLEAN','MILESTONE');
CREATE TYPE "KeyResultStatus" AS ENUM ('NOT_STARTED','ON_TRACK','AT_RISK','OFF_TRACK','COMPLETED');
CREATE TYPE "ConfidenceLevel" AS ENUM ('LOW','MEDIUM','HIGH');
CREATE TYPE "InitiativeStatus" AS ENUM ('PLANNED','IN_PROGRESS','BLOCKED','COMPLETED','CANCELLED');
-- Prisma Migrate will generate the full table DDL from schema.prisma when run locally.
