import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { KnowledgePlatformService } from '../knowledge-platform/knowledge-platform.service';
import { CreateDocumentDto, CreateDocumentVersionDto, PublishDocumentDto, RequestReviewDto, ReviewDecisionDto, UpdateDocumentDto } from './dto';
@Injectable()
export class DocumentAuthoringService {
 constructor(private readonly prisma:PrismaService,private readonly knowledge:KnowledgePlatformService){}
 private db(){return this.prisma as any;}
 private async get(org:string,id:string){const row=await this.db().enterpriseDocument.findFirst({where:{id,organizationId:org},include:{versions:{orderBy:{version:'desc'}},reviews:{orderBy:{createdAt:'desc'}},collaborators:true}});if(!row)throw new NotFoundException('Document not found');return row;}
 private canAccess(doc:any,userId:string){return doc.visibility==='ORGANIZATION'||doc.ownerUserId===userId||doc.allowedUserIds.includes(userId)||doc.collaborators?.some((x:any)=>x.userId===userId);}
 async list(org:string,userId:string){const docs=await this.db().enterpriseDocument.findMany({where:{organizationId:org},include:{_count:{select:{versions:true,reviews:true}},collaborators:true},orderBy:{updatedAt:'desc'}});return docs.filter((d:any)=>this.canAccess(d,userId));}
 async create(org:string,userId:string,d:CreateDocumentDto){return this.db().enterpriseDocument.create({data:{organizationId:org,title:d.title,summary:d.summary,ownerUserId:userId,visibility:d.visibility??'ORGANIZATION',allowedUserIds:d.allowedUserIds??[],templateKey:d.templateKey,status:'DRAFT',collaborators:{create:{organizationId:org,userId,role:'OWNER'}}},include:{collaborators:true}});}
 async update(org:string,userId:string,id:string,d:UpdateDocumentDto){const doc=await this.get(org,id);if(doc.ownerUserId!==userId)throw new ForbiddenException('Only the document owner can change document settings');return this.db().enterpriseDocument.update({where:{id},data:d});}
 async detail(org:string,userId:string,id:string){const doc=await this.get(org,id);if(!this.canAccess(doc,userId))throw new ForbiddenException('Document access denied');return doc;}
 async createVersion(org:string,userId:string,id:string,d:CreateDocumentVersionDto){const doc=await this.get(org,id);if(!this.canAccess(doc,userId))throw new ForbiddenException('Document access denied');if(['ARCHIVED','PUBLISHED'].includes(doc.status))throw new BadRequestException('Create a new draft before editing a published or archived document');const latest=doc.versions[0]?.version??0;const version=await this.db().enterpriseDocumentVersion.create({data:{organizationId:org,documentId:id,version:latest+1,content:d.content,changeSummary:d.changeSummary,metadata:d.metadata??{},createdByUserId:userId}});await this.db().enterpriseDocument.update({where:{id},data:{currentVersionId:version.id,status:'DRAFT'}});return version;}
 async requestReview(org:string,userId:string,id:string,d:RequestReviewDto){const doc=await this.get(org,id);if(doc.ownerUserId!==userId)throw new ForbiddenException('Only the document owner can request review');if(!doc.currentVersionId)throw new BadRequestException('Create a document version before requesting review');if(!d.reviewerUserIds.length)throw new BadRequestException('At least one reviewer is required');await this.db().documentReview.createMany({data:[...new Set(d.reviewerUserIds)].map(reviewerUserId=>({organizationId:org,documentId:id,versionId:doc.currentVersionId,requestedByUserId:userId,reviewerUserId,dueAt:d.dueAt?new Date(d.dueAt):null,status:'PENDING'}))});await this.db().enterpriseDocument.update({where:{id},data:{status:'IN_REVIEW'}});return this.get(org,id);}
 async decide(org:string,userId:string,reviewId:string,d:ReviewDecisionDto){const review=await this.db().documentReview.findFirst({where:{id:reviewId,organizationId:org}});if(!review)throw new NotFoundException('Review not found');if(review.reviewerUserId!==userId)throw new ForbiddenException('Review is assigned to another user');if(review.requestedByUserId===userId)throw new ForbiddenException('Requesters cannot approve their own review');if(review.status!=='PENDING')throw new BadRequestException('Review is already decided');const updated=await this.db().documentReview.update({where:{id:reviewId},data:{status:d.decision,comments:d.comments,decidedAt:new Date()}});const remaining=await this.db().documentReview.count({where:{documentId:review.documentId,versionId:review.versionId,status:'PENDING'}});const rejected=await this.db().documentReview.count({where:{documentId:review.documentId,versionId:review.versionId,status:{in:['REJECTED','CHANGES_REQUESTED']}}});if(!remaining)await this.db().enterpriseDocument.update({where:{id:review.documentId},data:{status:rejected?'DRAFT':'APPROVED'}});return updated;}
 async publish(org:string,userId:string,id:string,d:PublishDocumentDto){const doc=await this.get(org,id);if(doc.ownerUserId!==userId)throw new ForbiddenException('Only the document owner can publish');if(doc.status!=='APPROVED')throw new BadRequestException('Only approved documents can be published');const version=doc.versions.find((v:any)=>v.id===doc.currentVersionId);if(!version)throw new BadRequestException('Current document version is missing');let sourceId=d.knowledgeSourceId; if(!sourceId){const source=await this.knowledge.createSource(org,{name:'Enterprise Documents',type:'ENTERPRISE_DOCUMENT',configuration:{managedBy:'document-authoring'}});sourceId=source.id;}
 const indexed=await this.knowledge.index(org,userId,{sourceId,externalId:doc.id,title:doc.title,content:version.content,documentType:'ENTERPRISE_DOCUMENT',visibility:doc.visibility,allowedUserIds:doc.allowedUserIds,metadata:{documentId:doc.id,version:version.version,status:'PUBLISHED'}});
 await this.db().enterpriseDocument.update({where:{id},data:{status:'PUBLISHED',publishedAt:new Date(),knowledgeDocumentId:indexed.document.id}});return{document:await this.get(org,id),knowledge:indexed};}
 async archive(org:string,userId:string,id:string){const doc=await this.get(org,id);if(doc.ownerUserId!==userId)throw new ForbiddenException('Only the document owner can archive');return this.db().enterpriseDocument.update({where:{id},data:{status:'ARCHIVED',archivedAt:new Date()}});}
}
