CREATE TYPE "PredictionModelStatus" AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');
CREATE TYPE "PredictionModelType" AS ENUM ('LINEAR_TREND','MOVING_AVERAGE','EXPONENTIAL_SMOOTHING','RISK_SCORE');
CREATE TYPE "PredictionTargetType" AS ENUM ('OKR_ACHIEVEMENT','PROJECT_COMPLETION','RESOURCE_SHORTAGE','BUDGET_OVERRUN','DELIVERY_RISK','SLA_BREACH','CAPACITY_DEMAND');
CREATE TYPE "PredictionRunStatus" AS ENUM ('PENDING','RUNNING','SUCCEEDED','FAILED','CANCELLED');
CREATE TABLE "PredictionModel" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"targetType" "PredictionTargetType" NOT NULL,"status" "PredictionModelStatus" NOT NULL DEFAULT 'DRAFT',"activeVersionId" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "PredictionModelVersion" ("id" TEXT PRIMARY KEY,"modelId" TEXT NOT NULL,"version" INTEGER NOT NULL,"modelType" "PredictionModelType" NOT NULL,"configuration" JSONB NOT NULL DEFAULT '{}',"featureKeys" TEXT[],"horizonPeriods" INTEGER NOT NULL DEFAULT 1,"minimumSamples" INTEGER NOT NULL DEFAULT 3,"publishedAt" TIMESTAMP(3),"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "PredictionRun" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"modelId" TEXT NOT NULL,"versionId" TEXT NOT NULL,"status" "PredictionRunStatus" NOT NULL DEFAULT 'PENDING',"input" JSONB NOT NULL DEFAULT '{}',"output" JSONB NOT NULL DEFAULT '{}',"error" TEXT,"dryRun" BOOLEAN NOT NULL DEFAULT false,"initiatedById" TEXT,"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3));
CREATE TABLE "PredictionResult" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"modelId" TEXT NOT NULL,"versionId" TEXT NOT NULL,"runId" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT NOT NULL,"predictedValue" DOUBLE PRECISION NOT NULL,"probability" DOUBLE PRECISION,"confidence" DOUBLE PRECISION NOT NULL,"horizonStart" TIMESTAMP(3),"horizonEnd" TIMESTAMP(3),"explanation" JSONB NOT NULL DEFAULT '{}',"features" JSONB NOT NULL DEFAULT '{}',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "PredictionModel_organizationId_key_key" ON "PredictionModel"("organizationId","key");
CREATE UNIQUE INDEX "PredictionModelVersion_modelId_version_key" ON "PredictionModelVersion"("modelId","version");
CREATE INDEX "PredictionModel_organizationId_status_targetType_idx" ON "PredictionModel"("organizationId","status","targetType");
CREATE INDEX "PredictionRun_organizationId_status_startedAt_idx" ON "PredictionRun"("organizationId","status","startedAt");
CREATE INDEX "PredictionRun_modelId_versionId_idx" ON "PredictionRun"("modelId","versionId");
CREATE INDEX "PredictionResult_organizationId_entityType_entityId_createdAt_idx" ON "PredictionResult"("organizationId","entityType","entityId","createdAt");
CREATE INDEX "PredictionResult_organizationId_modelId_createdAt_idx" ON "PredictionResult"("organizationId","modelId","createdAt");
ALTER TABLE "PredictionModel" ADD CONSTRAINT "PredictionModel_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "PredictionModelVersion" ADD CONSTRAINT "PredictionModelVersion_modelId_fkey" FOREIGN KEY ("modelId") REFERENCES "PredictionModel"("id") ON DELETE CASCADE;
ALTER TABLE "PredictionRun" ADD CONSTRAINT "PredictionRun_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "PredictionRun" ADD CONSTRAINT "PredictionRun_modelId_fkey" FOREIGN KEY ("modelId") REFERENCES "PredictionModel"("id") ON DELETE CASCADE;
ALTER TABLE "PredictionRun" ADD CONSTRAINT "PredictionRun_versionId_fkey" FOREIGN KEY ("versionId") REFERENCES "PredictionModelVersion"("id") ON DELETE RESTRICT;
ALTER TABLE "PredictionResult" ADD CONSTRAINT "PredictionResult_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "PredictionResult" ADD CONSTRAINT "PredictionResult_modelId_fkey" FOREIGN KEY ("modelId") REFERENCES "PredictionModel"("id") ON DELETE CASCADE;
ALTER TABLE "PredictionResult" ADD CONSTRAINT "PredictionResult_versionId_fkey" FOREIGN KEY ("versionId") REFERENCES "PredictionModelVersion"("id") ON DELETE RESTRICT;
ALTER TABLE "PredictionResult" ADD CONSTRAINT "PredictionResult_runId_fkey" FOREIGN KEY ("runId") REFERENCES "PredictionRun"("id") ON DELETE CASCADE;
