import { Injectable, NotFoundException } from '@nestjs/common';
import { createHash } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
import { CreateKnowledgeSourceDto, IndexKnowledgeDocumentDto, KnowledgeSearchDto } from './dto';
@Injectable()
export class KnowledgePlatformService {
 constructor(private readonly prisma:PrismaService){}
 private db(){return this.prisma as any;}
 private chunk(content:string,size=1200,overlap=180){const out:string[]=[];let start=0;while(start<content.length){const end=Math.min(content.length,start+size);out.push(content.slice(start,end).trim());if(end===content.length)break;start=Math.max(start+1,end-overlap);}return out.filter(Boolean);}
 private vector(text:string,dimensions=32){const tokens=text.toLowerCase().match(/[a-z0-9]+/g)??[];const v=Array(dimensions).fill(0);for(const token of tokens){const h=createHash('sha256').update(token).digest();v[h[0]%dimensions]+=1;}const n=Math.sqrt(v.reduce((s:number,x:number)=>s+x*x,0))||1;return v.map((x:number)=>x/n);}
 private cosine(a:number[],b:number[]){return a.reduce((s,x,i)=>s+x*(b[i]??0),0);}
 createSource(org:string,d:CreateKnowledgeSourceDto){return this.db().knowledgeSource.create({data:{organizationId:org,name:d.name,type:d.type,configuration:d.configuration??{},status:'ACTIVE'}})}
 listSources(org:string){return this.db().knowledgeSource.findMany({where:{organizationId:org},include:{_count:{select:{documents:true}}},orderBy:{updatedAt:'desc'}})}
 async index(org:string,userId:string,d:IndexKnowledgeDocumentDto){const source=await this.db().knowledgeSource.findFirst({where:{id:d.sourceId,organizationId:org}});if(!source)throw new NotFoundException('Knowledge source not found');const checksum=createHash('sha256').update(d.content).digest('hex');const job=await this.db().knowledgeIndexJob.create({data:{organizationId:org,sourceId:d.sourceId,status:'RUNNING',requestedByUserId:userId}});try{const existing=await this.db().knowledgeDocument.findFirst({where:{organizationId:org,sourceId:d.sourceId,externalId:d.externalId}});const doc=existing?await this.db().knowledgeDocument.update({where:{id:existing.id},data:{title:d.title,documentType:d.documentType??'DOCUMENT',visibility:d.visibility??'ORGANIZATION',allowedUserIds:d.allowedUserIds??[],metadata:d.metadata??{},checksum,version:{increment:1},indexedAt:new Date()}}):await this.db().knowledgeDocument.create({data:{organizationId:org,sourceId:d.sourceId,externalId:d.externalId,title:d.title,documentType:d.documentType??'DOCUMENT',visibility:d.visibility??'ORGANIZATION',allowedUserIds:d.allowedUserIds??[],metadata:d.metadata??{},checksum,indexedAt:new Date()}});await this.db().knowledgeChunk.deleteMany({where:{documentId:doc.id}});const parts=this.chunk(d.content);for(let i=0;i<parts.length;i++){const chunk=await this.db().knowledgeChunk.create({data:{organizationId:org,documentId:doc.id,position:i,content:parts[i],tokenCount:Math.ceil(parts[i].length/4),metadata:{}}});await this.db().knowledgeEmbedding.create({data:{organizationId:org,chunkId:chunk.id,provider:'ACHIEVEX_LOCAL',model:'hash-embedding-v1',dimension:32,vector:this.vector(parts[i])}});}await this.db().knowledgeIndexJob.update({where:{id:job.id},data:{status:'COMPLETED',documentCount:1,chunkCount:parts.length,completedAt:new Date()}});return{document:doc,chunks:parts.length,jobId:job.id};}catch(e){await this.db().knowledgeIndexJob.update({where:{id:job.id},data:{status:'FAILED',errorMessage:e instanceof Error?e.message:String(e),completedAt:new Date()}});throw e;}}
 listDocuments(org:string){return this.db().knowledgeDocument.findMany({where:{organizationId:org},include:{source:true,_count:{select:{chunks:true}}},orderBy:{indexedAt:'desc'}})}
 async search(org:string,userId:string,d:KnowledgeSearchDto){const qv=this.vector(d.query);const chunks=await this.db().knowledgeChunk.findMany({where:{organizationId:org,document:{source:d.sourceTypes?.length?{type:{in:d.sourceTypes}}:undefined}},include:{document:{include:{source:true}},embedding:true},take:300});const terms=new Set((d.query.toLowerCase().match(/[a-z0-9]+/g)??[]));const ranked=chunks.filter((x:any)=>x.document.visibility==='ORGANIZATION'||x.document.allowedUserIds.includes(userId)).map((x:any)=>{const semantic=x.embedding?this.cosine(qv,x.embedding.vector as number[]):0;const words=x.content.toLowerCase().match(/[a-z0-9]+/g)??[];const keyword=words.filter((w:string)=>terms.has(w)).length/Math.max(1,terms.size);const score=semantic*.7+Math.min(1,keyword)*.3;return{chunkId:x.id,documentId:x.documentId,title:x.document.title,sourceType:x.document.source.type,content:x.content,score:Number(score.toFixed(4)),citation:{sourceType:x.document.source.type,sourceId:x.document.externalId,title:x.document.title,rank:0}}}).sort((a:any,b:any)=>b.score-a.score).slice(0,d.topK??6);ranked.forEach((x:any,i:number)=>x.citation.rank=i+1);await this.db().knowledgeQueryAudit.create({data:{organizationId:org,userId,query:d.query,resultCount:ranked.length,topScore:ranked[0]?.score??0}});return ranked;}
 async context(org:string,userId:string,query:string,topK=6){const results=await this.search(org,userId,{query,topK});return{context:results.map((r:any)=>r.content).join('\n\n---\n\n'),citations:results.map((r:any)=>({...r.citation,score:r.score,documentId:r.documentId,chunkId:r.chunkId}))};}
 analytics(org:string){return Promise.all([this.db().knowledgeSource.count({where:{organizationId:org}}),this.db().knowledgeDocument.count({where:{organizationId:org}}),this.db().knowledgeChunk.count({where:{organizationId:org}}),this.db().knowledgeIndexJob.findMany({where:{organizationId:org},orderBy:{createdAt:'desc'},take:10})]).then(([sources,documents,chunks,jobs])=>({sources,documents,chunks,jobs}));}
}
