'use client';
import Link from 'next/link';
import { FormEvent, use, useEffect, useMemo, useState } from 'react';
import { AdminShell } from '../../../../../components/admin-shell';
import { api } from '../../../../../lib/api';

type CatalogObjective={id:string;title:string;progress:number;status:string;cycle:{name:string};keyResults:{id:string;title:string;progress:number;status:string}[]};
type Trace={project:{id:string;key:string;name:string;progress:number;status:string;health:string};objectiveLinks:any[];keyResultLinks:any[];rollup:{objectiveContribution:number;keyResultContribution:number;linkedObjectives:number;linkedKeyResults:number;completedTasks:number;totalTasks:number};dependencyExposure:{blockedBy:any[];downstreamProjects:any[]}};
const label=(v:string)=>v.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function TraceabilityPage({params}:{params:Promise<{id:string}>}){const {id}=use(params);const [trace,setTrace]=useState<Trace|null>(null),[catalog,setCatalog]=useState<CatalogObjective[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);const [objective,setObjective]=useState({objectiveId:'',weight:100,contributionType:'DIRECT',rationale:''}),[kr,setKr]=useState({keyResultId:'',weight:100,contributionType:'DIRECT',rationale:''});
 async function load(){try{const [t,c]=await Promise.all([api<Trace>(`/execution/projects/${id}/traceability`),api<CatalogObjective[]>('/execution/strategy/catalog')]);setTrace(t);setCatalog(c);setObjective(x=>({...x,objectiveId:x.objectiveId||c[0]?.id||''}));const firstKr=c.flatMap(x=>x.keyResults)[0];setKr(x=>({...x,keyResultId:x.keyResultId||firstKr?.id||''}))}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[id]);
 const keyResults=useMemo(()=>catalog.flatMap(o=>o.keyResults.map(k=>({...k,objectiveTitle:o.title}))),[catalog]);
 async function addObjective(e:FormEvent){e.preventDefault();setBusy(true);try{await api(`/execution/projects/${id}/objective-links`,{method:'POST',body:JSON.stringify(objective)});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function addKr(e:FormEvent){e.preventDefault();setBusy(true);try{await api(`/execution/projects/${id}/key-result-links`,{method:'POST',body:JSON.stringify(kr)});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(path:string){setBusy(true);try{await api(path,{method:'DELETE'});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!trace)return <AdminShell title="Strategy traceability" subtitle="Loading…">{error&&<p className="formError">{error}</p>}</AdminShell>;
 return <AdminShell title={`${trace.project.key} · Strategy traceability`} subtitle="Connect delivery work to measurable strategic outcomes." action={<Link className="buttonLink secondary" href={`/execution/projects/${id}`}>Back to project</Link>}>
  {error&&<p className="formError">{error}</p>}
  <section className="metrics executionMetrics"><article><p>Objective contribution</p><strong>{Math.round(trace.rollup.objectiveContribution)}%</strong><span>{trace.rollup.linkedObjectives} linked objectives</span></article><article><p>KR contribution</p><strong>{Math.round(trace.rollup.keyResultContribution)}%</strong><span>{trace.rollup.linkedKeyResults} linked key results</span></article><article><p>Delivery completion</p><strong>{trace.rollup.totalTasks?Math.round(trace.rollup.completedTasks/trace.rollup.totalTasks*100):0}%</strong><span>{trace.rollup.completedTasks} of {trace.rollup.totalTasks} tasks done</span></article><article><p>Dependency exposure</p><strong>{trace.dependencyExposure.blockedBy.length}</strong><span>{trace.dependencyExposure.downstreamProjects.length} downstream projects</span></article></section>
  <section className="two-column executionDetail"><article className="panel"><h2>Link an objective</h2><form className="projectForm compactForm" onSubmit={addObjective}><label>Objective<select value={objective.objectiveId} onChange={e=>setObjective({...objective,objectiveId:e.target.value})}>{catalog.map(o=><option value={o.id} key={o.id}>{o.cycle.name} · {o.title}</option>)}</select></label><div className="formGrid"><label>Relationship<select value={objective.contributionType} onChange={e=>setObjective({...objective,contributionType:e.target.value})}><option>DIRECT</option><option>ENABLING</option><option>SUPPORTING</option></select></label><label>Weight %<input type="number" min="0" max="100" value={objective.weight} onChange={e=>setObjective({...objective,weight:Number(e.target.value)})}/></label></div><label>Rationale<textarea value={objective.rationale} onChange={e=>setObjective({...objective,rationale:e.target.value})} placeholder="Explain how this project advances the objective."/></label><button disabled={busy||!objective.objectiveId}>Save objective link</button></form></article><article className="panel"><h2>Link a key result</h2><form className="projectForm compactForm" onSubmit={addKr}><label>Key result<select value={kr.keyResultId} onChange={e=>setKr({...kr,keyResultId:e.target.value})}>{keyResults.map(k=><option value={k.id} key={k.id}>{k.objectiveTitle} · {k.title}</option>)}</select></label><div className="formGrid"><label>Relationship<select value={kr.contributionType} onChange={e=>setKr({...kr,contributionType:e.target.value})}><option>DIRECT</option><option>ENABLING</option><option>SUPPORTING</option></select></label><label>Weight %<input type="number" min="0" max="100" value={kr.weight} onChange={e=>setKr({...kr,weight:Number(e.target.value)})}/></label></div><label>Rationale<textarea value={kr.rationale} onChange={e=>setKr({...kr,rationale:e.target.value})} placeholder="Describe the measurable delivery contribution."/></label><button disabled={busy||!kr.keyResultId}>Save key-result link</button></form></article></section>
  <section className="two-column executionDetail"><article className="panel"><h2>Objectives supported</h2>{trace.objectiveLinks.map(x=><div className="workItem" key={x.id}><span><Link href={`/execution/objectives/${x.objective.id}`}><strong>{x.objective.title}</strong></Link><small>{x.objective.cycle.name} · {label(x.contributionType)} · {Number(x.weight)}% weight · {Math.round(x.effectiveContribution)}% effective</small></span><button className="secondary" disabled={busy} onClick={()=>remove(`/execution/projects/${id}/objective-links/${x.objective.id}`)}>Remove</button></div>)}{!trace.objectiveLinks.length&&<p className="muted">No objective links yet.</p>}</article><article className="panel"><h2>Key results supported</h2>{trace.keyResultLinks.map(x=><div className="workItem" key={x.id}><span><strong>{x.keyResult.title}</strong><small>{x.keyResult.objective.title} · {label(x.contributionType)} · {Number(x.weight)}% weight · {Math.round(x.effectiveContribution)}% effective</small></span><button className="secondary" disabled={busy} onClick={()=>remove(`/execution/projects/${id}/key-result-links/${x.keyResult.id}`)}>Remove</button></div>)}{!trace.keyResultLinks.length&&<p className="muted">No key-result links yet.</p>}</article></section>
  <section className="panel"><h2>Dependency exposure</h2>{trace.dependencyExposure.blockedBy.map(x=><div className="workItem" key={x.id}><span><Link href={`/execution/projects/${x.id}`}><strong>{x.key} · {x.name}</strong></Link><small>Upstream dependency · {label(x.status)} · {label(x.health)}</small></span><i className="status">{Math.round(Number(x.progress))}%</i></div>)}{!trace.dependencyExposure.blockedBy.length&&<p className="muted">No active upstream dependency exposure.</p>}</section>
 </AdminShell>}
