import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateAutomationDto, CreateAutomationVersionDto, ExecuteAutomationDto } from './dto/automation.dto';
import { planActions, shouldExecute, validateAutomation } from './engine/automation-engine';
@Injectable() export class AutomationService { constructor(private readonly prisma:PrismaService){}
 list(org:string){return this.prisma.automationDefinition.findMany({where:{organizationId:org},include:{versions:{orderBy:{version:'desc'},take:1}},orderBy:{updatedAt:'desc'}})}
 create(org:string,user:string,d:CreateAutomationDto){return this.prisma.automationDefinition.create({data:{organizationId:org,key:d.key,name:d.name,description:d.description,createdById:user}})}
 async addVersion(org:string,user:string,id:string,d:CreateAutomationVersionDto){try{validateAutomation(d.conditions,d.actions)}catch(e:any){throw new BadRequestException(e.message)}const def=await this.prisma.automationDefinition.findFirst({where:{id,organizationId:org}});if(!def)throw new NotFoundException('Automation not found');const latest=await this.prisma.automationVersion.aggregate({where:{definitionId:id},_max:{version:true}});return this.prisma.automationVersion.create({data:{definitionId:id,version:(latest._max.version??0)+1,triggerType:d.triggerType,triggerConfig:(d.triggerConfig??{}) as any,conditions:d.conditions as any,actions:d.actions as any,createdById:user}})}
 async publish(org:string,id:string,versionId:string){const v=await this.prisma.automationVersion.findFirst({where:{id:versionId,definitionId:id,definition:{organizationId:org}}});if(!v)throw new NotFoundException('Automation version not found');return this.prisma.$transaction(async tx=>{await tx.automationVersion.update({where:{id:v.id},data:{publishedAt:new Date()}});return tx.automationDefinition.update({where:{id},data:{status:'PUBLISHED',activeVersionId:v.id}})})}
 async execute(org:string,user:string,id:string,d:ExecuteAutomationDto){const def=await this.prisma.automationDefinition.findFirst({where:{id,organizationId:org,status:'PUBLISHED'}});if(!def?.activeVersionId)throw new NotFoundException('Published automation not found');const v=await this.prisma.automationVersion.findUnique({where:{id:def.activeVersionId}});if(!v)throw new NotFoundException('Active version not found');const context={...(d.context??{}),trigger:d.triggerPayload??{}};let matched=false,error:string|undefined;try{matched=shouldExecute(v.conditions,context)}catch(e:any){error=e.message}const results=matched?planActions(v.actions as any[],!!d.dryRun):[];return this.prisma.automationExecution.create({data:{organizationId:org,definitionId:def.id,versionId:v.id,status:error?'FAILED':!matched?'SKIPPED':d.dryRun?'DRY_RUN':'SUCCEEDED',triggerType:v.triggerType,triggerPayload:(d.triggerPayload??{}) as any,context:context as any,actionResults:results as any,error,dryRun:!!d.dryRun,completedAt:new Date(),initiatedById:user}})}
 history(org:string,id?:string){return this.prisma.automationExecution.findMany({where:{organizationId:org,...(id?{definitionId:id}:{})},include:{definition:{select:{key:true,name:true}},version:{select:{version:true}}},orderBy:{startedAt:'desc'},take:200})}
 async pause(org:string,id:string){const x=await this.prisma.automationDefinition.findFirst({where:{id,organizationId:org}});if(!x)throw new NotFoundException('Automation not found');return this.prisma.automationDefinition.update({where:{id},data:{status:'PAUSED'}})}
}
