import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateRuleDefinitionDto, CreateRuleVersionDto, EvaluateRuleDto } from './dto/rule.dto';
import { evaluateGroup, validateRuleGroup } from './engine/rule-engine';
const TYPES=new Set(['CREATE_TASK','SEND_NOTIFICATION','START_WORKFLOW','ASSIGN_USER','UPDATE_FIELD','INVOKE_AI','CALL_WEBHOOK','EMIT_EVENT']);
@Injectable() export class RuleService { constructor(private readonly prisma:PrismaService){}
 list(org:string){return this.prisma.businessRuleDefinition.findMany({where:{organizationId:org},include:{versions:{orderBy:{version:'desc'},take:1}},orderBy:{updatedAt:'desc'}})}
 create(org:string,user:string,d:CreateRuleDefinitionDto){return this.prisma.businessRuleDefinition.create({data:{organizationId:org,key:d.key,name:d.name,description:d.description,createdById:user}})}
 async addVersion(org:string,user:string,id:string,d:CreateRuleVersionDto){validateRuleGroup(d.conditions);if(!d.actions.length)throw new BadRequestException('At least one action is required');for(const a of d.actions)if(!TYPES.has(a.type))throw new BadRequestException(`Unsupported action type: ${a.type}`);const def=await this.prisma.businessRuleDefinition.findFirst({where:{id,organizationId:org}});if(!def)throw new NotFoundException('Rule definition not found');const latest=await this.prisma.businessRuleVersion.aggregate({where:{definitionId:id},_max:{version:true}});return this.prisma.businessRuleVersion.create({data:{definitionId:id,version:(latest._max.version??0)+1,conditions:d.conditions as any,actions:d.actions as any,priority:d.priority??100,stopOnMatch:d.stopOnMatch??false,createdById:user}})}
 async publish(org:string,id:string,versionId:string){const v=await this.prisma.businessRuleVersion.findFirst({where:{id:versionId,definitionId:id,definition:{organizationId:org}}});if(!v)throw new NotFoundException('Rule version not found');return this.prisma.$transaction(async tx=>{await tx.businessRuleVersion.update({where:{id:v.id},data:{publishedAt:new Date()}});return tx.businessRuleDefinition.update({where:{id},data:{status:'PUBLISHED',activeVersionId:v.id}})})}
 async evaluate(org:string,user:string,id:string,d:EvaluateRuleDto){const def=await this.prisma.businessRuleDefinition.findFirst({where:{id,organizationId:org,status:'PUBLISHED'}});if(!def?.activeVersionId)throw new NotFoundException('Published rule not found');const v=await this.prisma.businessRuleVersion.findUnique({where:{id:def.activeVersionId}});if(!v)throw new NotFoundException('Active rule version not found');let matched=false,error:string|undefined;try{matched=evaluateGroup(v.conditions as any,d.context)}catch(e:any){error=e.message}const results=matched?v.actions as any[]:[];return this.prisma.businessRuleExecution.create({data:{organizationId:org,definitionId:def.id,versionId:v.id,status:error?'FAILED':d.dryRun?'DRY_RUN':matched?'MATCHED':'NOT_MATCHED',entityType:d.entityType,entityId:d.entityId,triggerType:d.triggerType,context:d.context as any,matched,actionResults:(d.dryRun?results.map(a=>({action:a,status:'WOULD_EXECUTE'})):results.map(a=>({action:a,status:'QUEUED'}))) as any,error,executedById:user}})}
 history(org:string,id?:string){return this.prisma.businessRuleExecution.findMany({where:{organizationId:org,...(id?{definitionId:id}:{})},include:{definition:{select:{key:true,name:true}},version:{select:{version:true}}},orderBy:{executedAt:'desc'},take:200})}
}
