'use client';
import { FormEvent, useEffect, useState } from 'react';
import { AdminShell } from '../../../components/admin-shell';
import { api } from '../../../lib/api';

type Branding={productName:string;primaryColor:string;secondaryColor:string;supportEmail?:string;logoUrl?:string};
type Policy={ssoRequired:boolean;mfaRequired:boolean;passwordMinLength:number;sessionIdleMinutes:number;maxFailedAttempts:number;allowedCountries:string[]};
type Flag={key:string;name:string;enabled:boolean;rolloutPercentage:number};
type Domain={id:string;domain:string;status:string;verificationToken:string;autoJoinEnabled:boolean};
type Provider={id:string;name:string;type:string;status:string;issuerUrl?:string;metadataUrl?:string};
type Session={id:string;status:string;ipAddress?:string;userAgent?:string;lastActivityAt:string;user:{email:string;firstName:string;lastName:string}};

export default function EnterpriseSettingsPage(){
 const [tab,setTab]=useState('overview'); const [branding,setBranding]=useState<Branding|null>(null); const [policy,setPolicy]=useState<Policy|null>(null); const [flags,setFlags]=useState<Flag[]>([]); const [domains,setDomains]=useState<Domain[]>([]); const [providers,setProviders]=useState<Provider[]>([]); const [sessions,setSessions]=useState<Session[]>([]); const [notice,setNotice]=useState(''); const [secret,setSecret]=useState('');
 const load=async()=>{const [b,p,f,d,i,s]=await Promise.all([api<Branding>('/enterprise/branding'),api<Policy>('/enterprise/security-policy'),api<Flag[]>('/enterprise/feature-flags'),api<Domain[]>('/enterprise/domains'),api<Provider[]>('/enterprise/identity-providers'),api<Session[]>('/enterprise/sessions')]);setBranding(b);setPolicy(p);setFlags(f);setDomains(d);setProviders(i);setSessions(s)};
 useEffect(()=>{load().catch(e=>setNotice(e.message))},[]);
 const saveBranding=async(e:FormEvent)=>{e.preventDefault();if(!branding)return;setBranding(await api<Branding>('/enterprise/branding',{method:'PATCH',body:JSON.stringify(branding)}));setNotice('Branding saved')};
 const savePolicy=async(e:FormEvent)=>{e.preventDefault();if(!policy)return;setPolicy(await api<Policy>('/enterprise/security-policy',{method:'PATCH',body:JSON.stringify(policy)}));setNotice('Security policy saved')};
 const addDomain=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);await api('/enterprise/domains',{method:'POST',body:JSON.stringify({domain:fd.get('domain')})});e.currentTarget.reset();await load()};
 const addProvider=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);await api('/enterprise/identity-providers',{method:'POST',body:JSON.stringify({name:fd.get('name'),type:fd.get('type'),issuerUrl:fd.get('issuerUrl')||undefined,metadataUrl:fd.get('metadataUrl')||undefined,clientId:fd.get('clientId')||undefined,clientSecret:fd.get('clientSecret')||undefined})});e.currentTarget.reset();await load()};
 const createScim=async()=>{const result=await api<any>('/enterprise/scim-tokens',{method:'POST',body:JSON.stringify({name:'Primary directory sync'})});setSecret(result.token)};
 return <AdminShell title="Enterprise administration" subtitle="Identity, security, branding, sessions, domains, feature delivery, and compliance controls.">
  <div className="enterpriseTabs">{['overview','branding','security','identity','features','sessions'].map(x=><button className={tab===x?'active secondary':'secondary'} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
  {notice&&<p className="formNotice">{notice}</p>}{secret&&<div className="secretBox"><strong>Copy this SCIM token now</strong><code>{secret}</code></div>}
  {tab==='overview'&&<div className="metrics"><article><p>Identity providers</p><strong>{providers.length}</strong><span>OIDC and SAML</span></article><article><p>Verified domains</p><strong>{domains.filter(d=>d.status==='VERIFIED').length}</strong><span>{domains.length} configured</span></article><article><p>Active sessions</p><strong>{sessions.filter(s=>s.status==='ACTIVE').length}</strong><span>Tenant-wide visibility</span></article><article><p>Enabled features</p><strong>{flags.filter(f=>f.enabled).length}</strong><span>Controlled rollout</span></article></div>}
  {tab==='branding'&&branding&&<form className="panel enterpriseForm" onSubmit={saveBranding}><div className="panelHead"><div><h2>Tenant branding</h2><p>Customize the customer-facing AchieveX experience.</p></div></div><label>Product name<input value={branding.productName} onChange={e=>setBranding({...branding,productName:e.target.value})}/></label><label>Logo URL<input value={branding.logoUrl??''} onChange={e=>setBranding({...branding,logoUrl:e.target.value})}/></label><div className="formGrid"><label>Primary color<input type="color" value={branding.primaryColor} onChange={e=>setBranding({...branding,primaryColor:e.target.value})}/></label><label>Secondary color<input type="color" value={branding.secondaryColor} onChange={e=>setBranding({...branding,secondaryColor:e.target.value})}/></label></div><label>Support email<input value={branding.supportEmail??''} onChange={e=>setBranding({...branding,supportEmail:e.target.value})}/></label><button>Save branding</button></form>}
  {tab==='security'&&policy&&<form className="panel enterpriseForm" onSubmit={savePolicy}><div className="panelHead"><div><h2>Login and session policy</h2><p>Secure-by-default controls for every user in the tenant.</p></div></div><div className="preferenceRow"><div><strong>Require enterprise SSO</strong><p>Disable password login after providers are activated.</p></div><input type="checkbox" checked={policy.ssoRequired} onChange={e=>setPolicy({...policy,ssoRequired:e.target.checked})}/></div><div className="preferenceRow"><div><strong>Require MFA</strong><p>Foundation flag for identity-provider or native MFA enforcement.</p></div><input type="checkbox" checked={policy.mfaRequired} onChange={e=>setPolicy({...policy,mfaRequired:e.target.checked})}/></div><div className="formGrid"><label>Minimum password length<input type="number" value={policy.passwordMinLength} onChange={e=>setPolicy({...policy,passwordMinLength:Number(e.target.value)})}/></label><label>Idle timeout (minutes)<input type="number" value={policy.sessionIdleMinutes} onChange={e=>setPolicy({...policy,sessionIdleMinutes:Number(e.target.value)})}/></label></div><button>Save security policy</button></form>}
  {tab==='features'&&<section className="panel"><div className="panelHead"><div><h2>Feature flags</h2><p>Release capabilities gradually without redeploying the application.</p></div></div>{flags.map(flag=><div className="preferenceRow" key={flag.key}><div><strong>{flag.name}</strong><p>{flag.key} · {flag.rolloutPercentage}% rollout</p></div><input type="checkbox" checked={flag.enabled} onChange={async e=>{await api(`/enterprise/feature-flags/${flag.key}`,{method:'PATCH',body:JSON.stringify({enabled:e.target.checked,rolloutPercentage:flag.rolloutPercentage})});setFlags(flags.map(f=>f.key===flag.key?{...f,enabled:e.target.checked}:f))}}/></div>)}</section>}
  {tab==='identity'&&<div className="integrationGrid"><section className="panel"><div className="panelHead"><div><h2>Verified domains</h2><p>Domain discovery, auto-join, and invite restrictions.</p></div></div><form className="inlineForm" onSubmit={addDomain}><input name="domain" placeholder="company.com" required/><button>Add</button></form>{domains.map(d=><div className="integrationRow" key={d.id}><span><strong>{d.domain}</strong><small>{d.status}<br/>{d.verificationToken}</small></span>{d.status!=='VERIFIED'&&<button onClick={async()=>{await api(`/enterprise/domains/${d.id}/verify`,{method:'POST'});await load()}}>Verify</button>}</div>)}</section><section className="panel"><div className="panelHead"><div><h2>Identity providers</h2><p>Configure generic OIDC or SAML federation.</p></div></div><form className="okrForm" onSubmit={addProvider}><input name="name" placeholder="Microsoft Entra ID" required/><select name="type"><option>OIDC</option><option>SAML</option></select><input name="issuerUrl" placeholder="OIDC issuer URL"/><input name="metadataUrl" placeholder="SAML metadata URL"/><input name="clientId" placeholder="Client ID"/><input name="clientSecret" type="password" placeholder="Client secret"/><button>Create provider</button></form>{providers.map(p=><div className="integrationRow" key={p.id}><span><strong>{p.name}</strong><small>{p.type} · {p.status}</small></span></div>)}<button className="secondary" onClick={createScim}>Generate SCIM token</button></section></div>}
  {tab==='sessions'&&<section className="panel tablePanel"><div className="panelHead"><div><h2>Organization sessions</h2><p>Review and terminate active access across the tenant.</p></div><button onClick={async()=>{await api('/enterprise/sessions/revoke-all',{method:'POST'});await load()}}>Revoke all</button></div><div className="dataTable"><div className="tableRow tableHead"><span>User</span><span>Device</span><span>Last activity</span><span>Status</span></div>{sessions.map(s=><div className="tableRow" key={s.id}><span><strong>{s.user.firstName} {s.user.lastName}</strong><small>{s.user.email}</small></span><span>{s.userAgent?.slice(0,35)||'Unknown'}</span><span>{new Date(s.lastActivityAt).toLocaleString()}</span><span><em className={`status ${s.status.toLowerCase()}`}>{s.status}</em>{s.status==='ACTIVE'&&<button className="secondary" onClick={async()=>{await api(`/enterprise/sessions/${s.id}`,{method:'DELETE'});await load()}}>Revoke</button>}</span></div>)}</div></section>}
 </AdminShell>
}
