-- Milestone 8 enterprise identity and tenant administration.
CREATE TYPE "IdentityProviderType" AS ENUM ('OIDC','SAML');
CREATE TYPE "IdentityProviderStatus" AS ENUM ('DRAFT','ACTIVE','DISABLED');
CREATE TYPE "DomainVerificationStatus" AS ENUM ('PENDING','VERIFIED','FAILED');
CREATE TYPE "SessionStatus" AS ENUM ('ACTIVE','REVOKED','EXPIRED');
CREATE TYPE "SecretStatus" AS ENUM ('ACTIVE','ROTATED','REVOKED');

CREATE TABLE "OrganizationSetting" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE, "namespace" TEXT NOT NULL, "key" TEXT NOT NULL, "value" JSONB NOT NULL, "isSecret" BOOLEAN NOT NULL DEFAULT false, "updatedById" TEXT, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "OrganizationSetting_org_namespace_key" ON "OrganizationSetting"("organizationId","namespace","key");
CREATE TABLE "TenantSecret" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE, "name" TEXT NOT NULL, "encryptedValue" TEXT NOT NULL, "fingerprint" TEXT NOT NULL, "status" "SecretStatus" NOT NULL DEFAULT 'ACTIVE', "rotatedFromId" TEXT, "expiresAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "TenantSecret_org_name_status" ON "TenantSecret"("organizationId","name","status");
CREATE TABLE "FeatureFlagOverride" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE, "key" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT false, "value" JSONB, "rolloutPercentage" INTEGER NOT NULL DEFAULT 100, "updatedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "FeatureFlagOverride_org_key" ON "FeatureFlagOverride"("organizationId","key");
CREATE TABLE "TenantBranding" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL UNIQUE REFERENCES "Organization"("id") ON DELETE CASCADE, "productName" TEXT NOT NULL DEFAULT 'AchieveX', "logoUrl" TEXT, "darkLogoUrl" TEXT, "faviconUrl" TEXT, "primaryColor" TEXT NOT NULL DEFAULT '#3157D5', "secondaryColor" TEXT NOT NULL DEFAULT '#101828', "loginBackgroundUrl" TEXT, "supportEmail" TEXT, "supportUrl" TEXT, "customCss" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "SecurityPolicy" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL UNIQUE REFERENCES "Organization"("id") ON DELETE CASCADE, "ssoRequired" BOOLEAN NOT NULL DEFAULT false, "passwordMinLength" INTEGER NOT NULL DEFAULT 10, "passwordRequireUppercase" BOOLEAN NOT NULL DEFAULT true, "passwordRequireLowercase" BOOLEAN NOT NULL DEFAULT true, "passwordRequireNumber" BOOLEAN NOT NULL DEFAULT true, "passwordRequireSymbol" BOOLEAN NOT NULL DEFAULT false, "passwordExpiryDays" INTEGER, "maxFailedAttempts" INTEGER NOT NULL DEFAULT 5, "lockoutMinutes" INTEGER NOT NULL DEFAULT 15, "sessionIdleMinutes" INTEGER NOT NULL DEFAULT 60, "sessionAbsoluteHours" INTEGER NOT NULL DEFAULT 168, "mfaRequired" BOOLEAN NOT NULL DEFAULT false, "allowedIpCidrs" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "allowedCountries" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CompliancePolicy" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL UNIQUE REFERENCES "Organization"("id") ON DELETE CASCADE, "auditRetentionDays" INTEGER NOT NULL DEFAULT 2555, "activityRetentionDays" INTEGER NOT NULL DEFAULT 1095, "softDeleteRetentionDays" INTEGER NOT NULL DEFAULT 30, "notificationRetentionDays" INTEGER NOT NULL DEFAULT 365, "legalHoldEnabled" BOOLEAN NOT NULL DEFAULT false, "dataResidencyRegion" TEXT NOT NULL DEFAULT 'default', "privacyContactEmail" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "IdentityProvider" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE, "createdById" TEXT NOT NULL REFERENCES "User"("id"), "name" TEXT NOT NULL, "type" "IdentityProviderType" NOT NULL, "status" "IdentityProviderStatus" NOT NULL DEFAULT 'DRAFT', "issuerUrl" TEXT, "authorizationUrl" TEXT, "tokenUrl" TEXT, "userInfoUrl" TEXT, "clientId" TEXT, "clientSecretId" TEXT, "metadataUrl" TEXT, "entityId" TEXT, "certificateSecretId" TEXT, "emailDomains" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "jitProvisioning" BOOLEAN NOT NULL DEFAULT true, "defaultRoleName" TEXT NOT NULL DEFAULT 'Employee', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "IdentityProvider_org_name" ON "IdentityProvider"("organizationId","name");
CREATE TABLE "VerifiedDomain" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE, "domain" TEXT NOT NULL UNIQUE, "verificationToken" TEXT NOT NULL, "status" "DomainVerificationStatus" NOT NULL DEFAULT 'PENDING', "verifiedAt" TIMESTAMP(3), "autoJoinEnabled" BOOLEAN NOT NULL DEFAULT false, "restrictInvites" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ScimToken" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE, "createdById" TEXT NOT NULL REFERENCES "User"("id"), "name" TEXT NOT NULL, "prefix" TEXT NOT NULL, "tokenHash" TEXT NOT NULL UNIQUE, "lastUsedAt" TIMESTAMP(3), "expiresAt" TIMESTAMP(3), "revokedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "UserSession" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE, "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "status" "SessionStatus" NOT NULL DEFAULT 'ACTIVE', "ipAddress" TEXT, "userAgent" TEXT, "deviceName" TEXT, "browser" TEXT, "operatingSystem" TEXT, "countryCode" TEXT, "lastActivityAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), "revokedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "UserSession_org_status" ON "UserSession"("organizationId","status");
CREATE INDEX "UserSession_user_status" ON "UserSession"("userId","status");
