import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { createHash } from 'crypto';
import { AuditService } from '../audit/audit.service';
import { PrismaService } from '../prisma/prisma.service';
import { CreateDirectoryConnectionDto, PreviewDirectorySyncDto, UpdateDirectoryConnectionDto, UpsertAttributeMappingsDto } from './dto/identity-provisioning.dto';
@Injectable()
export class IdentityProvisioningService {
 constructor(private readonly prisma:PrismaService, private readonly audit:AuditService){}
 private async connection(org:string,id:string){const value=await this.prisma.directoryConnection.findFirst({where:{id,organizationId:org},include:{mappings:true,identityProvider:{select:{id:true,name:true,type:true,status:true}},_count:{select:{syncRuns:true,provisioningEvents:true}}}});if(!value)throw new NotFoundException('Directory connection not found');return value;}
 list(org:string){return this.prisma.directoryConnection.findMany({where:{organizationId:org},include:{mappings:true,identityProvider:{select:{id:true,name:true,type:true,status:true}}},orderBy:{createdAt:'desc'}})}
 detail(org:string,id:string){return this.connection(org,id)}
 async create(org:string,actor:string,dto:CreateDirectoryConnectionDto){if(dto.identityProviderId){const idp=await this.prisma.identityProvider.findFirst({where:{id:dto.identityProviderId,organizationId:org}});if(!idp)throw new BadRequestException('Identity provider does not belong to organization')}const {credential,...data}=dto;const value=await this.prisma.directoryConnection.create({data:{organizationId:org,...data as any,credentialSecretId:credential?createHash('sha256').update(credential).digest('hex'):undefined}});await this.audit.record({organizationId:org,actorUserId:actor,action:'directory.connection_created',entityType:'DirectoryConnection',entityId:value.id,metadata:{provider:value.provider}});return this.connection(org,value.id)}
 async update(org:string,actor:string,id:string,dto:UpdateDirectoryConnectionDto){await this.connection(org,id);const {credential,...data}=dto;const value=await this.prisma.directoryConnection.update({where:{id},data:{...data as any,...(credential?{credentialSecretId:createHash('sha256').update(credential).digest('hex')}:{})}});await this.audit.record({organizationId:org,actorUserId:actor,action:'directory.connection_updated',entityType:'DirectoryConnection',entityId:id,metadata:{status:value.status}});return this.connection(org,id)}
 async mappings(org:string,actor:string,id:string,dto:UpsertAttributeMappingsDto){await this.connection(org,id);for(const mapping of dto.mappings){if(!mapping.sourceAttribute||!mapping.targetAttribute)throw new BadRequestException('Mapping attributes are required')}await this.prisma.$transaction([this.prisma.directoryAttributeMapping.deleteMany({where:{directoryConnectionId:id}}),...dto.mappings.map(m=>this.prisma.directoryAttributeMapping.create({data:{directoryConnectionId:id,sourceAttribute:m.sourceAttribute,targetAttribute:m.targetAttribute,required:m.required??false,transformation:m.transformation as any}}))]);await this.audit.record({organizationId:org,actorUserId:actor,action:'directory.mappings_updated',entityType:'DirectoryConnection',entityId:id,metadata:{count:dto.mappings.length}});return this.connection(org,id)}
 async preview(org:string,id:string,dto:PreviewDirectorySyncDto){const c=await this.connection(org,id);const users=dto.users??[];return {connectionId:id,provider:c.provider,dryRun:true,received:users.length,planned:users.map((u:any)=>({externalId:u.id??u.externalId??null,email:u.userName??u.email??null,action:'UPSERT',mapped:c.mappings.reduce((o:any,m:any)=>{o[m.targetAttribute]=u[m.sourceAttribute];return o},{} as any)})),warnings:users.filter((u:any)=>!(u.userName??u.email)).map((_,i)=>`Row ${i+1} has no email`)}}
 async run(org:string,actor:string,id:string,dto:PreviewDirectorySyncDto){const c=await this.connection(org,id);if(c.status!=='ACTIVE')throw new BadRequestException('Directory connection must be ACTIVE');const preview=await this.preview(org,id,dto);const run=await this.prisma.directorySyncRun.create({data:{organizationId:org,directoryConnectionId:id,status:'SUCCEEDED',triggeredById:actor,startedAt:new Date(),completedAt:new Date(),usersRead:preview.received,summary:{dryRunFramework:true,warnings:preview.warnings}}});await this.prisma.directoryConnection.update({where:{id},data:{lastSyncAt:new Date(),lastSuccessfulSyncAt:new Date()}});await this.audit.record({organizationId:org,actorUserId:actor,action:'directory.sync_executed',entityType:'DirectorySyncRun',entityId:run.id,metadata:{usersRead:run.usersRead}});return run}
 runs(org:string,id?:string){return this.prisma.directorySyncRun.findMany({where:{organizationId:org,...(id?{directoryConnectionId:id}:{})},orderBy:{createdAt:'desc'},take:100})}
 events(org:string,id?:string){return this.prisma.provisioningEvent.findMany({where:{organizationId:org,...(id?{directoryConnectionId:id}:{})},orderBy:{occurredAt:'desc'},take:200})}
}
