import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { createHash, randomBytes } from 'crypto'; import { PrismaService } from '../prisma/prisma.service'; import { CreateApiKeyDto, CreateWebhookDto, UpdateWebhookDto } from './dto/integrations.dto';
@Injectable() export class IntegrationsService { constructor(private prisma:PrismaService){}
 private hash(v:string){return createHash('sha256').update(v).digest('hex')}
 async createApiKey(org:string,user:string,dto:CreateApiKeyDto){const raw='ax_'+randomBytes(32).toString('base64url'); const row=await this.prisma.apiKey.create({data:{organizationId:org,createdById:user,name:dto.name,prefix:raw.slice(0,11),keyHash:this.hash(raw),scopes:dto.scopes,expiresAt:dto.expiresAt?new Date(dto.expiresAt):undefined}}); return {...row,key:raw,keyHash:undefined};}
 listApiKeys(org:string){return this.prisma.apiKey.findMany({where:{organizationId:org},select:{id:true,name:true,prefix:true,scopes:true,status:true,lastUsedAt:true,expiresAt:true,createdAt:true,createdBy:{select:{firstName:true,lastName:true}}},orderBy:{createdAt:'desc'}})}
 async revokeApiKey(org:string,id:string){const r=await this.prisma.apiKey.updateMany({where:{id,organizationId:org,status:'ACTIVE'},data:{status:'REVOKED',revokedAt:new Date()}});if(!r.count)throw new NotFoundException('API key not found');return {revoked:true}}
 async createWebhook(org:string,user:string,dto:CreateWebhookDto){if(!dto.events.includes('*')&&dto.events.some(x=>!x.includes('.')))throw new BadRequestException('Events must use domain event names or *'); const secret='whsec_'+randomBytes(24).toString('base64url'); const row=await this.prisma.legacyWebhookSubscription.create({data:{organizationId:org,createdById:user,name:dto.name,url:dto.url,events:dto.events,secretHash:this.hash(secret),secretEncrypted:Buffer.from(secret).toString('base64')}});return {...row,secret,secretHash:undefined,secretEncrypted:undefined}}
 listWebhooks(org:string){return this.prisma.legacyWebhookSubscription.findMany({where:{organizationId:org},select:{id:true,name:true,url:true,events:true,status:true,consecutiveFailures:true,lastDeliveredAt:true,createdAt:true,_count:{select:{deliveries:true}}},orderBy:{createdAt:'desc'}})}
 async updateWebhook(org:string,id:string,dto:UpdateWebhookDto){const found=await this.prisma.legacyWebhookSubscription.findFirst({where:{id,organizationId:org}});if(!found)throw new NotFoundException('Webhook not found');return this.prisma.legacyWebhookSubscription.update({where:{id},data:dto})}
 deliveries(org:string,id:string){return this.prisma.legacyWebhookDelivery.findMany({where:{organizationId:org,subscriptionId:id},orderBy:{createdAt:'desc'},take:50})}
 async retry(org:string,id:string){const d=await this.prisma.legacyWebhookDelivery.findFirst({where:{id,organizationId:org}});if(!d)throw new NotFoundException('Delivery not found');return this.prisma.legacyWebhookDelivery.update({where:{id},data:{status:'PENDING',nextAttemptAt:new Date(),lastError:null}})}
}
