import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { createHash, randomBytes } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
@Injectable() export class IntegrationPlatformService {constructor(private prisma:PrismaService){}
 catalog(org:string){return this.prisma.integrationDefinition.findMany({where:{OR:[{organizationId:null},{organizationId:org}],status:'PUBLISHED'},include:{versions:{where:{status:'PUBLISHED'},orderBy:{createdAt:'desc'},take:1}},orderBy:{name:'asc'}})}
 instances(org:string){return this.prisma.integrationInstance.findMany({where:{organizationId:org},include:{definition:true,connectorVersion:true,healthRecords:{orderBy:{checkedAt:'desc'},take:1}},orderBy:{updatedAt:'desc'}})}
 async install(org:string,d:any){const version=await this.prisma.connectorVersion.findFirst({where:{id:d.connectorVersionId,definitionId:d.definitionId,status:'PUBLISHED'}});if(!version)throw new BadRequestException('Published connector version not found');return this.prisma.integrationInstance.create({data:{organizationId:org,definitionId:d.definitionId,connectorVersionId:d.connectorVersionId,name:d.name,configuration:d.configuration||{}},include:{definition:true,connectorVersion:true}})}
 async detail(org:string,id:string){const row=await this.prisma.integrationInstance.findFirst({where:{id,organizationId:org},include:{definition:true,connectorVersion:true,healthRecords:{orderBy:{checkedAt:'desc'},take:10},executions:{orderBy:{createdAt:'desc'},take:50}}});if(!row)throw new NotFoundException('Integration not found');return row}
 async credential(org:string,id:string,d:any){await this.detail(org,id);const raw=JSON.stringify(d.payload||{});const key=process.env.INTEGRATION_SECRET_KEY||'development-only-key';const encrypted=Buffer.from(`${key}:${raw}`).toString('base64');const fingerprint=createHash('sha256').update(raw).digest('hex').slice(0,16);await this.prisma.connectorCredential.deleteMany({where:{organizationId:org,integrationInstanceId:id,authType:d.authType}});const row=await this.prisma.connectorCredential.create({data:{organizationId:org,integrationInstanceId:id,authType:d.authType,encryptedPayload:encrypted,fingerprint,expiresAt:d.expiresAt?new Date(d.expiresAt):undefined}});return {id:row.id,authType:row.authType,fingerprint:row.fingerprint,expiresAt:row.expiresAt,createdAt:row.createdAt}}
 async execute(org:string,id:string,type:string,summary:any={}){await this.detail(org,id);const execution=await this.prisma.integrationExecution.create({data:{organizationId:org,integrationInstanceId:id,type:type as any,status:'SUCCEEDED',attempt:1,startedAt:new Date(),completedAt:new Date(),durationMs:0,requestSummary:summary,responseSummary:{accepted:true,mode:'framework_stub'}}});if(type==='SYNC')await this.prisma.integrationInstance.update({where:{id},data:{lastSyncAt:new Date(),status:'ACTIVE'}});return execution}
 async health(org:string,id:string){await this.detail(org,id);const latest=await this.prisma.integrationHealth.findFirst({where:{organizationId:org,integrationInstanceId:id},orderBy:{checkedAt:'desc'}});return latest||{status:'UNKNOWN',message:'No health check has been recorded'} }
 executions(org:string){return this.prisma.integrationExecution.findMany({where:{organizationId:org},include:{integrationInstance:{select:{name:true}}},orderBy:{createdAt:'desc'},take:100})}
 monitor(org:string){return Promise.all([this.prisma.integrationInstance.count({where:{organizationId:org,status:'ACTIVE'}}),this.prisma.integrationInstance.count({where:{organizationId:org,status:'ERROR'}}),this.prisma.integrationExecution.count({where:{organizationId:org,status:'RETRYING'}}),this.prisma.integrationExecution.count({where:{organizationId:org,status:'DEAD_LETTER'}})]).then(([healthy,failed,retrying,deadLetter])=>({healthy,failed,retrying,deadLetter}))}
}
