import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { ConfigService } from '@nestjs/config';
import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, randomUUID } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
import { CreateWebhookSubscriptionDto, EmitWebhookEventDto, UpdateWebhookSubscriptionDto } from './dto';

@Injectable()
export class WebhookPlatformService {
  constructor(private readonly prisma:PrismaService, private readonly config:ConfigService){}
  private key(){const raw=this.config.get<string>('WEBHOOK_ENCRYPTION_KEY')||this.config.get<string>('JWT_SECRET')||'achievex-development-webhook-key';return createHash('sha256').update(raw).digest()}
  private encrypt(value:string){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',this.key(),iv);const body=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return [iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),body.toString('base64url')].join('.')}
  private decrypt(value:string){const [iv,tag,body]=value.split('.');const d=createDecipheriv('aes-256-gcm',this.key(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(body,'base64url')),d.final()]).toString('utf8')}
  private async subscription(org:string,id:string){const row=await this.prisma.webhookSubscription.findFirst({where:{id,organizationId:org}});if(!row)throw new NotFoundException('Webhook subscription not found');return row}
  listSubscriptions(org:string){return this.prisma.webhookSubscription.findMany({where:{organizationId:org},select:{id:true,applicationId:true,name:true,endpointUrl:true,eventTypes:true,status:true,secretPrefix:true,description:true,headers:true,maxAttempts:true,timeoutMs:true,createdByUserId:true,createdAt:true,updatedAt:true},orderBy:{createdAt:'desc'}})}
  async createSubscription(org:string,userId:string,d:CreateWebhookSubscriptionDto){if(!d.eventTypes?.length)throw new BadRequestException('At least one event type is required');if(!d.endpointUrl.startsWith('https://'))throw new BadRequestException('Webhook endpoint must use HTTPS');if(d.applicationId){const app=await this.prisma.developerApplication.findFirst({where:{id:d.applicationId,organizationId:org,status:'ACTIVE'}});if(!app)throw new BadRequestException('Active developer application not found')}const secret=`whsec_${randomBytes(32).toString('base64url')}`;const row=await this.prisma.webhookSubscription.create({data:{organizationId:org,applicationId:d.applicationId,name:d.name.trim(),endpointUrl:d.endpointUrl,eventTypes:[...new Set(d.eventTypes)],description:d.description,headers:d.headers||{},maxAttempts:d.maxAttempts||8,timeoutMs:d.timeoutMs||10000,status:'ACTIVE',secretCiphertext:this.encrypt(secret),secretPrefix:secret.slice(0,14),createdByUserId:userId}});return {...row,secret,warning:'Copy this signing secret now. It is encrypted at rest and is not returned again.'}}
  async updateSubscription(org:string,id:string,d:UpdateWebhookSubscriptionDto){await this.subscription(org,id);if(d.endpointUrl&&!d.endpointUrl.startsWith('https://'))throw new BadRequestException('Webhook endpoint must use HTTPS');return this.prisma.webhookSubscription.update({where:{id},data:{name:d.name,endpointUrl:d.endpointUrl,eventTypes:d.eventTypes? [...new Set(d.eventTypes)]:undefined,status:d.status,description:d.description,headers:d.headers,maxAttempts:d.maxAttempts,timeoutMs:d.timeoutMs}})}
  async rotateSecret(org:string,id:string){await this.subscription(org,id);const secret=`whsec_${randomBytes(32).toString('base64url')}`;const row=await this.prisma.webhookSubscription.update({where:{id},data:{secretCiphertext:this.encrypt(secret),secretPrefix:secret.slice(0,14)}});return {id:row.id,secret,secretPrefix:row.secretPrefix,warning:'Copy this signing secret now. Previous signatures can no longer be verified with the old secret.'}}
  async emit(org:string,d:EmitWebhookEventDto){const event=await this.prisma.webhookEvent.create({data:{organizationId:org,type:d.type,subjectType:d.subjectType,subjectId:d.subjectId,payload:d.payload as Prisma.InputJsonValue,correlationId:d.correlationId||randomUUID(),status:'PENDING'}});const subscriptions=await this.prisma.webhookSubscription.findMany({where:{organizationId:org,status:'ACTIVE',eventTypes:{has:d.type}}});if(subscriptions.length)await this.prisma.webhookDelivery.createMany({data:subscriptions.map(s=>({organizationId:org,subscriptionId:s.id,eventId:event.id,status:'PENDING' as const,nextAttemptAt:new Date()})),skipDuplicates:true});await this.prisma.webhookEvent.update({where:{id:event.id},data:{status:'DISPATCHED',dispatchedAt:new Date()}});return {...event,deliveryCount:subscriptions.length}}
  deliveries(org:string,take=100,status?:string){return this.prisma.webhookDelivery.findMany({where:{organizationId:org,...(status?{status:status as any}:{})},include:{subscription:{select:{id:true,name:true,endpointUrl:true}},event:{select:{id:true,type:true,subjectType:true,subjectId:true,occurredAt:true,correlationId:true}}},orderBy:{createdAt:'desc'},take:Math.min(250,Math.max(1,take))})}
  async attempt(org:string,id:string){const delivery=await this.prisma.webhookDelivery.findFirst({where:{id,organizationId:org},include:{subscription:true,event:true}});if(!delivery)throw new NotFoundException('Webhook delivery not found');if(['SUCCEEDED','CANCELLED'].includes(delivery.status))return delivery;const attempt=delivery.attemptCount+1;await this.prisma.webhookDelivery.update({where:{id},data:{status:'DELIVERING',attemptCount:attempt,lastAttemptAt:new Date()}});const timestamp=Math.floor(Date.now()/1000).toString();const envelope={id:delivery.event.id,type:delivery.event.type,occurredAt:delivery.event.occurredAt.toISOString(),subject:{type:delivery.event.subjectType,id:delivery.event.subjectId},data:delivery.event.payload};const body=JSON.stringify(envelope);const signature=createHmac('sha256',this.decrypt(delivery.subscription.secretCiphertext)).update(`${timestamp}.${body}`).digest('hex');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),delivery.subscription.timeoutMs);const started=Date.now();try{const response=await fetch(delivery.subscription.endpointUrl,{method:'POST',body,signal:controller.signal,headers:{...((delivery.subscription.headers||{}) as Record<string,string>),'content-type':'application/json','user-agent':'AchieveX-Webhooks/1.0','x-achievex-event-id':delivery.event.id,'x-achievex-delivery-id':delivery.id,'x-achievex-event-type':delivery.event.type,'x-achievex-timestamp':timestamp,'x-achievex-signature':`v1=${signature}`,'x-achievex-attempt':String(attempt)}});const snippet=(await response.text()).slice(0,1000);const duration=Date.now()-started;if(response.ok)return this.prisma.webhookDelivery.update({where:{id},data:{status:'SUCCEEDED',deliveredAt:new Date(),responseStatus:response.status,responseBodySnippet:snippet,responseHeaders:Object.fromEntries(response.headers.entries()),durationMs:duration,lastError:null}});return this.fail(delivery,attempt,`HTTP ${response.status}`,response.status,snippet,duration)}catch(e:any){return this.fail(delivery,attempt,e?.name==='AbortError'?'Delivery timed out':String(e?.message||e),undefined,undefined,Date.now()-started)}finally{clearTimeout(timer)}}
  private fail(delivery:any,attempt:number,error:string,responseStatus?:number,snippet?:string,durationMs?:number){const exhausted=attempt>=delivery.subscription.maxAttempts;const delay=Math.min(86400,Math.pow(2,Math.max(0,attempt-1))*60);return this.prisma.webhookDelivery.update({where:{id:delivery.id},data:{status:exhausted?'DEAD_LETTERED':'RETRY_SCHEDULED',nextAttemptAt:exhausted?delivery.nextAttemptAt:new Date(Date.now()+delay*1000),deadLetteredAt:exhausted?new Date():null,lastError:error,responseStatus,responseBodySnippet:snippet,durationMs}})}
  async processDue(org:string,limit=25){const due=await this.prisma.webhookDelivery.findMany({where:{organizationId:org,status:{in:['PENDING','RETRY_SCHEDULED']},nextAttemptAt:{lte:new Date()}},orderBy:{nextAttemptAt:'asc'},take:Math.min(100,Math.max(1,limit))});const results=[];for(const d of due)results.push(await this.attempt(org,d.id));return {processed:results.length,results}}
  async replay(org:string,id:string){const source=await this.prisma.webhookDelivery.findFirst({where:{id,organizationId:org},include:{subscription:true}});if(!source)throw new NotFoundException('Webhook delivery not found');if(source.subscription.status!=='ACTIVE')throw new BadRequestException('Subscription must be active before replay');const existing=await this.prisma.webhookDelivery.create({data:{organizationId:org,subscriptionId:source.subscriptionId,eventId:source.eventId,status:'PENDING',nextAttemptAt:new Date(),replayedFromId:source.id}}).catch(()=>null);if(!existing)throw new BadRequestException('A delivery for this subscription and event already exists');return this.attempt(org,existing.id)}
  async analytics(org:string,days=30){const since=new Date(Date.now()-Math.min(90,Math.max(1,days))*86400000);const [total,success,dead,avg,byStatus]=await Promise.all([this.prisma.webhookDelivery.count({where:{organizationId:org,createdAt:{gte:since}}}),this.prisma.webhookDelivery.count({where:{organizationId:org,createdAt:{gte:since},status:'SUCCEEDED'}}),this.prisma.webhookDelivery.count({where:{organizationId:org,createdAt:{gte:since},status:'DEAD_LETTERED'}}),this.prisma.webhookDelivery.aggregate({where:{organizationId:org,createdAt:{gte:since},durationMs:{not:null}},_avg:{durationMs:true}}),this.prisma.webhookDelivery.groupBy({by:['status'],where:{organizationId:org,createdAt:{gte:since}},_count:true})]);return {days,total,successful:success,deadLettered:dead,successRate:total?Number(((success/total)*100).toFixed(2)):0,averageDurationMs:Math.round(avg._avg.durationMs||0),byStatus}}
}
