'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { AdminShell } from '../../../components/admin-shell';
import { api } from '../../../lib/api';
type Period={start:string;end:string;capacityHours:number;allocatedHours:number;remainingHours:number;utilizationPercent:number;state:'UNDERUTILIZED'|'BALANCED'|'OVERALLOCATED'};
type ResourceRow={id:string;displayName:string;jobTitle?:string;teams:string[];periods:Period[]};
type Plan={from:string;to:string;granularity:'week'|'month';resources:ResourceRow[];periods:Period[];summary:{capacityHours:number;allocatedHours:number;overallocatedCells:number;underutilizedCells:number}};
type Conflict={resourceId:string;resourceName:string;start:string;end:string;capacityHours:number;allocatedHours:number;overByHours:number;utilizationPercent:number};
const date=(d:Date)=>d.toISOString().slice(0,10);
const label=(p:Period)=>`${p.start.slice(5)} – ${p.end.slice(5)}`;
export default function CapacityPage(){const today=new Date(),future=new Date(today);future.setDate(future.getDate()+55);const[from,setFrom]=useState(date(today)),[to,setTo]=useState(date(future)),[granularity,setGranularity]=useState<'week'|'month'>('week'),[plan,setPlan]=useState<Plan|null>(null),[conflicts,setConflicts]=useState<Conflict[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const utilization=useMemo(()=>plan?.summary.capacityHours?Math.round(plan.summary.allocatedHours/plan.summary.capacityHours*100):0,[plan]);
 async function load(){setBusy(true);try{setError('');const qs=`from=${from}&to=${to}&granularity=${granularity}`;const[p,c]=await Promise.all([api<Plan>(`/resource-management/capacity?${qs}`),api<Conflict[]>(`/resource-management/capacity/conflicts?${qs}`)]);setPlan(p);setConflicts(c)}catch(e){setError(e instanceof Error?e.message:'Unable to load capacity plan')}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 return <AdminShell title="Capacity planning" subtitle="Forecast demand against working calendars, holidays, availability, and active allocations." action={<Link className="buttonLink" href="/resources">Back to resources</Link>}>
 {error&&<div className="formError">{error}</div>}
 <section className="panel"><div className="executionInlineForm"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Period<select value={granularity} onChange={e=>setGranularity(e.target.value as any)}><option value="week">Weekly</option><option value="month">Monthly</option></select></label><button onClick={load} disabled={busy}>{busy?'Calculating…':'Refresh forecast'}</button></div></section>
 <section className="metrics executionMetrics"><article><p>Forecast utilization</p><strong>{utilization}%</strong><span>{Math.round(plan?.summary.allocatedHours||0)} / {Math.round(plan?.summary.capacityHours||0)} hours</span></article><article><p>Overallocated periods</p><strong>{plan?.summary.overallocatedCells??'—'}</strong><span>Resource-period conflicts</span></article><article><p>Available capacity</p><strong>{Math.round((plan?.summary.capacityHours||0)-(plan?.summary.allocatedHours||0))}h</strong><span>Across selected horizon</span></article><article><p>Underutilized periods</p><strong>{plan?.summary.underutilizedCells??'—'}</strong><span>Below 60% utilization</span></article></section>
 <section className="panel tablePanel"><div className="panelHead"><div><h2>Capacity heat map</h2><p>Demand versus available hours by resource and period.</p></div></div><div className="capacityTable"><div className="capacityRow capacityHead"><span>Resource</span>{plan?.periods.map(p=><span key={p.start}>{label(p)}</span>)}</div>{plan?.resources.map(r=><div className="capacityRow" key={r.id}><span><strong>{r.displayName}</strong><small>{r.jobTitle||r.teams.join(', ')||'Resource'}</small></span>{r.periods.map(p=><span key={p.start} className={`capacityCell ${p.state.toLowerCase()}`}><strong>{Math.round(p.utilizationPercent)}%</strong><small>{Math.round(p.allocatedHours)}/{Math.round(p.capacityHours)}h</small></span>)}</div>)}</div></section>
 <section className="panel tablePanel"><div className="panelHead"><div><h2>Allocation conflicts</h2><p>Periods where committed demand exceeds calendar-adjusted capacity.</p></div></div><div className="executionTable"><div className="executionRow executionHead"><span>Resource</span><span>Period</span><span>Capacity</span><span>Demand</span><span>Over by</span><span>Utilization</span></div>{conflicts.length?conflicts.map(c=><div className="executionRow" key={`${c.resourceId}-${c.start}`}><span><strong>{c.resourceName}</strong></span><span>{c.start} – {c.end}</span><span>{Math.round(c.capacityHours)}h</span><span>{Math.round(c.allocatedHours)}h</span><span className="negative">{Math.round(c.overByHours)}h</span><span><strong className="negative">{Math.round(c.utilizationPercent)}%</strong></span></div>):<p className="emptyState">No allocation conflicts in this horizon.</p>}</div></section>
 </AdminShell>}
