export type PeriodGranularity='week'|'month';
export type CalendarInput={hoursPerDay:number;workingDays:number[];holidays?:string[]};
export type ExceptionInput={startsAt:Date;endsAt:Date;availableHours:number};
export type TimeAllocationInput={startsAt:Date;endsAt:Date;allocationPercent:number;hoursPerWeek?:number|null};
export type CapacityPeriod={start:string;end:string;capacityHours:number;allocatedHours:number;remainingHours:number;utilizationPercent:number;state:'UNDERUTILIZED'|'BALANCED'|'OVERALLOCATED'};
const day=(d:Date)=>new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));
const iso=(d:Date)=>d.toISOString().slice(0,10);
const overlap=(a:Date,b:Date,c:Date,d:Date)=>a<=d&&b>=c;
export function periodBounds(start:Date,end:Date,granularity:PeriodGranularity){const out:{start:Date;end:Date}[]=[];let cursor=day(start);while(cursor<=end){let pStart=new Date(cursor),pEnd:Date;if(granularity==='week'){const wd=(pStart.getUTCDay()+6)%7;pStart.setUTCDate(pStart.getUTCDate()-wd);pEnd=new Date(pStart);pEnd.setUTCDate(pEnd.getUTCDate()+6)}else{pStart=new Date(Date.UTC(cursor.getUTCFullYear(),cursor.getUTCMonth(),1));pEnd=new Date(Date.UTC(cursor.getUTCFullYear(),cursor.getUTCMonth()+1,0))}if(!out.some(x=>+x.start===+pStart))out.push({start:pStart,end:pEnd});cursor=new Date(pEnd);cursor.setUTCDate(cursor.getUTCDate()+1)}return out.filter(x=>x.end>=start&&x.start<=end)}
export function workingCapacity(start:Date,end:Date,calendar:CalendarInput,exceptions:ExceptionInput[]=[]){const holidays=new Set(calendar.holidays??[]);let total=0;for(let d=day(start);d<=end;d=new Date(d.getTime()+86400000)){if(!calendar.workingDays.includes(d.getUTCDay())||holidays.has(iso(d)))continue;total+=calendar.hoursPerDay}for(const ex of exceptions){if(!overlap(ex.startsAt,ex.endsAt,start,end))continue;for(let d=day(ex.startsAt<start?start:ex.startsAt);d<=day(ex.endsAt>end?end:ex.endsAt);d=new Date(d.getTime()+86400000)){if(calendar.workingDays.includes(d.getUTCDay())&&!holidays.has(iso(d)))total-=calendar.hoursPerDay}total+=ex.availableHours}return Math.max(0,Math.round(total*100)/100)}
export function allocatedHours(start:Date,end:Date,capacityHours:number,allocations:TimeAllocationInput[]){return Math.round(allocations.filter(a=>overlap(a.startsAt,a.endsAt,start,end)).reduce((sum,a)=>{if(a.hoursPerWeek!=null){const days=Math.max(1,Math.round((end.getTime()-start.getTime())/86400000)+1);return sum+a.hoursPerWeek*(days/7)}return sum+capacityHours*(a.allocationPercent/100)},0)*100)/100}
export function classifyUtilization(percent:number){return percent>100?'OVERALLOCATED':percent<60?'UNDERUTILIZED':'BALANCED'}
export function buildCapacityPeriods(start:Date,end:Date,granularity:PeriodGranularity,calendar:CalendarInput,exceptions:ExceptionInput[],allocations:TimeAllocationInput[]):CapacityPeriod[]{return periodBounds(start,end,granularity).map(p=>{const s=p.start<start?start:p.start,e=p.end>end?end:p.end,c=workingCapacity(s,e,calendar,exceptions),a=allocatedHours(s,e,c,allocations),u=c?Math.round(a/c*10000)/100:0;return{start:iso(s),end:iso(e),capacityHours:c,allocatedHours:a,remainingHours:Math.round((c-a)*100)/100,utilizationPercent:u,state:classifyUtilization(u)}})}
