import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { EventsService } from '../events/events.service';
import { AddTeamMemberDto, AssignSkillDto, CapacityQueryDto, CreateAllocationDto, CreateAvailabilityExceptionDto, CreateHolidayCalendarDto, CreateResourceDto, CreateResourceTeamDto, CreateSkillDto, CreateWorkingCalendarDto, UpdateResourceDto, UpdateWorkingCalendarDto, ScheduleQueryDto, RescheduleAllocationDto, PreviewScheduleScenarioDto, WorkforceAnalyticsQueryDto } from './dto/resource-management.dto';
import { calculateAllocatedHours, calculateUtilization, isOverallocated } from './resource-capacity';
import { buildCapacityPeriods } from './capacity-planning';
import { previewScenario } from './enterprise-scheduling';
import { buildExecutiveSummary, hiringSignals, resourceAnalytics, skillDistribution, teamRollups } from './workforce-analytics';
@Injectable() export class ResourceManagementService{
 constructor(private prisma:PrismaService,private events:EventsService){}
 private event(org:string,user:string,name:string,type:string,id:string,payload:any={}){return this.events.publish({organizationId:org,actorUserId:user,eventName:name,aggregateType:type,aggregateId:id,payload});}
 async overview(org:string){const [resources,teams,skills,allocations]=await Promise.all([this.prisma.resource.findMany({where:{organizationId:org},include:{allocations:{where:{status:{in:['PLANNED','ACTIVE']}}}}}),this.prisma.resourceTeam.count({where:{organizationId:org}}),this.prisma.skill.count({where:{organizationId:org}}),this.prisma.resourceAllocation.count({where:{organizationId:org,status:{in:['PLANNED','ACTIVE']}}})]);const capacity=resources.reduce((s,r)=>s+Number(r.capacityHoursPerWeek),0),allocated=resources.reduce((s,r)=>s+calculateAllocatedHours(Number(r.capacityHoursPerWeek),r.allocations.map(a=>({allocationPercent:Number(a.allocationPercent),hoursPerWeek:a.hoursPerWeek?Number(a.hoursPerWeek):null}))),0);return{resources:resources.length,teams,skills,allocations,capacityHours:capacity,allocatedHours:allocated,utilizationPercent:capacity?Math.round(allocated/capacity*10000)/100:0,overallocatedResources:resources.filter(r=>isOverallocated(Number(r.capacityHoursPerWeek),r.allocations.map(a=>({allocationPercent:Number(a.allocationPercent),hoursPerWeek:a.hoursPerWeek?Number(a.hoursPerWeek):null})))).length};}
 listResources(org:string){return this.prisma.resource.findMany({where:{organizationId:org},include:{skills:{include:{skill:true}},teamMemberships:{include:{team:true}},allocations:{where:{status:{in:['PLANNED','ACTIVE']}},include:{project:{select:{id:true,key:true,name:true}},program:{select:{id:true,name:true}}}}},orderBy:{displayName:'asc'}}).then(rows=>rows.map(r=>({...r,capacity:{allocatedHours:calculateAllocatedHours(Number(r.capacityHoursPerWeek),r.allocations.map(a=>({allocationPercent:Number(a.allocationPercent),hoursPerWeek:a.hoursPerWeek?Number(a.hoursPerWeek):null}))),utilizationPercent:calculateUtilization(Number(r.capacityHoursPerWeek),r.allocations.map(a=>({allocationPercent:Number(a.allocationPercent),hoursPerWeek:a.hoursPerWeek?Number(a.hoursPerWeek):null}))),overallocated:isOverallocated(Number(r.capacityHoursPerWeek),r.allocations.map(a=>({allocationPercent:Number(a.allocationPercent),hoursPerWeek:a.hoursPerWeek?Number(a.hoursPerWeek):null})))}})));}
 async createResource(org:string,user:string,d:CreateResourceDto){if(d.userId){const u=await this.prisma.user.findFirst({where:{id:d.userId,organizationId:org}});if(!u)throw new BadRequestException('User is outside the tenant');}const r=await this.prisma.resource.create({data:{...d,organizationId:org}});await this.event(org,user,'resource.created','Resource',r.id,{displayName:r.displayName});return r;}
 async updateResource(org:string,user:string,id:string,d:UpdateResourceDto){const r=await this.prisma.resource.findFirst({where:{id,organizationId:org}});if(!r)throw new NotFoundException('Resource not found');const out=await this.prisma.resource.update({where:{id},data:d});await this.event(org,user,'resource.updated','Resource',id,d);return out;}
 listTeams(org:string){return this.prisma.resourceTeam.findMany({where:{organizationId:org},include:{leadUser:{select:{id:true,firstName:true,lastName:true}},memberships:{include:{resource:true}}},orderBy:{name:'asc'}})}
 async createTeam(org:string,user:string,d:CreateResourceTeamDto){const t=await this.prisma.resourceTeam.create({data:{...d,organizationId:org}});await this.event(org,user,'resource.team_created','ResourceTeam',t.id,{name:t.name});return t;}
 async addTeamMember(org:string,user:string,teamId:string,d:AddTeamMemberDto){const [team,res]=await Promise.all([this.prisma.resourceTeam.findFirst({where:{id:teamId,organizationId:org}}),this.prisma.resource.findFirst({where:{id:d.resourceId,organizationId:org}})]);if(!team||!res)throw new BadRequestException('Team or resource not found');const m=await this.prisma.resourceTeamMembership.upsert({where:{teamId_resourceId:{teamId,resourceId:d.resourceId}},create:{organizationId:org,teamId,resourceId:d.resourceId,userId:res.userId,role:d.role,allocationPercent:d.allocationPercent??100},update:{role:d.role,allocationPercent:d.allocationPercent??100}});await this.event(org,user,'resource.team_member_assigned','ResourceTeam',teamId,{resourceId:d.resourceId});return m;}
 listSkills(org:string){return this.prisma.skill.findMany({where:{organizationId:org},include:{_count:{select:{resources:true}}},orderBy:{name:'asc'}})}
 async createSkill(org:string,user:string,d:CreateSkillDto){const s=await this.prisma.skill.create({data:{...d,organizationId:org}});await this.event(org,user,'resource.skill_created','Skill',s.id,{name:s.name});return s;}
 async assignSkill(org:string,user:string,resourceId:string,d:AssignSkillDto){const [r,s]=await Promise.all([this.prisma.resource.findFirst({where:{id:resourceId,organizationId:org}}),this.prisma.skill.findFirst({where:{id:d.skillId,organizationId:org}})]);if(!r||!s)throw new BadRequestException('Resource or skill not found');const out=await this.prisma.resourceSkill.upsert({where:{resourceId_skillId:{resourceId,skillId:d.skillId}},create:{organizationId:org,resourceId,skillId:d.skillId,proficiency:d.proficiency,yearsExperience:d.yearsExperience},update:{proficiency:d.proficiency,yearsExperience:d.yearsExperience}});await this.event(org,user,'resource.skill_assigned','Resource',resourceId,{skillId:d.skillId});return out;}
 listAllocations(org:string){return this.prisma.resourceAllocation.findMany({where:{organizationId:org},include:{resource:true,project:{select:{id:true,key:true,name:true}},program:{select:{id:true,name:true}}},orderBy:{startsAt:'desc'}})}
 async createAllocation(org:string,user:string,d:CreateAllocationDto){if(new Date(d.endsAt)<=new Date(d.startsAt))throw new BadRequestException('Allocation end must be after start');const resource=await this.prisma.resource.findFirst({where:{id:d.resourceId,organizationId:org}});if(!resource)throw new BadRequestException('Resource not found');if(d.projectId&&!await this.prisma.project.findFirst({where:{id:d.projectId,organizationId:org}}))throw new BadRequestException('Project is outside the tenant');if(d.programId&&!await this.prisma.program.findFirst({where:{id:d.programId,organizationId:org}}))throw new BadRequestException('Program is outside the tenant');const a=await this.prisma.resourceAllocation.create({data:{...d,organizationId:org,startsAt:new Date(d.startsAt),endsAt:new Date(d.endsAt)}});await this.event(org,user,'resource.allocation_created','ResourceAllocation',a.id,{resourceId:d.resourceId,allocationPercent:d.allocationPercent});return a;}
 listCalendars(org:string){return this.prisma.workingCalendar.findMany({where:{organizationId:org},orderBy:{name:'asc'}})}
 async createCalendar(org:string,user:string,d:CreateWorkingCalendarDto){if(d.isDefault)await this.prisma.workingCalendar.updateMany({where:{organizationId:org,isDefault:true},data:{isDefault:false}});const c=await this.prisma.workingCalendar.create({data:{...d,organizationId:org}});await this.event(org,user,'resource.calendar_created','WorkingCalendar',c.id,{name:c.name});return c;}
 async capacityPlan(org:string,q:CapacityQueryDto){const from=new Date(q.from),to=new Date(q.to);if(to<from)throw new BadRequestException('Capacity range is invalid');const where:any={organizationId:org};if(q.resourceId)where.id=q.resourceId;if(q.teamId)where.teamMemberships={some:{teamId:q.teamId}};const resources=await this.prisma.resource.findMany({where,include:{workingCalendar:{include:{holidayCalendar:true}},availabilityExceptions:{where:{startsAt:{lte:to},endsAt:{gte:from}}},allocations:{where:{status:{in:['PLANNED','ACTIVE']},startsAt:{lte:to},endsAt:{gte:from}}},teamMemberships:{include:{team:true}}}});const defaultCalendar=await this.prisma.workingCalendar.findFirst({where:{organizationId:org,isDefault:true},include:{holidayCalendar:true}});const rows=resources.map(r=>{const c=r.workingCalendar||defaultCalendar;const holidays=((c?.holidayCalendar?.holidays as any[])||[]).map(h=>typeof h==='string'?h:h.date).filter(Boolean);const periods=buildCapacityPeriods(from,to,q.granularity||'week',{hoursPerDay:Number(c?.hoursPerDay||8),workingDays:c?.workingDays||[0,1,2,3,4],holidays},r.availabilityExceptions.map(x=>({startsAt:x.startsAt,endsAt:x.endsAt,availableHours:Number(x.availableHours)})),r.allocations.map(a=>({startsAt:a.startsAt,endsAt:a.endsAt,allocationPercent:Number(a.allocationPercent),hoursPerWeek:a.hoursPerWeek?Number(a.hoursPerWeek):null})));return{id:r.id,displayName:r.displayName,jobTitle:r.jobTitle,teams:r.teamMemberships.map(m=>m.team.name),periods}});const periodMap=new Map<string,any>();for(const r of rows)for(const p of r.periods){const key=p.start+'|'+p.end,current=periodMap.get(key)||{start:p.start,end:p.end,capacityHours:0,allocatedHours:0};current.capacityHours+=p.capacityHours;current.allocatedHours+=p.allocatedHours;periodMap.set(key,current)}const periods=[...periodMap.values()].map(p=>({...p,remainingHours:Math.round((p.capacityHours-p.allocatedHours)*100)/100,utilizationPercent:p.capacityHours?Math.round(p.allocatedHours/p.capacityHours*10000)/100:0,state:p.allocatedHours>p.capacityHours?'OVERALLOCATED':p.capacityHours&&p.allocatedHours/p.capacityHours<.6?'UNDERUTILIZED':'BALANCED'}));return{from:q.from,to:q.to,granularity:q.granularity||'week',resources:rows,periods,summary:{capacityHours:periods.reduce((s,p)=>s+p.capacityHours,0),allocatedHours:periods.reduce((s,p)=>s+p.allocatedHours,0),overallocatedCells:rows.flatMap(r=>r.periods).filter(p=>p.state==='OVERALLOCATED').length,underutilizedCells:rows.flatMap(r=>r.periods).filter(p=>p.state==='UNDERUTILIZED').length}}}
 async schedule(org:string,q:ScheduleQueryDto){const from=new Date(q.from),to=new Date(q.to);if(to<from)throw new BadRequestException('Schedule range is invalid');const resourceWhere:any={organizationId:org};if(q.resourceId)resourceWhere.id=q.resourceId;if(q.teamId)resourceWhere.teamMemberships={some:{teamId:q.teamId}};const resources=await this.prisma.resource.findMany({where:resourceWhere,include:{teamMemberships:{include:{team:true}},availabilityExceptions:{where:{startsAt:{lte:to},endsAt:{gte:from}}},allocations:{where:{status:{in:['PLANNED','ACTIVE']},startsAt:{lte:to},endsAt:{gte:from}},include:{project:{select:{id:true,key:true,name:true}},program:{select:{id:true,name:true}}}}},orderBy:{displayName:'asc'}});return{from:q.from,to:q.to,timezone:q.timezone||'Asia/Riyadh',resources:resources.map(r=>({id:r.id,displayName:r.displayName,jobTitle:r.jobTitle,timezone:r.timezone,teams:r.teamMemberships.map(m=>m.team.name),leave:r.availabilityExceptions.map(x=>({id:x.id,startsAt:x.startsAt,endsAt:x.endsAt,availableHours:Number(x.availableHours),reason:x.reason})),allocations:r.allocations.map(a=>({...a,allocationPercent:Number(a.allocationPercent),hoursPerWeek:a.hoursPerWeek?Number(a.hoursPerWeek):null}))}))};}
 async rescheduleAllocation(org:string,user:string,id:string,d:RescheduleAllocationDto){const a=await this.prisma.resourceAllocation.findFirst({where:{id,organizationId:org}});if(!a)throw new NotFoundException('Allocation not found');if(new Date(d.endsAt)<new Date(d.startsAt))throw new BadRequestException('Schedule end must be on or after start');if(d.resourceId&&!await this.prisma.resource.findFirst({where:{id:d.resourceId,organizationId:org}}))throw new BadRequestException('Resource is outside the tenant');const out=await this.prisma.resourceAllocation.update({where:{id},data:{resourceId:d.resourceId,startsAt:new Date(d.startsAt),endsAt:new Date(d.endsAt),allocationPercent:d.allocationPercent,hoursPerWeek:d.hoursPerWeek}});await this.event(org,user,'resource.allocation_rescheduled','ResourceAllocation',id,{resourceId:out.resourceId,startsAt:out.startsAt,endsAt:out.endsAt});return out;}
 async previewScheduleScenario(org:string,d:PreviewScheduleScenarioDto){const from=new Date(d.from),to=new Date(d.to);if(to<from)throw new BadRequestException('Scenario range is invalid');const allocations=await this.prisma.resourceAllocation.findMany({where:{organizationId:org,status:{in:['PLANNED','ACTIVE']},startsAt:{lte:to},endsAt:{gte:from},...(d.teamId?{resource:{teamMemberships:{some:{teamId:d.teamId}}}}:{})}});const ids=new Set(allocations.map(a=>a.id));for(const move of d.moves)if(!ids.has(move.allocationId))throw new BadRequestException('Scenario contains an allocation outside the selected tenant or horizon');return previewScenario(allocations.map(a=>({id:a.id,resourceId:a.resourceId,title:a.title,startsAt:a.startsAt,endsAt:a.endsAt,allocationPercent:Number(a.allocationPercent),hoursPerWeek:a.hoursPerWeek?Number(a.hoursPerWeek):null})),d.moves);}

 async allocationConflicts(org:string,q:CapacityQueryDto){const plan=await this.capacityPlan(org,q);return plan.resources.flatMap((r:any)=>r.periods.filter((p:any)=>p.state==='OVERALLOCATED').map((p:any)=>({resourceId:r.id,resourceName:r.displayName,start:p.start,end:p.end,capacityHours:p.capacityHours,allocatedHours:p.allocatedHours,overByHours:Math.round((p.allocatedHours-p.capacityHours)*100)/100,utilizationPercent:p.utilizationPercent}))).sort((a:any,b:any)=>b.overByHours-a.overByHours)}
 listHolidayCalendars(org:string){return this.prisma.holidayCalendar.findMany({where:{organizationId:org},orderBy:{name:'asc'}})}
 async createHolidayCalendar(org:string,user:string,d:CreateHolidayCalendarDto){const c=await this.prisma.holidayCalendar.create({data:{organizationId:org,name:d.name,countryCode:d.countryCode,holidays:d.holidays||[]}});await this.event(org,user,'resource.holiday_calendar_created','HolidayCalendar',c.id,{name:c.name});return c}
 async updateCalendar(org:string,user:string,id:string,d:UpdateWorkingCalendarDto){const c=await this.prisma.workingCalendar.findFirst({where:{id,organizationId:org}});if(!c)throw new NotFoundException('Calendar not found');if(d.holidayCalendarId&&!await this.prisma.holidayCalendar.findFirst({where:{id:d.holidayCalendarId,organizationId:org}}))throw new BadRequestException('Holiday calendar is outside the tenant');if(d.isDefault)await this.prisma.workingCalendar.updateMany({where:{organizationId:org,isDefault:true,id:{not:id}},data:{isDefault:false}});const out=await this.prisma.workingCalendar.update({where:{id},data:d});await this.event(org,user,'resource.calendar_updated','WorkingCalendar',id,d);return out}
 async addAvailabilityException(org:string,user:string,resourceId:string,d:CreateAvailabilityExceptionDto){if(new Date(d.endsAt)<new Date(d.startsAt))throw new BadRequestException('Availability range is invalid');if(!await this.prisma.resource.findFirst({where:{id:resourceId,organizationId:org}}))throw new NotFoundException('Resource not found');const x=await this.prisma.availabilityException.create({data:{organizationId:org,resourceId,startsAt:new Date(d.startsAt),endsAt:new Date(d.endsAt),availableHours:d.availableHours,reason:d.reason}});await this.event(org,user,'resource.availability_changed','Resource',resourceId,{exceptionId:x.id});return x}

 async workforceAnalytics(org:string,q:WorkforceAnalyticsQueryDto){
  const now=new Date(),from=q.from?new Date(q.from):now,to=q.to?new Date(q.to):new Date(now.getTime()+84*86400000);if(to<from)throw new BadRequestException('Analytics range is invalid');
  const where:any={organizationId:org,status:{in:['ACTIVE','CONTRACTOR','ON_LEAVE']}};if(q.teamId)where.teamMemberships={some:{teamId:q.teamId}};
  const resources=await this.prisma.resource.findMany({where,include:{skills:{include:{skill:true}},teamMemberships:{include:{team:true}},allocations:{where:{status:{in:['PLANNED','ACTIVE']},startsAt:{lte:to},endsAt:{gte:from}}}}});
  const weeks=Math.max(1,(to.getTime()-from.getTime()+86400000)/(7*86400000));
  const inputs=resources.map(r=>{const capacity=Number(r.capacityHoursPerWeek)*weeks;const allocated=r.allocations.reduce((sum,a)=>{const start=new Date(Math.max(a.startsAt.getTime(),from.getTime())),end=new Date(Math.min(a.endsAt.getTime(),to.getTime()));const overlapWeeks=Math.max(0,(end.getTime()-start.getTime()+86400000)/(7*86400000));return sum+(a.hoursPerWeek?Number(a.hoursPerWeek)*overlapWeeks:Number(r.capacityHoursPerWeek)*Number(a.allocationPercent)/100*overlapWeeks)},0);return{id:r.id,displayName:r.displayName,jobTitle:r.jobTitle,capacityHours:Math.round(capacity*100)/100,allocatedHours:Math.round(allocated*100)/100,costRate:r.costRate?Number(r.costRate):null,currency:r.currency,teams:r.teamMemberships.map(m=>m.team.name),skills:r.skills.map(x=>({id:x.skill.id,name:x.skill.name,category:x.skill.category,proficiency:x.proficiency,verified:x.verified}))}});
  const rows=resourceAnalytics(inputs),teams=teamRollups(rows),skills=skillDistribution(rows),signals=hiringSignals(skills,rows),summary=buildExecutiveSummary(rows,teams,skills);
  return{from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10),currency:q.currency||resources[0]?.currency||'SAR',summary,resources:rows.sort((a,b)=>b.utilizationPercent-a.utilizationPercent),teams,skills,hiringSignals:signals,bottlenecks:rows.filter(r=>r.workloadState==='OVERALLOCATED').sort((a,b)=>b.utilizationPercent-a.utilizationPercent),bench:rows.filter(r=>r.workloadState==='BENCH').sort((a,b)=>a.utilizationPercent-b.utilizationPercent)};
 }
 async workforceExecutiveReport(org:string,q:WorkforceAnalyticsQueryDto){const a=await this.workforceAnalytics(org,q);return{generatedAt:new Date().toISOString(),headline:a.summary.headline,summary:a.summary,decisions:[...a.bottlenecks.slice(0,5).map((r:any)=>`Rebalance ${r.displayName}, currently at ${Math.round(r.utilizationPercent)}% utilization`),...a.hiringSignals.filter((s:any)=>s.urgency!=='LOW').slice(0,5).map((s:any)=>`Address ${s.skillName} capability gap (${s.urgency.toLowerCase()} urgency)`)],teamWorkload:a.teams,criticalSkills:a.hiringSignals.slice(0,10),benchOpportunities:a.bench.slice(0,10),cost:{forecast:a.summary.forecastCost,currency:a.currency,note:'Forecast uses recorded hourly cost rates and overlapping allocation demand.'}}}

}
