export type WorkforceResourceInput = {
  id:string; displayName:string; jobTitle?:string|null; capacityHours:number; allocatedHours:number;
  costRate?:number|null; currency?:string|null; teams:string[];
  skills:{id:string;name:string;category?:string|null;proficiency:string;verified:boolean}[];
};
const round=(n:number)=>Math.round(n*100)/100;
export function utilization(capacity:number,allocated:number){return capacity>0?round(allocated/capacity*100):0}
export function classifyWorkload(value:number){return value>100?'OVERALLOCATED':value<25?'BENCH':value<60?'UNDERUTILIZED':'BALANCED'}
export function resourceAnalytics(resources:WorkforceResourceInput[]){return resources.map(r=>{const u=utilization(r.capacityHours,r.allocatedHours);return {...r,utilizationPercent:u,remainingHours:round(r.capacityHours-r.allocatedHours),workloadState:classifyWorkload(u),forecastCost:round(r.allocatedHours*(r.costRate||0))}})}
export function teamRollups(rows:ReturnType<typeof resourceAnalytics>){const map=new Map<string,any>();for(const r of rows){for(const team of r.teams.length?r.teams:['Unassigned']){const x=map.get(team)||{name:team,resources:0,capacityHours:0,allocatedHours:0,forecastCost:0,overallocated:0,bench:0};x.resources++;x.capacityHours+=r.capacityHours;x.allocatedHours+=r.allocatedHours;x.forecastCost+=r.forecastCost;if(r.workloadState==='OVERALLOCATED')x.overallocated++;if(r.workloadState==='BENCH')x.bench++;map.set(team,x)}}return [...map.values()].map(x=>({...x,capacityHours:round(x.capacityHours),allocatedHours:round(x.allocatedHours),forecastCost:round(x.forecastCost),utilizationPercent:utilization(x.capacityHours,x.allocatedHours)})).sort((a,b)=>b.utilizationPercent-a.utilizationPercent)}
export function skillDistribution(rows:ReturnType<typeof resourceAnalytics>){const map=new Map<string,any>();for(const r of rows)for(const s of r.skills){const x=map.get(s.id)||{id:s.id,name:s.name,category:s.category,resources:0,advancedResources:0,verifiedResources:0,availableResources:0};x.resources++;if(['ADVANCED','EXPERT'].includes(s.proficiency))x.advancedResources++;if(s.verified)x.verifiedResources++;if(r.utilizationPercent<80)x.availableResources++;map.set(s.id,x)}return [...map.values()].sort((a,b)=>a.resources-b.resources||a.name.localeCompare(b.name))}
export function hiringSignals(skills:ReturnType<typeof skillDistribution>,rows:ReturnType<typeof resourceAnalytics>){const orgUtil=utilization(rows.reduce((s,r)=>s+r.capacityHours,0),rows.reduce((s,r)=>s+r.allocatedHours,0));return skills.filter(s=>s.advancedResources<=1).map(s=>({skillId:s.id,skillName:s.name,qualifiedResources:s.advancedResources,availableQualifiedResources:s.availableResources,urgency:s.advancedResources===0&&orgUtil>=85?'HIGH':s.advancedResources<=1&&orgUtil>=70?'MEDIUM':'LOW',reason:s.advancedResources===0?'No advanced or expert coverage':'Single-point-of-failure capability'})).sort((a,b)=>({HIGH:3,MEDIUM:2,LOW:1}[b.urgency as 'HIGH']-({HIGH:3,MEDIUM:2,LOW:1}[a.urgency as 'HIGH'])))}
export function buildExecutiveSummary(rows:ReturnType<typeof resourceAnalytics>,teams:ReturnType<typeof teamRollups>,skills:ReturnType<typeof skillDistribution>){const capacity=rows.reduce((s,r)=>s+r.capacityHours,0),allocated=rows.reduce((s,r)=>s+r.allocatedHours,0),overallocated=rows.filter(r=>r.workloadState==='OVERALLOCATED'),bench=rows.filter(r=>r.workloadState==='BENCH');return{headline:overallocated.length?`${overallocated.length} resources require workload intervention`:'Workforce capacity is broadly balanced',capacityHours:round(capacity),allocatedHours:round(allocated),utilizationPercent:utilization(capacity,allocated),forecastCost:round(rows.reduce((s,r)=>s+r.forecastCost,0)),overallocatedResources:overallocated.length,benchResources:bench.length,teamsAtRisk:teams.filter(t=>t.utilizationPercent>100).length,skillsAtRisk:skills.filter(s=>s.advancedResources<=1).length}}
