import { Body, Controller, Get, Param, Post } from '@nestjs/common'; import { ApiBearerAuth, ApiTags } from '@nestjs/swagger'; import { CurrentUser } from '../auth/decorators/current-user.decorator'; import { Permissions } from '../auth/decorators/permissions.decorator'; import { AuthenticatedUser } from '../auth/auth.types'; import { CreateListingDto, CreatePublisherDto, IncidentDto, InstallListingDto, ResolveIncidentDto, ReviewDto, ReviewListingDto, SubmitListingDto } from './dto'; import { IntegrationMarketplaceService } from './integration-marketplace.service';
@ApiTags('Integration Marketplace') @ApiBearerAuth() @Controller('v1/integration-marketplace') export class IntegrationMarketplaceController{constructor(private readonly s:IntegrationMarketplaceService){}
@Get('publishers') @Permissions('marketplace.publisher.read') publishers(@CurrentUser()u:AuthenticatedUser){return this.s.publishers(u.organizationId)}
@Post('publishers') @Permissions('marketplace.publisher.manage') createPublisher(@CurrentUser()u:AuthenticatedUser,@Body()d:CreatePublisherDto){return this.s.createPublisher(u.organizationId,u.sub,d)}
@Get('listings') @Permissions('marketplace.listing.read') listings(@CurrentUser()u:AuthenticatedUser){return this.s.listings(u.organizationId)}
@Post('listings') @Permissions('marketplace.listing.manage') create(@CurrentUser()u:AuthenticatedUser,@Body()d:CreateListingDto){return this.s.createListing(u.organizationId,u.sub,d)}
@Post('listings/:id/submit') @Permissions('marketplace.listing.manage') submit(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:SubmitListingDto){return this.s.submit(u.organizationId,u.sub,id,d)}
@Post('reviews/:id/decision') @Permissions('marketplace.review') review(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:ReviewListingDto){return this.s.review(u.organizationId,u.sub,id,d)}
@Post('listings/:id/install') @Permissions('marketplace.install') install(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:InstallListingDto){return this.s.install(u.organizationId,u.sub,id,d)}
@Get('installations') @Permissions('marketplace.installation.read') installations(@CurrentUser()u:AuthenticatedUser){return this.s.installations(u.organizationId)}
@Post('installations/:id/uninstall') @Permissions('marketplace.install') uninstall(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string){return this.s.uninstall(u.organizationId,u.sub,id)}
@Post('listings/:id/ratings') @Permissions('marketplace.rating.create') rating(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:ReviewDto){return this.s.addReview(u.organizationId,u.sub,id,d)}
@Post('listings/:id/certify') @Permissions('marketplace.certify') certify(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string){return this.s.certify(u.organizationId,u.sub,id)}
@Get('incidents') @Permissions('marketplace.operations.read') incidents(@CurrentUser()u:AuthenticatedUser){return this.s.incidents(u.organizationId)}
@Post('installations/:id/incidents') @Permissions('marketplace.operations.manage') incident(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:IncidentDto){return this.s.createIncident(u.organizationId,u.sub,id,d)}
@Post('incidents/:id/resolve') @Permissions('marketplace.operations.manage') resolve(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:ResolveIncidentDto){return this.s.resolveIncident(u.organizationId,u.sub,id,d.resolution)}
@Get('analytics') @Permissions('marketplace.analytics.read') analytics(@CurrentUser()u:AuthenticatedUser){return this.s.analytics(u.organizationId)}}
