import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateListingDto, CreatePublisherDto, IncidentDto, InstallListingDto, ReviewDto, ReviewListingDto, SubmitListingDto } from './dto';
@Injectable()
export class IntegrationMarketplaceService {
 constructor(private readonly prisma:PrismaService){}
 private db(){ return this.prisma as any; }
 async publishers(org:string){ return this.db().integrationPublisher.findMany({where:{organizationId:org},orderBy:{createdAt:'desc'}}); }
 async createPublisher(org:string,user:string,d:CreatePublisherDto){ return this.db().integrationPublisher.create({data:{organizationId:org,ownerUserId:user,...d,status:'PENDING'}}); }
 async listings(org:string){ return this.db().integrationMarketplaceListing.findMany({where:{OR:[{organizationId:org},{visibility:'PUBLIC',status:'PUBLISHED'}]},include:{publisher:true,certifications:true},orderBy:{updatedAt:'desc'}}); }
 async createListing(org:string,user:string,d:CreateListingDto){ const p=await this.db().integrationPublisher.findFirst({where:{id:d.publisherId,organizationId:org}}); if(!p) throw new NotFoundException('Publisher not found'); return this.db().integrationMarketplaceListing.create({data:{organizationId:org,createdByUserId:user,status:'DRAFT',version:'1.0.0',...d}}); }
 async submit(org:string,user:string,id:string,d:SubmitListingDto){ const l=await this.ownedListing(org,id); if(l.status!=='DRAFT'&&l.status!=='CHANGES_REQUESTED') throw new BadRequestException('Only draft or changes-requested listings may be submitted'); return this.db().$transaction(async(tx:any)=>{await tx.integrationMarketplaceReview.create({data:{organizationId:org,listingId:id,requestedByUserId:user,status:'PENDING',submissionNotes:d.notes}});return tx.integrationMarketplaceListing.update({where:{id},data:{status:'IN_REVIEW',submittedAt:new Date()}});}); }
 async review(org:string,user:string,id:string,d:ReviewListingDto){ const r=await this.db().integrationMarketplaceReview.findFirst({where:{id,organizationId:org,status:'PENDING'},include:{listing:true}}); if(!r) throw new NotFoundException('Review not found'); if(r.requestedByUserId===user) throw new ForbiddenException('Submitters cannot approve their own listings'); const approved=d.decision.toUpperCase()==='APPROVE'; return this.db().$transaction(async(tx:any)=>{await tx.integrationMarketplaceReview.update({where:{id},data:{status:approved?'APPROVED':'CHANGES_REQUESTED',reviewedByUserId:user,reviewNotes:d.notes,findings:d.findings||[],reviewedAt:new Date()}});return tx.integrationMarketplaceListing.update({where:{id:r.listingId},data:{status:approved?'PUBLISHED':'CHANGES_REQUESTED',publishedAt:approved?new Date():null}});}); }
 async install(org:string,user:string,id:string,d:InstallListingDto){ const l=await this.db().integrationMarketplaceListing.findFirst({where:{id,status:'PUBLISHED',OR:[{organizationId:org},{visibility:'PUBLIC'}]}}); if(!l) throw new NotFoundException('Published listing not found'); return this.db().integrationInstallation.upsert({where:{organizationId_listingId:{organizationId:org,listingId:id}},update:{status:'ACTIVE',configuration:d.configuration||{},autoUpdate:d.autoUpdate??true,updatedByUserId:user},create:{organizationId:org,listingId:id,installedByUserId:user,updatedByUserId:user,status:'ACTIVE',installedVersion:l.version,configuration:d.configuration||{},autoUpdate:d.autoUpdate??true}}); }
 async installations(org:string){return this.db().integrationInstallation.findMany({where:{organizationId:org},include:{listing:true},orderBy:{updatedAt:'desc'}})}
 async uninstall(org:string,user:string,id:string){const i=await this.db().integrationInstallation.findFirst({where:{id,organizationId:org}});if(!i)throw new NotFoundException('Installation not found');return this.db().integrationInstallation.update({where:{id},data:{status:'UNINSTALLED',uninstalledAt:new Date(),updatedByUserId:user}})}
 async addReview(org:string,user:string,id:string,d:ReviewDto){const install=await this.db().integrationInstallation.findFirst({where:{organizationId:org,listingId:id,status:'ACTIVE'}});if(!install)throw new ForbiddenException('Install the listing before reviewing it');const n=Number(d.rating);if(!Number.isInteger(n)||n<1||n>5)throw new BadRequestException('Rating must be 1-5');return this.db().integrationMarketplaceRating.upsert({where:{organizationId_listingId_userId:{organizationId:org,listingId:id,userId:user}},update:{title:d.title,body:d.body,rating:n},create:{organizationId:org,listingId:id,userId:user,title:d.title,body:d.body,rating:n}})}
 async certify(org:string,user:string,id:string){const l=await this.ownedListing(org,id);if(l.status!=='PUBLISHED')throw new BadRequestException('Only published listings can be certified');return this.db().integrationCertification.create({data:{organizationId:org,listingId:id,certifiedByUserId:user,type:'SECURITY_REVIEW',status:'ACTIVE',validFrom:new Date()}})}
 async incidents(org:string){return this.db().integrationMarketplaceIncident.findMany({where:{organizationId:org},include:{listing:true,installation:true},orderBy:{createdAt:'desc'}})}
 async createIncident(org:string,user:string,id:string,d:IncidentDto){const i=await this.db().integrationInstallation.findFirst({where:{id,organizationId:org}});if(!i)throw new NotFoundException('Installation not found');return this.db().integrationMarketplaceIncident.create({data:{organizationId:org,installationId:id,listingId:i.listingId,reportedByUserId:user,title:d.title,severity:d.severity,status:'OPEN',description:d.description}})}
 async resolveIncident(org:string,user:string,id:string,resolution:string){const i=await this.db().integrationMarketplaceIncident.findFirst({where:{id,organizationId:org,status:{not:'RESOLVED'}}});if(!i)throw new NotFoundException('Open incident not found');return this.db().integrationMarketplaceIncident.update({where:{id},data:{status:'RESOLVED',resolution,resolvedByUserId:user,resolvedAt:new Date()}})}
 async analytics(org:string){const [listings,installs,incidents]=await Promise.all([this.db().integrationMarketplaceListing.count({where:{organizationId:org}}),this.db().integrationInstallation.count({where:{organizationId:org,status:'ACTIVE'}}),this.db().integrationMarketplaceIncident.count({where:{organizationId:org,status:{not:'RESOLVED'}}})]);return{listings,activeInstallations:installs,openIncidents:incidents};}
 private async ownedListing(org:string,id:string){const l=await this.db().integrationMarketplaceListing.findFirst({where:{id,organizationId:org}});if(!l)throw new NotFoundException('Listing not found');return l;}
}
