'use client';
import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AdminShell } from '../../components/admin-shell';
import { api } from '../../lib/api';

type User={id:string;firstName:string;lastName:string};
type Overview={portfolios:number;programs:number;projects:number;activeProjects:number;atRiskProjects:number;averageProgress:number;openRisks:number;openIssues:number;budget:number;actualCost:number;overdueProjects:number};
type Portfolio={id:string;name:string;status:string;health:string;owner:User;_count:{programs:number;projects:number};projects:{progress:string;health:string}[]};
type Program={id:string;name:string;status:string;health:string;owner:User;portfolio?:{name:string};_count:{projects:number};projects:{progress:string;health:string}[]};
type Project={id:string;key:string;name:string;status:string;health:string;progress:string;budget?:string;actualCost:string;targetDate?:string;owner:User;portfolio?:{name:string};program?:{name:string};variance:{budgetVariance:number;budgetVariancePercent:number;scheduleVariancePoints:number;daysRemaining:number|null}};
const money=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n||0);
const label=(v:string)=>v?.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function ExecutionPage(){
 const [overview,setOverview]=useState<Overview|null>(null),[projects,setProjects]=useState<Project[]>([]),[portfolios,setPortfolios]=useState<Portfolio[]>([]),[programs,setPrograms]=useState<Program[]>([]),[users,setUsers]=useState<User[]>([]),[tab,setTab]=useState<'projects'|'portfolios'|'programs'>('projects'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [portfolioForm,setPortfolioForm]=useState({name:'',ownerId:'',budget:''}),[programForm,setProgramForm]=useState({name:'',ownerId:'',portfolioId:'',budget:''});
 async function load(){try{setError('');const [o,p,pf,pg,u]=await Promise.all([api<Overview>('/execution/overview'),api<Project[]>('/execution/projects'),api<Portfolio[]>('/execution/portfolios'),api<Program[]>('/execution/programs'),api<User[]>('/users')]);setOverview(o);setProjects(p);setPortfolios(pf);setPrograms(pg);setUsers(u);setPortfolioForm(x=>({...x,ownerId:x.ownerId||u[0]?.id||''}));setProgramForm(x=>({...x,ownerId:x.ownerId||u[0]?.id||''}));}catch(e){setError(e instanceof Error?e.message:'Unable to load execution data')}}
 useEffect(()=>{load()},[]);
 async function createPortfolio(e:FormEvent){e.preventDefault();setBusy(true);try{await api('/execution/portfolios',{method:'POST',body:JSON.stringify({...portfolioForm,budget:portfolioForm.budget?Number(portfolioForm.budget):undefined})});setPortfolioForm({name:'',ownerId:users[0]?.id||'',budget:''});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create portfolio')}finally{setBusy(false)}}
 async function createProgram(e:FormEvent){e.preventDefault();setBusy(true);try{await api('/execution/programs',{method:'POST',body:JSON.stringify({...programForm,portfolioId:programForm.portfolioId||undefined,budget:programForm.budget?Number(programForm.budget):undefined})});setProgramForm({name:'',ownerId:users[0]?.id||'',portfolioId:'',budget:''});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create program')}finally{setBusy(false)}}
 const portfolioProgress=(p:Portfolio)=>p.projects.length?Math.round(p.projects.reduce((s,x)=>s+Number(x.progress),0)/p.projects.length):0;
 const programProgress=(p:Program)=>p.projects.length?Math.round(p.projects.reduce((s,x)=>s+Number(x.progress),0)/p.projects.length):0;
 const highRisk=useMemo(()=>projects.filter(p=>['AT_RISK','OFF_TRACK'].includes(p.health)),[projects]);
 return <AdminShell title="Projects & initiatives" subtitle="Manage strategic portfolios, programs, and project delivery with live health and variance signals." action={<Link className="buttonLink" href="/execution/projects/new">New project</Link>}>
  {error&&<div className="formError">{error}</div>}
  <section className="metrics executionMetrics"><article><p>Active projects</p><strong>{overview?.activeProjects??'—'}</strong><span>{overview?.projects??0} total projects</span></article><article><p>At risk / off track</p><strong>{overview?.atRiskProjects??'—'}</strong><span>{overview?.overdueProjects??0} overdue</span></article><article><p>Open delivery exposure</p><strong>{(overview?.openRisks??0)+(overview?.openIssues??0)}</strong><span>{overview?.openRisks??0} risks · {overview?.openIssues??0} issues</span></article><article><p>Portfolio progress</p><strong>{Math.round(overview?.averageProgress??0)}%</strong><span>Cost {money(overview?.actualCost??0)} / {money(overview?.budget??0)}</span></article></section>
  <div className="enterpriseTabs"><button className={tab==='projects'?'active secondary':'secondary'} onClick={()=>setTab('projects')}>Projects</button><button className={tab==='portfolios'?'active secondary':'secondary'} onClick={()=>setTab('portfolios')}>Portfolios</button><button className={tab==='programs'?'active secondary':'secondary'} onClick={()=>setTab('programs')}>Programs</button></div>
  {tab==='projects'&&<section className="panel tablePanel"><div className="panelHead"><div><h2>Project portfolio</h2><p>Calculated health, schedule variance, budget performance, and ownership.</p></div></div><div className="executionTable"><div className="executionRow executionHead"><span>Project</span><span>Owner</span><span>Status</span><span>Health</span><span>Progress</span><span>Variance</span></div>{projects.map(p=><Link href={`/execution/projects/${p.id}`} className="executionRow" key={p.id}><span><strong>{p.key} · {p.name}</strong><small>{p.program?.name||p.portfolio?.name||'Unassigned'}</small></span><span>{p.owner.firstName} {p.owner.lastName}</span><span><i className="status">{label(p.status)}</i></span><span><i className={`status health-${p.health.toLowerCase()}`}>{label(p.health)}</i></span><span><progress max="100" value={Number(p.progress)}/><small>{Math.round(Number(p.progress))}%</small></span><span><b className={p.variance.scheduleVariancePoints<-10?'negative':''}>{Math.round(p.variance.scheduleVariancePoints)} pts</b><small>{p.variance.budgetVariancePercent>0?'+':''}{Math.round(p.variance.budgetVariancePercent)}% cost</small></span></Link>)}{!projects.length&&<div className="emptyState"><h2>No projects yet</h2><p>Create the first project to start connecting strategy and delivery.</p></div>}</div></section>}
  {tab==='portfolios'&&<><section className="panel"><div className="panelHead"><div><h2>Create portfolio</h2><p>Group programs and projects under a strategic investment area.</p></div></div><form className="executionInlineForm" onSubmit={createPortfolio}><input required placeholder="Portfolio name" value={portfolioForm.name} onChange={e=>setPortfolioForm({...portfolioForm,name:e.target.value})}/><select required value={portfolioForm.ownerId} onChange={e=>setPortfolioForm({...portfolioForm,ownerId:e.target.value})}>{users.map(u=><option value={u.id} key={u.id}>{u.firstName} {u.lastName}</option>)}</select><input type="number" min="0" placeholder="Budget" value={portfolioForm.budget} onChange={e=>setPortfolioForm({...portfolioForm,budget:e.target.value})}/><button disabled={busy}>Create</button></form></section><section className="cardGrid executionCards">{portfolios.map(p=><article className="panel entityCard" key={p.id}><div className="entityIcon">PF</div><h2>{p.name}</h2><p>{p._count.programs} programs · {p._count.projects} direct projects</p><div className="bar"><i style={{width:`${portfolioProgress(p)}%`}}/></div><div><span>{p.owner.firstName} {p.owner.lastName}</span><strong>{portfolioProgress(p)}%</strong></div></article>)}</section></>}
  {tab==='programs'&&<><section className="panel"><div className="panelHead"><div><h2>Create program</h2><p>Coordinate related projects and their shared outcomes.</p></div></div><form className="executionInlineForm" onSubmit={createProgram}><input required placeholder="Program name" value={programForm.name} onChange={e=>setProgramForm({...programForm,name:e.target.value})}/><select required value={programForm.ownerId} onChange={e=>setProgramForm({...programForm,ownerId:e.target.value})}>{users.map(u=><option value={u.id} key={u.id}>{u.firstName} {u.lastName}</option>)}</select><select value={programForm.portfolioId} onChange={e=>setProgramForm({...programForm,portfolioId:e.target.value})}><option value="">No portfolio</option>{portfolios.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input type="number" min="0" placeholder="Budget" value={programForm.budget} onChange={e=>setProgramForm({...programForm,budget:e.target.value})}/><button disabled={busy}>Create</button></form></section><section className="cardGrid executionCards">{programs.map(p=><article className="panel entityCard" key={p.id}><div className="entityIcon team">PG</div><h2>{p.name}</h2><p>{p.portfolio?.name||'Independent program'} · {p._count.projects} projects</p><div className="bar"><i style={{width:`${programProgress(p)}%`}}/></div><div><span>{p.owner.firstName} {p.owner.lastName}</span><strong>{programProgress(p)}%</strong></div></article>)}</section></>}
  {highRisk.length>0&&<section className="panel executionAlert"><h2>Projects needing attention</h2>{highRisk.slice(0,4).map(p=><Link href={`/execution/projects/${p.id}`} key={p.id}><strong>{p.key} · {p.name}</strong><span>{label(p.health)} · {Math.round(p.variance.scheduleVariancePoints)} schedule points</span></Link>)}</section>}
 </AdminShell>
}
