import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { CreatePredictionModelDto, CreatePredictionVersionDto, PredictionQueryDto, RunPredictionDto } from './dto/predictive.dto';
import { PredictionEngineService } from './prediction-engine.service';
@Injectable()
export class PredictiveAnalyticsService {
 constructor(private prisma:PrismaService,private engine:PredictionEngineService){}
 listModels(org:string){return this.prisma.predictionModel.findMany({where:{organizationId:org},include:{versions:{orderBy:{version:'desc'},take:1}},orderBy:{name:'asc'}})}
 createModel(org:string,user:string,d:CreatePredictionModelDto){return this.prisma.predictionModel.create({data:{organizationId:org,createdById:user,...d}})}
 async addVersion(org:string,user:string,id:string,d:CreatePredictionVersionDto){const model=await this.prisma.predictionModel.findFirst({where:{id,organizationId:org}});if(!model)throw new NotFoundException('Prediction model not found');const last=await this.prisma.predictionModelVersion.aggregate({where:{modelId:id},_max:{version:true}});return this.prisma.predictionModelVersion.create({data:{modelId:id,createdById:user,version:(last._max.version||0)+1,modelType:d.modelType as any,configuration:(d.configuration||{}) as any,featureKeys:d.featureKeys,horizonPeriods:d.horizonPeriods??1,minimumSamples:d.minimumSamples??3}})}
 async publish(org:string,id:string,versionId:string){const v=await this.prisma.predictionModelVersion.findFirst({where:{id:versionId,model:{id,organizationId:org}}});if(!v)throw new NotFoundException('Prediction model version not found');if(v.publishedAt)throw new BadRequestException('Version already published');return this.prisma.$transaction([this.prisma.predictionModelVersion.update({where:{id:v.id},data:{publishedAt:new Date()}}),this.prisma.predictionModel.update({where:{id},data:{status:'PUBLISHED',activeVersionId:v.id}})])}
 async run(org:string,user:string,id:string,d:RunPredictionDto){const model=await this.prisma.predictionModel.findFirst({where:{id,organizationId:org},include:{versions:{where:{publishedAt:{not:null}},orderBy:{version:'desc'},take:1}}});if(!model||!model.versions[0])throw new NotFoundException('Published prediction model not found');const v=model.versions[0];if(d.series.length<v.minimumSamples && v.modelType!=='RISK_SCORE')throw new BadRequestException(`At least ${v.minimumSamples} observations are required`);const run=await this.prisma.predictionRun.create({data:{organizationId:org,modelId:id,versionId:v.id,status:'RUNNING',input:d as any,dryRun:d.dryRun??false,initiatedById:user}});try{const output=this.engine.predict(v.modelType as any,d.series,d.features||{},v.configuration as any);const result=d.dryRun?null:await this.prisma.predictionResult.create({data:{organizationId:org,modelId:id,versionId:v.id,runId:run.id,entityType:d.entityType,entityId:d.entityId,predictedValue:output.predictedValue,probability:output.probability,confidence:output.confidence,horizonStart:d.horizonStart?new Date(d.horizonStart):null,horizonEnd:d.horizonEnd?new Date(d.horizonEnd):null,explanation:output.explanation as any,features:(d.features||{}) as any}});await this.prisma.predictionRun.update({where:{id:run.id},data:{status:'SUCCEEDED',output:output as any,completedAt:new Date()}});return {runId:run.id,dryRun:d.dryRun??false,resultId:result?.id??null,...output};}catch(e){await this.prisma.predictionRun.update({where:{id:run.id},data:{status:'FAILED',error:e instanceof Error?e.message:'Prediction failed',completedAt:new Date()}});throw e;}}
 results(org:string,q:PredictionQueryDto){return this.prisma.predictionResult.findMany({where:{organizationId:org,...(q.modelId?{modelId:q.modelId}:{}),...(q.entityType?{entityType:q.entityType}:{}),...(q.entityId?{entityId:q.entityId}:{})},include:{model:{select:{key:true,name:true,targetType:true}},version:{select:{version:true,modelType:true}}},orderBy:{createdAt:'desc'},take:500})}
 runs(org:string,modelId?:string){return this.prisma.predictionRun.findMany({where:{organizationId:org,...(modelId?{modelId}:{})},orderBy:{startedAt:'desc'},take:200})}
}
