import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AcknowledgeAnnouncementDto, CreateCommunicationCampaignDto, CreateEnterpriseAnnouncementDto, UpdateEnterpriseAnnouncementDto, UpdateWorkplacePreferenceDto } from './dto';
@Injectable()
export class DigitalWorkplaceService {
 constructor(private readonly prisma:PrismaService){}
 private db(){return this.prisma as any;}
 private audience(user:any){return {OR:[{audienceUserIds:{isEmpty:true}},{audienceUserIds:{has:user.sub}},...(user.departmentId?[{audienceDepartmentIds:{has:user.departmentId}}]:[])]};}
 async home(org:string,user:any){const now=new Date();const [announcements,activity,documents,workspaces,communities,preferences]=await Promise.all([
  this.db().enterpriseAnnouncement.findMany({where:{organizationId:org,status:'PUBLISHED',AND:[this.audience(user),{OR:[{publishAt:null},{publishAt:{lte:now}}]},{OR:[{expiresAt:null},{expiresAt:{gt:now}}]}]},include:{acknowledgements:{where:{userId:user.sub}}},orderBy:[{severity:'desc'},{publishedAt:'desc'}],take:12}),
  this.db().activityEvent.findMany({where:{organizationId:org,OR:[{audienceUserIds:{isEmpty:true}},{audienceUserIds:{has:user.sub}}]},orderBy:{createdAt:'desc'},take:20}),
  this.db().enterpriseDocument.findMany({where:{organizationId:org,status:'PUBLISHED',OR:[{visibility:'ORGANIZATION'},{allowedUserIds:{has:user.sub}},{ownerUserId:user.sub}]},orderBy:{publishedAt:'desc'},take:8}),
  this.db().teamWorkspace.findMany({where:{organizationId:org,status:'ACTIVE',OR:[{visibility:{in:['PUBLIC','INTERNAL']}},{members:{some:{userId:user.sub,leftAt:null}}}]},include:{_count:{select:{members:true,communities:true}}},orderBy:{updatedAt:'desc'},take:8}),
  this.db().community.findMany({where:{organizationId:org,status:'ACTIVE',OR:[{membershipPolicy:'OPEN'},{members:{some:{userId:user.sub,leftAt:null}}}]},include:{_count:{select:{members:true}}},orderBy:{updatedAt:'desc'},take:8}),
  this.db().digitalWorkplacePreference.findUnique({where:{organizationId_userId:{organizationId:org,userId:user.sub}}})
 ]);return {announcements,activity,documents,workspaces,communities,preferences:preferences??{showAnnouncements:true,showActivity:true,showDocuments:true,showWorkspaces:true,feedPageSize:20}};}
 async directory(org:string,q?:string){return this.db().user.findMany({where:{organizationId:org,status:'ACTIVE',...(q?{OR:[{firstName:{contains:q,mode:'insensitive'}},{lastName:{contains:q,mode:'insensitive'}},{email:{contains:q,mode:'insensitive'}}]}:{})},select:{id:true,firstName:true,lastName:true,email:true,jobTitle:true,departmentId:true},orderBy:[{firstName:'asc'},{lastName:'asc'}],take:50});}
 async listAnnouncements(org:string,user:any){return this.db().enterpriseAnnouncement.findMany({where:{organizationId:org,...this.audience(user)},include:{acknowledgements:{where:{userId:user.sub}}},orderBy:{createdAt:'desc'}});}
 async createAnnouncement(org:string,userId:string,d:CreateEnterpriseAnnouncementDto){const status=d.publishAt&&new Date(d.publishAt)>new Date()?'SCHEDULED':'DRAFT';return this.db().enterpriseAnnouncement.create({data:{organizationId:org,title:d.title,content:d.content,severity:d.severity??'INFORMATION',status,audienceUserIds:d.audienceUserIds??[],audienceDepartmentIds:d.audienceDepartmentIds??[],publishAt:d.publishAt?new Date(d.publishAt):null,expiresAt:d.expiresAt?new Date(d.expiresAt):null,requiresAcknowledgement:d.requiresAcknowledgement??false,createdByUserId:userId}});}
 async updateAnnouncement(org:string,id:string,d:UpdateEnterpriseAnnouncementDto){const row=await this.db().enterpriseAnnouncement.findFirst({where:{id,organizationId:org}});if(!row)throw new NotFoundException('Announcement not found');const data:any={...d};if(d.publishAt)data.publishAt=new Date(d.publishAt);if(d.expiresAt)data.expiresAt=new Date(d.expiresAt);if(d.status==='PUBLISHED')data.publishedAt=new Date();return this.db().enterpriseAnnouncement.update({where:{id},data});}
 async acknowledge(org:string,userId:string,id:string,d:AcknowledgeAnnouncementDto){const row=await this.db().enterpriseAnnouncement.findFirst({where:{id,organizationId:org,status:'PUBLISHED'}});if(!row)throw new NotFoundException('Published announcement not found');return this.db().announcementAcknowledgement.upsert({where:{announcementId_userId:{announcementId:id,userId}},update:{note:d.note,acknowledgedAt:new Date()},create:{organizationId:org,announcementId:id,userId,note:d.note}});}
 async createCampaign(org:string,userId:string,d:CreateCommunicationCampaignDto){const channels=[...new Set(d.channels??['IN_APP'])];if(!channels.every(c=>['IN_APP','EMAIL','PUSH'].includes(c)))throw new BadRequestException('Unsupported communication channel');return this.db().communicationCampaign.create({data:{organizationId:org,name:d.name,subject:d.subject,content:d.content,channels,audienceUserIds:d.audienceUserIds??[],audienceDepartmentIds:d.audienceDepartmentIds??[],scheduledAt:d.scheduledAt?new Date(d.scheduledAt):null,status:d.scheduledAt?'SCHEDULED':'DRAFT',createdByUserId:userId}});}
 async campaigns(org:string){return this.db().communicationCampaign.findMany({where:{organizationId:org},orderBy:{createdAt:'desc'}});}
 async publishCampaign(org:string,id:string,userId:string){const row=await this.db().communicationCampaign.findFirst({where:{id,organizationId:org}});if(!row)throw new NotFoundException('Campaign not found');if(row.status==='SENT')throw new BadRequestException('Campaign already sent');await this.db().activityEvent.create({data:{organizationId:org,actorUserId:userId,type:'COMMUNICATION_CAMPAIGN_SENT',entityType:'CommunicationCampaign',entityId:id,payload:{subject:row.subject,channels:row.channels},audienceUserIds:row.audienceUserIds}});return this.db().communicationCampaign.update({where:{id},data:{status:'SENT',sentAt:new Date()}});}
 async preferences(org:string,userId:string,d:UpdateWorkplacePreferenceDto){return this.db().digitalWorkplacePreference.upsert({where:{organizationId_userId:{organizationId:org,userId}},update:d,create:{organizationId:org,userId,...d}});}
 async analytics(org:string){const [published,required,acknowledged,campaigns]=await Promise.all([this.db().enterpriseAnnouncement.count({where:{organizationId:org,status:'PUBLISHED'}}),this.db().enterpriseAnnouncement.count({where:{organizationId:org,requiresAcknowledgement:true,status:'PUBLISHED'}}),this.db().announcementAcknowledgement.count({where:{organizationId:org}}),this.db().communicationCampaign.groupBy({by:['status'],where:{organizationId:org},_count:{_all:true}})]);return {publishedAnnouncements:published,acknowledgementRequired:required,acknowledgements:acknowledged,campaigns};}
}
