import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
import { AddFieldMappingDto, CreateConnectionDto, CreateSyncDefinitionDto, ResolveConflictDto, UpdateConnectionDto } from './dto';
@Injectable()
export class DataSyncPlatformService {
  constructor(private readonly prisma:PrismaService){}
  private db(){ return this.prisma as any; }
  private key(){ return createHash('sha256').update(process.env.CONNECTOR_ENCRYPTION_KEY || process.env.JWT_SECRET || 'achievex-development-only').digest(); }
  private encrypt(value:string){ const iv=randomBytes(12); const cipher=createCipheriv('aes-256-gcm',this.key(),iv); const encrypted=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]); return [iv.toString('base64'),cipher.getAuthTag().toString('base64'),encrypted.toString('base64')].join('.'); }
  async seedCatalog(){ const definitions=[['workday','Workday','HRIS',['employees','positions','organizationUnits']],['salesforce','Salesforce','CRM',['accounts','opportunities','users']],['sap','SAP S/4HANA','ERP',['costCenters','budgets','employees']],['jira','Jira','PROJECT',['projects','issues','users']],['microsoft-teams','Microsoft Teams','COLLABORATION',['teams','channels','messages']],['google-workspace','Google Workspace','PRODUCTIVITY',['users','groups','calendarEvents']]]; for(const [key,name,domain,objects] of definitions){ await this.db().dataConnectorDefinition.upsert({where:{key},update:{name,domain,supportedObjects:objects,active:true},create:{key,name,domain,capabilities:['PULL','PUSH','INCREMENTAL_SYNC','HEALTH_CHECK'],supportedObjects:objects,active:true}});} return this.db().dataConnectorDefinition.findMany({orderBy:{name:'asc'}}); }
  catalog(){ return this.db().dataConnectorDefinition.findMany({where:{active:true},orderBy:{name:'asc'}}); }
  connections(org:string){ return this.db().dataConnection.findMany({where:{organizationId:org},include:{connectorDefinition:true,_count:{select:{syncDefinitions:true,runs:true}}},orderBy:{updatedAt:'desc'}}); }
  async createConnection(org:string,user:string,d:CreateConnectionDto){ const def=await this.db().dataConnectorDefinition.findUnique({where:{id:d.connectorDefinitionId}}); if(!def) throw new NotFoundException('Connector definition not found'); return this.db().dataConnection.create({data:{organizationId:org,connectorDefinitionId:d.connectorDefinitionId,name:d.name,baseUrl:d.baseUrl,tenantKey:d.tenantKey,settings:d.settings,createdByUserId:user,encryptedCredential:d.credential?this.encrypt(d.credential):undefined,credentialFingerprint:d.credential?createHash('sha256').update(d.credential).digest('hex').slice(0,16):undefined}}); }
  async updateConnection(org:string,id:string,d:UpdateConnectionDto){ await this.requireConnection(org,id); return this.db().dataConnection.update({where:{id},data:d}); }
  async rotateCredential(org:string,id:string,credential:string){ await this.requireConnection(org,id); if(!credential) throw new BadRequestException('credential is required'); return this.db().dataConnection.update({where:{id},data:{encryptedCredential:this.encrypt(credential),credentialFingerprint:createHash('sha256').update(credential).digest('hex').slice(0,16)}}); }
  definitions(org:string){ return this.db().dataSyncDefinition.findMany({where:{organizationId:org},include:{connection:{include:{connectorDefinition:true}},mappings:true,_count:{select:{runs:true,conflicts:true}}},orderBy:{updatedAt:'desc'}}); }
  async createDefinition(org:string,d:CreateSyncDefinitionDto){ await this.requireConnection(org,d.connectionId); if(d.trigger==='SCHEDULED'&&!d.scheduleCron) throw new BadRequestException('scheduleCron is required for scheduled syncs'); return this.db().dataSyncDefinition.create({data:{organizationId:org,...d}}); }
  async addMapping(org:string,id:string,d:AddFieldMappingDto){ await this.requireDefinition(org,id); return this.db().dataFieldMapping.create({data:{syncDefinitionId:id,...d}}); }
  async startRun(org:string,user:string,id:string,trigger='MANUAL'){ const def=await this.requireDefinition(org,id); const run=await this.db().dataSyncRun.create({data:{organizationId:org,connectionId:def.connectionId,syncDefinitionId:id,status:'RUNNING',trigger,triggeredByUserId:user,startedAt:new Date(),checkpointBefore:def.checkpoint}}); return {run,executionBoundary:'Provider adapter execution must be handled by the connector worker; this API creates the durable governed run.'}; }
  runs(org:string,take=100){ return this.db().dataSyncRun.findMany({where:{organizationId:org},include:{syncDefinition:true,connection:{include:{connectorDefinition:true}}},orderBy:{createdAt:'desc'},take:Math.min(take,500)}); }
  conflicts(org:string,status?:string){ return this.db().dataSyncConflict.findMany({where:{organizationId:org,...(status?{status}: {})},include:{syncDefinition:true},orderBy:{createdAt:'desc'},take:200}); }
  async resolve(org:string,user:string,id:string,d:ResolveConflictDto){ const c=await this.db().dataSyncConflict.findFirst({where:{id,organizationId:org}}); if(!c) throw new NotFoundException('Conflict not found'); return this.db().dataSyncConflict.update({where:{id},data:{status:'RESOLVED',resolution:d.resolution,resolvedByUserId:user,resolvedAt:new Date(),notes:d.notes}}); }
  async analytics(org:string,days=30){ const since=new Date(Date.now()-Math.min(days,90)*86400000); const [connections,definitions,runs,conflicts]=await Promise.all([this.db().dataConnection.count({where:{organizationId:org}}),this.db().dataSyncDefinition.count({where:{organizationId:org,enabled:true}}),this.db().dataSyncRun.groupBy({by:['status'],where:{organizationId:org,createdAt:{gte:since}},_count:{_all:true}}),this.db().dataSyncConflict.count({where:{organizationId:org,status:'OPEN'}})]); return {connections,activeDefinitions:definitions,runsByStatus:runs,openConflicts:conflicts,windowDays:Math.min(days,90)}; }
  private async requireConnection(org:string,id:string){ const x=await this.db().dataConnection.findFirst({where:{id,organizationId:org}}); if(!x) throw new NotFoundException('Connection not found'); return x; }
  private async requireDefinition(org:string,id:string){ const x=await this.db().dataSyncDefinition.findFirst({where:{id,organizationId:org}}); if(!x) throw new NotFoundException('Sync definition not found'); return x; }
}
