'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AdminShell } from '../../../../components/admin-shell';
import { api } from '../../../../lib/api';
type User={id:string;firstName:string;lastName:string}; type Ref={id:string;name:string;portfolioId?:string};
export default function NewProjectPage(){const router=useRouter();const [users,setUsers]=useState<User[]>([]),[portfolios,setPortfolios]=useState<Ref[]>([]),[programs,setPrograms]=useState<Ref[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState({key:'',name:'',description:'',ownerId:'',sponsorId:'',portfolioId:'',programId:'',priority:'MEDIUM',status:'DRAFT',startDate:'',targetDate:'',budget:''});
 useEffect(()=>{Promise.all([api<User[]>('/users'),api<Ref[]>('/execution/portfolios'),api<Ref[]>('/execution/programs')]).then(([u,p,g])=>{setUsers(u);setPortfolios(p);setPrograms(g);setForm(x=>({...x,ownerId:u[0]?.id||''}))}).catch(e=>setError(e.message))},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const project=await api<{id:string}>('/execution/projects',{method:'POST',body:JSON.stringify({...form,sponsorId:form.sponsorId||undefined,portfolioId:form.portfolioId||undefined,programId:form.programId||undefined,startDate:form.startDate||undefined,targetDate:form.targetDate||undefined,budget:form.budget?Number(form.budget):undefined})});router.push(`/execution/projects/${project.id}`)}catch(e){setError(e instanceof Error?e.message:'Unable to create project')}finally{setBusy(false)}}
 return <AdminShell title="Create project" subtitle="Define ownership, delivery boundaries, investment, and strategic placement."><section className="panel"><form className="projectForm" onSubmit={submit}>{error&&<div className="formError">{error}</div>}<div className="formGrid"><label>Project key<input required maxLength={30} placeholder="DX-101" value={form.key} onChange={e=>setForm({...form,key:e.target.value.toUpperCase()})}/></label><label>Project name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label></div><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="formGrid"><label>Owner<select required value={form.ownerId} onChange={e=>setForm({...form,ownerId:e.target.value})}>{users.map(u=><option key={u.id} value={u.id}>{u.firstName} {u.lastName}</option>)}</select></label><label>Sponsor<select value={form.sponsorId} onChange={e=>setForm({...form,sponsorId:e.target.value})}><option value="">Not assigned</option>{users.map(u=><option key={u.id} value={u.id}>{u.firstName} {u.lastName}</option>)}</select></label></div><div className="formGrid"><label>Portfolio<select value={form.portfolioId} onChange={e=>setForm({...form,portfolioId:e.target.value,programId:''})}><option value="">No portfolio</option>{portfolios.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Program<select value={form.programId} onChange={e=>setForm({...form,programId:e.target.value})}><option value="">No program</option>{programs.filter(p=>!form.portfolioId||!p.portfolioId||p.portfolioId===form.portfolioId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="formGrid"><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Initial status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>DRAFT</option><option>PLANNED</option></select></label></div><div className="formGrid"><label>Start date<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>Target date<input type="date" value={form.targetDate} onChange={e=>setForm({...form,targetDate:e.target.value})}/></label></div><label>Approved budget<input type="number" min="0" step="0.01" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></label><div className="formActions"><button disabled={busy}>{busy?'Creating…':'Create project'}</button><button className="secondary" type="button" onClick={()=>router.push('/execution')}>Cancel</button></div></form></section></AdminShell>}
