CREATE TYPE "WorkspaceVisibility" AS ENUM ('PRIVATE','INTERNAL','PUBLIC');
CREATE TYPE "WorkspaceStatus" AS ENUM ('ACTIVE','ARCHIVED');
CREATE TYPE "WorkspaceMemberRole" AS ENUM ('OWNER','ADMIN','MEMBER','VIEWER');
CREATE TYPE "CommunityMembershipPolicy" AS ENUM ('OPEN','REQUEST_TO_JOIN','INVITE_ONLY');
CREATE TYPE "CommunityStatus" AS ENUM ('ACTIVE','ARCHIVED');
CREATE TYPE "CommunityMemberRole" AS ENUM ('OWNER','MODERATOR','MEMBER');
CREATE TABLE "TeamWorkspace" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"visibility" "WorkspaceVisibility" NOT NULL DEFAULT 'INTERNAL',"status" "WorkspaceStatus" NOT NULL DEFAULT 'ACTIVE',"createdByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "TeamWorkspace_organizationId_name_key" ON "TeamWorkspace"("organizationId","name");
CREATE INDEX "TeamWorkspace_organizationId_status_updatedAt_idx" ON "TeamWorkspace"("organizationId","status","updatedAt");
CREATE TABLE "WorkspaceMember" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"userId" TEXT NOT NULL,"role" "WorkspaceMemberRole" NOT NULL DEFAULT 'MEMBER',"joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"leftAt" TIMESTAMP(3));
CREATE UNIQUE INDEX "WorkspaceMember_workspaceId_userId_key" ON "WorkspaceMember"("workspaceId","userId");
CREATE INDEX "WorkspaceMember_organizationId_userId_leftAt_idx" ON "WorkspaceMember"("organizationId","userId","leftAt");
ALTER TABLE "WorkspaceMember" ADD CONSTRAINT "WorkspaceMember_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TeamWorkspace"("id") ON DELETE CASCADE;
CREATE TABLE "WorkspaceResource" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT NOT NULL,"label" TEXT,"linkedByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "WorkspaceResource_workspaceId_resourceType_resourceId_key" ON "WorkspaceResource"("workspaceId","resourceType","resourceId");
CREATE INDEX "WorkspaceResource_organizationId_resourceType_resourceId_idx" ON "WorkspaceResource"("organizationId","resourceType","resourceId");
ALTER TABLE "WorkspaceResource" ADD CONSTRAINT "WorkspaceResource_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TeamWorkspace"("id") ON DELETE CASCADE;
CREATE TABLE "WorkspaceAnnouncement" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"title" TEXT NOT NULL,"content" TEXT NOT NULL,"authorUserId" TEXT NOT NULL,"expiresAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "WorkspaceAnnouncement_organizationId_workspaceId_createdAt_idx" ON "WorkspaceAnnouncement"("organizationId","workspaceId","createdAt");
ALTER TABLE "WorkspaceAnnouncement" ADD CONSTRAINT "WorkspaceAnnouncement_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TeamWorkspace"("id") ON DELETE CASCADE;
CREATE TABLE "Community" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"workspaceId" TEXT,"name" TEXT NOT NULL,"description" TEXT,"membershipPolicy" "CommunityMembershipPolicy" NOT NULL DEFAULT 'OPEN',"status" "CommunityStatus" NOT NULL DEFAULT 'ACTIVE',"createdByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "Community_organizationId_name_key" ON "Community"("organizationId","name");
CREATE INDEX "Community_organizationId_status_updatedAt_idx" ON "Community"("organizationId","status","updatedAt");
ALTER TABLE "Community" ADD CONSTRAINT "Community_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "TeamWorkspace"("id") ON DELETE SET NULL;
CREATE TABLE "CommunityMember" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"communityId" TEXT NOT NULL,"userId" TEXT NOT NULL,"role" "CommunityMemberRole" NOT NULL DEFAULT 'MEMBER',"joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"leftAt" TIMESTAMP(3));
CREATE UNIQUE INDEX "CommunityMember_communityId_userId_key" ON "CommunityMember"("communityId","userId");
CREATE INDEX "CommunityMember_organizationId_userId_leftAt_idx" ON "CommunityMember"("organizationId","userId","leftAt");
ALTER TABLE "CommunityMember" ADD CONSTRAINT "CommunityMember_communityId_fkey" FOREIGN KEY ("communityId") REFERENCES "Community"("id") ON DELETE CASCADE;
