CREATE TYPE "DomainEventStatus" AS ENUM ('PENDING','PROCESSED','FAILED');
CREATE TYPE "NotificationType" AS ENUM ('INFO','SUCCESS','WARNING','ACTION_REQUIRED');
CREATE TYPE "NotificationChannel" AS ENUM ('IN_APP','EMAIL');
CREATE TYPE "NotificationDeliveryStatus" AS ENUM ('PENDING','SENT','FAILED','SKIPPED');
CREATE TABLE "DomainEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"eventName" TEXT NOT NULL,"aggregateType" TEXT NOT NULL,"aggregateId" TEXT NOT NULL,"actorUserId" TEXT,"payload" JSONB,"status" "DomainEventStatus" NOT NULL DEFAULT 'PENDING',"attempts" INTEGER NOT NULL DEFAULT 0,"processedAt" TIMESTAMP(3),"error" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Notification" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"type" "NotificationType" NOT NULL DEFAULT 'INFO',"eventName" TEXT,"title" TEXT NOT NULL,"body" TEXT NOT NULL,"actionUrl" TEXT,"metadata" JSONB,"readAt" TIMESTAMP(3),"archivedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "NotificationPreference" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"userId" TEXT NOT NULL UNIQUE,"inAppEnabled" BOOLEAN NOT NULL DEFAULT true,"emailEnabled" BOOLEAN NOT NULL DEFAULT true,"checkInReminders" BOOLEAN NOT NULL DEFAULT true,"riskAlerts" BOOLEAN NOT NULL DEFAULT true,"assignmentAlerts" BOOLEAN NOT NULL DEFAULT true,"commentAlerts" BOOLEAN NOT NULL DEFAULT true,"weeklyDigest" BOOLEAN NOT NULL DEFAULT true,"reminderDayOfWeek" INTEGER NOT NULL DEFAULT 4,"reminderHour" INTEGER NOT NULL DEFAULT 9,"digestDayOfWeek" INTEGER NOT NULL DEFAULT 0,"digestHour" INTEGER NOT NULL DEFAULT 8,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "NotificationDelivery" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"notificationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"channel" "NotificationChannel" NOT NULL,"status" "NotificationDeliveryStatus" NOT NULL DEFAULT 'PENDING',"provider" TEXT,"providerMessageId" TEXT,"error" TEXT,"sentAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "DomainEvent" ADD CONSTRAINT "DomainEvent_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "NotificationPreference" ADD CONSTRAINT "NotificationPreference_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "NotificationPreference" ADD CONSTRAINT "NotificationPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "NotificationDelivery" ADD CONSTRAINT "NotificationDelivery_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "NotificationDelivery" ADD CONSTRAINT "NotificationDelivery_notificationId_fkey" FOREIGN KEY ("notificationId") REFERENCES "Notification"("id") ON DELETE CASCADE;
ALTER TABLE "NotificationDelivery" ADD CONSTRAINT "NotificationDelivery_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
CREATE INDEX "DomainEvent_status_createdAt_idx" ON "DomainEvent"("status","createdAt");
CREATE INDEX "Notification_userId_readAt_createdAt_idx" ON "Notification"("userId","readAt","createdAt");
CREATE INDEX "NotificationDelivery_status_createdAt_idx" ON "NotificationDelivery"("status","createdAt");
