import { IsArray, IsDateString, IsEmail, IsEnum, IsIn, IsInt, IsNumber, IsOptional, IsString, Max, Min } from 'class-validator';
import { ResourceAllocationStatus, ResourceAllocationType, ResourceStatus, SkillProficiency } from '@prisma/client';
export class CreateResourceDto { @IsOptional() @IsString() userId?:string; @IsString() displayName!:string; @IsOptional() @IsEmail() email?:string; @IsOptional() @IsString() employeeCode?:string; @IsOptional() @IsString() jobTitle?:string; @IsOptional() @IsEnum(ResourceStatus) status?:ResourceStatus; @IsOptional() @IsNumber() @Min(0) capacityHoursPerWeek?:number; @IsOptional() @IsNumber() @Min(0) costRate?:number; @IsOptional() @IsString() currency?:string; @IsOptional() @IsString() timezone?:string; }
export class UpdateResourceDto extends CreateResourceDto {}
export class CreateResourceTeamDto { @IsString() name!:string; @IsOptional() @IsString() description?:string; @IsOptional() @IsString() leadUserId?:string; }
export class AddTeamMemberDto { @IsString() resourceId!:string; @IsOptional() @IsString() role?:string; @IsOptional() @IsNumber() @Min(0) @Max(100) allocationPercent?:number; }
export class CreateSkillDto { @IsString() name!:string; @IsOptional() @IsString() category?:string; @IsOptional() @IsString() description?:string; }
export class AssignSkillDto { @IsString() skillId!:string; @IsOptional() @IsEnum(SkillProficiency) proficiency?:SkillProficiency; @IsOptional() @IsNumber() @Min(0) yearsExperience?:number; }
export class CreateAllocationDto { @IsString() resourceId!:string; @IsOptional() @IsString() projectId?:string; @IsOptional() @IsString() programId?:string; @IsOptional() @IsEnum(ResourceAllocationType) type?:ResourceAllocationType; @IsOptional() @IsEnum(ResourceAllocationStatus) status?:ResourceAllocationStatus; @IsString() title!:string; @IsNumber() @Min(0) @Max(200) allocationPercent!:number; @IsOptional() @IsNumber() @Min(0) hoursPerWeek?:number; @IsDateString() startsAt!:string; @IsDateString() endsAt!:string; @IsOptional() @IsString() notes?:string; }
export class CreateWorkingCalendarDto { @IsString() name!:string; @IsOptional() @IsString() timezone?:string; @IsOptional() @IsNumber() @Min(0) hoursPerDay?:number; @IsOptional() @IsArray() @IsInt({each:true}) workingDays?:number[]; @IsOptional() isDefault?:boolean; }
export class CapacityQueryDto { @IsDateString() from!:string; @IsDateString() to!:string; @IsOptional() @IsIn(['week','month']) granularity?:'week'|'month'; @IsOptional() @IsString() teamId?:string; @IsOptional() @IsString() resourceId?:string; }
export class CreateHolidayCalendarDto { @IsString() name!:string; @IsOptional() @IsString() countryCode?:string; @IsOptional() @IsArray() holidays?:{date:string;name?:string}[]; }
export class CreateAvailabilityExceptionDto { @IsDateString() startsAt!:string; @IsDateString() endsAt!:string; @IsNumber() @Min(0) availableHours!:number; @IsOptional() @IsString() reason?:string; }
export class UpdateWorkingCalendarDto { @IsOptional() @IsString() name?:string; @IsOptional() @IsString() timezone?:string; @IsOptional() @IsNumber() @Min(0) hoursPerDay?:number; @IsOptional() @IsArray() @IsInt({each:true}) workingDays?:number[]; @IsOptional() @IsString() holidayCalendarId?:string; @IsOptional() isDefault?:boolean; }
export class ScheduleQueryDto { @IsDateString() from!:string; @IsDateString() to!:string; @IsOptional() @IsString() teamId?:string; @IsOptional() @IsString() resourceId?:string; @IsOptional() @IsString() timezone?:string; }
export class RescheduleAllocationDto { @IsOptional() @IsString() resourceId?:string; @IsDateString() startsAt!:string; @IsDateString() endsAt!:string; @IsOptional() @IsNumber() @Min(0) @Max(200) allocationPercent?:number; @IsOptional() @IsNumber() @Min(0) hoursPerWeek?:number; }
export class ScenarioMoveDto { @IsString() allocationId!:string; @IsOptional() @IsString() resourceId?:string; @IsDateString() startsAt!:string; @IsDateString() endsAt!:string; }
export class PreviewScheduleScenarioDto { @IsDateString() from!:string; @IsDateString() to!:string; @IsOptional() @IsString() teamId?:string; @IsArray() moves!:ScenarioMoveDto[]; }

export class WorkforceAnalyticsQueryDto { @IsOptional() @IsDateString() from?:string; @IsOptional() @IsDateString() to?:string; @IsOptional() @IsString() teamId?:string; @IsOptional() @IsString() currency?:string; }
