export type EnterpriseProvider='WORKDAY'|'SAP_SUCCESSFACTORS'|'BAMBOOHR'|'HIBOB'|'SLACK'|'MICROSOFT_TEAMS'|'GOOGLE_WORKSPACE'|'MICROSOFT_365';
export interface NormalizedEnterpriseItem {externalId:string;objectType:string;displayName:string;email?:string;status?:string;managerExternalId?:string;department?:string;updatedAt?:string;metadata?:Record<string,unknown>;raw?:Record<string,unknown>}
export interface EnterpriseProviderAdapter {provider:EnterpriseProvider;domain:'HRIS'|'COLLABORATION'|'PRODUCTIVITY';capabilities:string[];normalize(input:any):NormalizedEnterpriseItem;buildMessage?(input:any):Record<string,unknown>}
const t=(v:any)=>v==null?undefined:String(v);
const employee=(x:any,id:any,name:any,email:any,status:any,manager:any,department:any,updated:any):NormalizedEnterpriseItem=>({externalId:t(id)!,objectType:'EMPLOYEE',displayName:t(name)!,email:t(email)?.toLowerCase(),status:t(status),managerExternalId:t(manager),department:t(department),updatedAt:t(updated),raw:x});
const adapters:Record<EnterpriseProvider,EnterpriseProviderAdapter>={
 WORKDAY:{provider:'WORKDAY',domain:'HRIS',capabilities:['EMPLOYEE','ORGANIZATION_UNIT','POSITION'],normalize:x=>employee(x,x.Worker_ID||x.id,x.Worker||x.name,x.Email_Address||x.email,x.Worker_Status||x.status,x.Manager_ID,x.Supervisory_Organization,x.Updated_Moment||x.updatedAt)},
 SAP_SUCCESSFACTORS:{provider:'SAP_SUCCESSFACTORS',domain:'HRIS',capabilities:['EMPLOYEE','ORGANIZATION_UNIT','POSITION'],normalize:x=>employee(x,x.userId||x.personIdExternal,x.defaultFullName||x.firstName+' '+x.lastName,x.email,x.status,x.managerId,x.department,x.lastModifiedDateTime)},
 BAMBOOHR:{provider:'BAMBOOHR',domain:'HRIS',capabilities:['EMPLOYEE','ORGANIZATION_UNIT'],normalize:x=>employee(x,x.id,x.displayName||`${x.firstName||''} ${x.lastName||''}`.trim(),x.workEmail,x.status,x.supervisorId,x.department,x.lastChanged)},
 HIBOB:{provider:'HIBOB',domain:'HRIS',capabilities:['EMPLOYEE','ORGANIZATION_UNIT','POSITION'],normalize:x=>employee(x,x.id,x.displayName||x.fullName,x.email,x.status,x.work?.reportsTo?.id,x.work?.department,x.creationDateTime||x.updatedAt)},
 SLACK:{provider:'SLACK',domain:'COLLABORATION',capabilities:['TEAM','CHANNEL','MESSAGE'],normalize:x=>({externalId:t(x.id||x.ts)!,objectType:x.ts?'MESSAGE':x.is_channel?'CHANNEL':'TEAM',displayName:t(x.name||x.text||x.team?.name)!,updatedAt:t(x.updated||x.ts),raw:x}),buildMessage:i=>({channel:i.destinationId,text:i.text,blocks:i.blocks})},
 MICROSOFT_TEAMS:{provider:'MICROSOFT_TEAMS',domain:'COLLABORATION',capabilities:['TEAM','CHANNEL','MESSAGE'],normalize:x=>({externalId:t(x.id)!,objectType:x.body?'MESSAGE':x.membershipType?'CHANNEL':'TEAM',displayName:t(x.displayName||x.body?.content)!,updatedAt:t(x.lastModifiedDateTime||x.createdDateTime),raw:x}),buildMessage:i=>({body:{contentType:'html',content:i.text}})},
 GOOGLE_WORKSPACE:{provider:'GOOGLE_WORKSPACE',domain:'PRODUCTIVITY',capabilities:['EMPLOYEE','DIRECTORY_GROUP','CALENDAR_EVENT','DOCUMENT'],normalize:x=>({externalId:t(x.id||x.primaryEmail)!,objectType:x.primaryEmail?'EMPLOYEE':x.start?'CALENDAR_EVENT':x.mimeType?'DOCUMENT':'DIRECTORY_GROUP',displayName:t(x.name?.fullName||x.summary||x.name||x.email)!,email:t(x.primaryEmail||x.email),updatedAt:t(x.updated),raw:x})},
 MICROSOFT_365:{provider:'MICROSOFT_365',domain:'PRODUCTIVITY',capabilities:['EMPLOYEE','DIRECTORY_GROUP','CALENDAR_EVENT','DOCUMENT','MESSAGE'],normalize:x=>({externalId:t(x.id||x.userPrincipalName)!,objectType:x.userPrincipalName?'EMPLOYEE':x.start?'CALENDAR_EVENT':x.file?'DOCUMENT':x.mail?'MESSAGE':'DIRECTORY_GROUP',displayName:t(x.displayName||x.subject||x.name)!,email:t(x.mail||x.userPrincipalName),updatedAt:t(x.lastModifiedDateTime),raw:x})}
};
export const getEnterpriseProviderAdapter=(provider:EnterpriseProvider)=>adapters[provider];
export const ENTERPRISE_CONNECTOR_CATALOG=Object.values(adapters).map(a=>({provider:a.provider,domain:a.domain,capabilities:a.capabilities,supports:['preview','sync','mapping',...(a.buildMessage?['message-delivery']:[])]}));
