import {BadRequestException,Injectable,NotFoundException} from '@nestjs/common';
import { Prisma } from '@prisma/client';
import {createHash} from 'crypto';
import {PrismaService} from '../../prisma/prisma.service';
import {ENTERPRISE_CONNECTOR_CATALOG,EnterpriseProvider,getEnterpriseProviderAdapter} from './enterprise-provider-adapters';
@Injectable() export class EnterpriseConnectorsService {constructor(private prisma:PrismaService){}
 catalog(){return ENTERPRISE_CONNECTOR_CATALOG}
 list(org:string){return this.prisma.enterpriseConnectorProfile.findMany({where:{organizationId:org},include:{integrationInstance:{include:{definition:true}},mappings:true},orderBy:{updatedAt:'desc'}})}
 async create(org:string,d:any){const instance=await this.prisma.integrationInstance.findFirst({where:{id:d.integrationInstanceId,organizationId:org}});if(!instance)throw new NotFoundException('Integration instance not found');const adapter=getEnterpriseProviderAdapter(d.provider as EnterpriseProvider);if(!adapter)throw new BadRequestException('Unsupported provider');return this.prisma.enterpriseConnectorProfile.create({data:{organizationId:org,integrationInstanceId:d.integrationInstanceId,provider:d.provider,domain:adapter.domain,baseUrl:d.baseUrl,tenantKey:d.tenantKey,enabledObjects:d.enabledObjects||adapter.capabilities,settings:d.settings||{}}})}
 async replaceMappings(org:string,id:string,d:any){await this.require(org,id);await this.prisma.enterpriseConnectorMapping.deleteMany({where:{organizationId:org,profileId:id}});return this.prisma.enterpriseConnectorMapping.createMany({data:(d.mappings||[]).map((m:any)=>({organizationId:org,profileId:id,objectType:m.objectType,direction:m.direction||'INBOUND',sourceField:m.sourceField,targetField:m.targetField,transform:m.transform,required:!!m.required}))})}
 async preview(org:string,id:string,d:any){const p=await this.require(org,id);const a=getEnterpriseProviderAdapter(p.provider as EnterpriseProvider);const items=(d.items||[]).map((x:any)=>a.normalize(x));return {provider:p.provider,domain:p.domain,dryRun:true,received:items.length,items:items.map(({raw,...x}:any)=>x),warnings:items.filter((x:any)=>!x.externalId||!x.displayName).map((x:any)=>({externalId:x.externalId,message:'External id and display name are required'}))}}
 async sync(org:string,id:string,d:any){const p=await this.require(org,id);const a=getEnterpriseProviderAdapter(p.provider as EnterpriseProvider);const execution=await this.prisma.integrationExecution.create({data:{organizationId:org,integrationInstanceId:p.integrationInstanceId,type:'SYNC',status:'RUNNING',attempt:1,startedAt:new Date(),requestSummary:{provider:p.provider,count:(d.items||[]).length}}});let succeeded=0,failed=0;for(const raw of d.items||[]){try{const item=a.normalize(raw);if(!item.externalId||!item.displayName)throw new Error('External id and display name are required');const checksum=createHash('sha256').update(JSON.stringify(item.raw||raw)).digest('hex');await this.prisma.enterpriseConnectorSyncItem.upsert({where:{profileId_objectType_externalId:{profileId:id,objectType:item.objectType as any,externalId:item.externalId}},update:{executionId:execution.id,status:'SUCCEEDED',checksum,sourceUpdatedAt:item.updatedAt?new Date(item.updatedAt):undefined,payloadSummary:{displayName:item.displayName,email:item.email,status:item.status,department:item.department}},create:{organizationId:org,profileId:id,executionId:execution.id,externalId:item.externalId,objectType:item.objectType as any,status:'SUCCEEDED',checksum,sourceUpdatedAt:item.updatedAt?new Date(item.updatedAt):undefined,payloadSummary:{displayName:item.displayName,email:item.email,status:item.status,department:item.department}}});succeeded++}catch{failed++}}
 await this.prisma.integrationExecution.update({where:{id:execution.id},data:{status:failed?'FAILED':'SUCCEEDED',completedAt:new Date(),responseSummary:{succeeded,failed},errorMessage:failed?`${failed} item(s) failed normalization`:undefined}});await this.prisma.enterpriseConnectorProfile.update({where:{id},data:{lastSuccessfulSyncAt:failed?undefined:new Date()}});await this.prisma.integrationInstance.update({where:{id:p.integrationInstanceId},data:{lastSyncAt:new Date(),status:failed?'ERROR':'ACTIVE'}});return {executionId:execution.id,succeeded,failed}}
 async deliver(org:string,id:string,d:any){const p=await this.require(org,id);const a=getEnterpriseProviderAdapter(p.provider as EnterpriseProvider);if(!a.buildMessage)throw new BadRequestException('Provider does not support collaboration message delivery');const key=d.idempotencyKey||createHash('sha256').update(`${id}:${d.destinationId}:${d.text}`).digest('hex');const existing=await this.prisma.collaborationDelivery.findUnique({where:{organizationId_idempotencyKey:{organizationId:org,idempotencyKey:key}}});if(existing)return existing;const payload=a.buildMessage(d);return this.prisma.collaborationDelivery.create({data:{organizationId:org,profileId:id,provider:p.provider,destinationType:d.destinationType||'CHANNEL',destinationId:d.destinationId,messageType:d.messageType||'TEXT',idempotencyKey:key,payload:payload as Prisma.InputJsonValue,status:'PENDING'}})}
 deliveries(org:string,id:string){return this.prisma.collaborationDelivery.findMany({where:{organizationId:org,profileId:id},orderBy:{createdAt:'desc'}})}
 private async require(org:string,id:string){const row=await this.prisma.enterpriseConnectorProfile.findFirst({where:{id,organizationId:org},include:{integrationInstance:true}});if(!row)throw new NotFoundException('Enterprise connector profile not found');return row}
}
