'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { AdminShell } from '../../../components/admin-shell';
import { api } from '../../../lib/api';

type Project={id:string;key:string;name:string;health:string;status:string;progress:string;portfolio?:{name:string};program?:{name:string};variance:{scheduleVariancePoints:number;budgetVariancePercent:number;budgetVariance:number;daysRemaining:number|null}};
type Risk={id:string;title:string;probability:string;impact:string;score:number;project:{id:string;key:string;name:string;health:string}};
type Milestone={id:string;name:string;plannedDate:string;status:string;project:{id:string;key:string;name:string;health:string}};
type PortfolioRow={id:string;name:string;projects:number;activeProjects:number;atRiskProjects:number;averageProgress:number;totalBudget:number;actualCost:number;budgetVariancePercent:number;averageScheduleVariance:number};
type Dashboard={generatedAt:string;summary:{projects:number;activeProjects:number;atRiskProjects:number;averageProgress:number;totalBudget:number;actualCost:number;budgetVariance:number;budgetVariancePercent:number;averageScheduleVariance:number;openRisks:number;openIssues:number;overdueMilestones:number;healthDistribution:{onTrack:number;atRisk:number;offTrack:number;notSet:number}};projects:Project[];portfolioRows:PortfolioRow[];riskHeatMap:{probability:string;impact:string;count:number;score:number}[];topRisks:Risk[];milestoneForecast:{overdue:Milestone[];upcoming:Milestone[]};deliveryTrend:{month:string;completed:number;due:number}[]};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
const label=(v:string)=>v?.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function PortfolioAnalyticsPage(){
 const [data,setData]=useState<Dashboard|null>(null),[error,setError]=useState('');
 useEffect(()=>{api<Dashboard>('/execution/analytics/dashboard').then(setData).catch(e=>setError(e instanceof Error?e.message:'Unable to load analytics'))},[]);
 const attention=useMemo(()=>data?.projects.filter(p=>['AT_RISK','OFF_TRACK'].includes(p.health)||p.variance.scheduleVariancePoints<-10||p.variance.budgetVariancePercent>10).slice(0,8)??[],[data]);
 const probabilities=['LOW','MEDIUM','HIGH','CRITICAL'],impacts=['LOW','MEDIUM','HIGH','CRITICAL'];
 const heat=(p:string,i:string)=>data?.riskHeatMap.find(x=>x.probability===p&&x.impact===i)?.count??0;
 return <AdminShell title="Portfolio analytics" subtitle="Executive delivery intelligence across portfolios, programs, projects, risks, milestones, schedules, and investment." action={<Link className="buttonLink" href="/execution">Back to execution</Link>}>
  {error&&<div className="formError">{error}</div>}
  <section className="metrics executionMetrics"><article><p>Portfolio health</p><strong>{data?.summary.atRiskProjects??'—'}</strong><span>projects at risk or off track</span></article><article><p>Schedule variance</p><strong>{Math.round(data?.summary.averageScheduleVariance??0)} pts</strong><span>average delivery versus plan</span></article><article><p>Budget variance</p><strong>{Math.round(data?.summary.budgetVariancePercent??0)}%</strong><span>{money(data?.summary.actualCost??0)} actual / {money(data?.summary.totalBudget??0)} budget</span></article><article><p>Milestone exposure</p><strong>{data?.summary.overdueMilestones??'—'}</strong><span>{data?.summary.openRisks??0} open risks · {data?.summary.openIssues??0} open issues</span></article></section>
  <section className="panel tablePanel"><div className="panelHead"><div><h2>Executive attention</h2><p>Projects surfaced by health, schedule, or budget signals.</p></div></div><div className="executionTable"><div className="executionRow executionHead"><span>Project</span><span>Health</span><span>Progress</span><span>Schedule</span><span>Budget</span><span>Time</span></div>{attention.map(p=><Link href={`/execution/projects/${p.id}`} className="executionRow" key={p.id}><span><strong>{p.key} · {p.name}</strong><small>{p.program?.name||p.portfolio?.name||'Unassigned'}</small></span><span><i className={`status health-${p.health.toLowerCase()}`}>{label(p.health)}</i></span><span>{Math.round(Number(p.progress))}%</span><span className={p.variance.scheduleVariancePoints<-10?'negative':''}>{Math.round(p.variance.scheduleVariancePoints)} pts</span><span className={p.variance.budgetVariancePercent>10?'negative':''}>{Math.round(p.variance.budgetVariancePercent)}%</span><span>{p.variance.daysRemaining===null?'—':`${p.variance.daysRemaining} days`}</span></Link>)}{!attention.length&&<div className="emptyState"><h2>No material delivery exposure</h2><p>Current project signals are within configured thresholds.</p></div>}</div></section>
  <section className="analyticsGrid"><article className="panel"><div className="panelHead"><div><h2>Risk heat map</h2><p>Open risks by probability and impact.</p></div></div><div className="riskHeat"><span></span>{impacts.map(i=><strong key={i}>{label(i)}</strong>)}{probabilities.map(p=><div className="heatRow" key={p}><strong>{label(p)}</strong>{impacts.map(i=><span className={`heatCell heat-${Math.min(4,Math.ceil((probabilities.indexOf(p)+1)*(impacts.indexOf(i)+1)/4))}`} key={i}>{heat(p,i)}</span>)}</div>)}</div></article>
  <article className="panel"><div className="panelHead"><div><h2>Milestone forecast</h2><p>Overdue and upcoming strategic checkpoints.</p></div></div><div className="activityList">{data?.milestoneForecast.overdue.slice(0,5).map(m=><Link href={`/execution/projects/${m.project.id}`} key={m.id}><strong>{m.project.key} · {m.name}</strong><span className="negative">Overdue · {new Date(m.plannedDate).toLocaleDateString()}</span></Link>)}{data?.milestoneForecast.upcoming.slice(0,5).map(m=><Link href={`/execution/projects/${m.project.id}`} key={m.id}><strong>{m.project.key} · {m.name}</strong><span>{new Date(m.plannedDate).toLocaleDateString()}</span></Link>)}</div></article></section>
  <section className="panel tablePanel"><div className="panelHead"><div><h2>Portfolio performance</h2><p>Aggregated progress, health, schedule, and investment performance.</p></div></div><div className="executionTable"><div className="executionRow executionHead"><span>Portfolio</span><span>Projects</span><span>At risk</span><span>Progress</span><span>Schedule</span><span>Budget</span></div>{data?.portfolioRows.map(p=><div className="executionRow" key={p.id}><span><strong>{p.name}</strong><small>{p.activeProjects} active</small></span><span>{p.projects}</span><span>{p.atRiskProjects}</span><span>{Math.round(p.averageProgress)}%</span><span>{Math.round(p.averageScheduleVariance)} pts</span><span>{Math.round(p.budgetVariancePercent)}%</span></div>)}</div></section>
  <section className="analyticsGrid"><article className="panel"><div className="panelHead"><div><h2>Highest exposure risks</h2><p>Ranked by probability × impact.</p></div></div><div className="activityList">{data?.topRisks.slice(0,8).map(r=><Link href={`/execution/projects/${r.project.id}`} key={r.id}><strong>{r.title}</strong><span>{r.project.key} · {label(r.probability)} probability · {label(r.impact)} impact</span></Link>)}</div></article><article className="panel"><div className="panelHead"><div><h2>Delivery trend</h2><p>Projects due versus completed over six months.</p></div></div><div className="trendBars">{data?.deliveryTrend.map(t=><div key={t.month}><span>{t.month}</span><i style={{height:`${Math.max(8,t.due*18)}px`}} title={`${t.due} due`}/><b style={{height:`${Math.max(8,t.completed*18)}px`}} title={`${t.completed} completed`}/><small>{t.completed}/{t.due}</small></div>)}</div></article></section>
 </AdminShell>
}
