import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AddEdgeDto, AddNodeDto, ApprovalDecisionDto, CompleteStepDto, CreateAutomationDto, StartAutomationDto, UpdateAutomationDto } from './dto';
@Injectable()
export class IntegrationAutomationService {
 constructor(private readonly prisma:PrismaService){} private db(){return this.prisma as any;}
 workflows(org:string){return this.db().integrationAutomation.findMany({where:{organizationId:org},include:{_count:{select:{nodes:true,edges:true,runs:true}}},orderBy:{updatedAt:'desc'}})}
 async workflow(org:string,id:string){const x=await this.db().integrationAutomation.findFirst({where:{id,organizationId:org},include:{nodes:{orderBy:{createdAt:'asc'}},edges:true}});if(!x)throw new NotFoundException('Automation not found');return x}
 create(org:string,user:string,d:CreateAutomationDto){return this.db().integrationAutomation.create({data:{organizationId:org,createdByUserId:user,name:d.name,description:d.description,triggerType:d.triggerType,triggerConfig:d.triggerConfig,tags:d.tags||[]}})}
 async update(org:string,id:string,d:UpdateAutomationDto){const x=await this.requireAutomation(org,id);if(x.status==='PUBLISHED')throw new ConflictException('Published automation definitions are immutable; create a new version');return this.db().integrationAutomation.update({where:{id},data:d})}
 async addNode(org:string,id:string,d:AddNodeDto){const x=await this.requireDraft(org,id);return this.db().integrationAutomationNode.create({data:{organizationId:org,automationId:x.id,key:d.key,name:d.name,type:d.type,config:d.config,maxAttempts:d.maxAttempts??3,timeoutSeconds:d.timeoutSeconds??300}})}
 async addEdge(org:string,id:string,d:AddEdgeDto){const x=await this.requireDraft(org,id);const nodes=await this.db().integrationAutomationNode.findMany({where:{automationId:id,key:{in:[d.fromNodeKey,d.toNodeKey]}}});if(nodes.length!==2)throw new BadRequestException('Both edge nodes must exist in this automation');return this.db().integrationAutomationEdge.create({data:{organizationId:org,automationId:x.id,...d,outcome:d.outcome||'SUCCESS'}})}
 async publish(org:string,user:string,id:string){const x=await this.workflow(org,id);if(!x.enabled)throw new BadRequestException('Disabled automation cannot be published');if(!x.nodes.length)throw new BadRequestException('Automation requires at least one node');if(!x.nodes.some((n:any)=>n.type==='TRIGGER'))throw new BadRequestException('Automation requires a trigger node');return this.db().integrationAutomation.update({where:{id},data:{status:'PUBLISHED',publishedAt:new Date(),publishedByUserId:user,version:{increment:1}}})}
 async start(org:string,user:string,id:string,d:StartAutomationDto){const x=await this.requireAutomation(org,id);if(x.status!=='PUBLISHED'||!x.enabled)throw new BadRequestException('Only enabled published automations can run');if(d.idempotencyKey){const old=await this.db().integrationAutomationRun.findFirst({where:{organizationId:org,automationId:id,idempotencyKey:d.idempotencyKey}});if(old)return old;}const trigger=await this.db().integrationAutomationNode.findFirst({where:{automationId:id,type:'TRIGGER'}});const run=await this.db().integrationAutomationRun.create({data:{organizationId:org,automationId:id,status:'RUNNING',triggerType:x.triggerType,input:d.input,idempotencyKey:d.idempotencyKey,startedAt:new Date(),triggeredByUserId:user,steps:trigger?{create:{organizationId:org,nodeId:trigger.id,status:'PENDING',attempt:1}}:undefined},include:{steps:true}});return {run,executionBoundary:'A distributed worker must claim pending steps, execute adapters, and call the step completion endpoint.'}}
 runs(org:string,take=100){return this.db().integrationAutomationRun.findMany({where:{organizationId:org},include:{automation:true,_count:{select:{steps:true,approvals:true}}},orderBy:{createdAt:'desc'},take:Math.min(take,500)})}
 async cancel(org:string,id:string){const run=await this.requireRun(org,id);if(['SUCCEEDED','FAILED','CANCELLED'].includes(run.status))throw new ConflictException('Run is already terminal');return this.db().integrationAutomationRun.update({where:{id},data:{status:'CANCELLED',completedAt:new Date()}})}
 async completeStep(org:string,id:string,d:CompleteStepDto){const step=await this.db().integrationAutomationStepRun.findFirst({where:{id,organizationId:org},include:{node:true,run:true}});if(!step)throw new NotFoundException('Step not found');if(!['PENDING','RUNNING','RETRY_SCHEDULED'].includes(step.status))throw new ConflictException('Step is not executable');const failed=!!d.errorMessage;const status=failed?(step.attempt>=step.node.maxAttempts?'FAILED':'RETRY_SCHEDULED'):'SUCCEEDED';const updated=await this.db().integrationAutomationStepRun.update({where:{id},data:{status,output:d.output,errorMessage:d.errorMessage,completedAt:failed&&status==='RETRY_SCHEDULED'?undefined:new Date(),nextAttemptAt:status==='RETRY_SCHEDULED'?new Date(Date.now()+Math.min(86400000,1000*2**step.attempt)):undefined}});if(status==='FAILED')await this.db().integrationAutomationRun.update({where:{id:step.runId},data:{status:'FAILED',errorMessage:d.errorMessage,completedAt:new Date()}});else if(status==='SUCCEEDED')await this.advance(step,d.outcome||'SUCCESS');return updated}
 async retryStep(org:string,id:string){const step=await this.db().integrationAutomationStepRun.findFirst({where:{id,organizationId:org},include:{node:true}});if(!step)throw new NotFoundException('Step not found');if(!['FAILED','RETRY_SCHEDULED'].includes(step.status))throw new ConflictException('Only failed or scheduled steps can be retried');return this.db().integrationAutomationStepRun.update({where:{id},data:{status:'PENDING',attempt:{increment:1},errorMessage:null,nextAttemptAt:null,completedAt:null}})}
 approvals(org:string,user:string){return this.db().integrationAutomationApproval.findMany({where:{organizationId:org,status:'PENDING',OR:[{approverUserId:user},{approverUserId:null}]},include:{run:{include:{automation:true}},step:true},orderBy:{createdAt:'asc'}})}
 async decide(org:string,user:string,id:string,d:ApprovalDecisionDto){const a=await this.db().integrationAutomationApproval.findFirst({where:{id,organizationId:org,status:'PENDING'}});if(!a)throw new NotFoundException('Approval not found');if(a.requestedByUserId===user)throw new BadRequestException('Requester cannot approve their own automation action');const decision=d.decision.toUpperCase();if(!['APPROVED','REJECTED'].includes(decision))throw new BadRequestException('Decision must be APPROVED or REJECTED');const out=await this.db().integrationAutomationApproval.update({where:{id},data:{status:decision,decisionNotes:d.notes,decidedByUserId:user,decidedAt:new Date()}});await this.db().integrationAutomationStepRun.update({where:{id:a.stepId},data:{status:decision==='APPROVED'?'SUCCEEDED':'FAILED',completedAt:new Date(),errorMessage:decision==='REJECTED'?'Approval rejected':null}});if(decision==='APPROVED'){const step=await this.db().integrationAutomationStepRun.findUnique({where:{id:a.stepId},include:{node:true,run:true}});await this.advance(step,'APPROVED')}else await this.db().integrationAutomationRun.update({where:{id:a.runId},data:{status:'FAILED',errorMessage:'Approval rejected',completedAt:new Date()}});return out}
 async analytics(org:string,days=30){const since=new Date(Date.now()-Math.min(days,90)*86400000);const [workflows,runs,approvals]=await Promise.all([this.db().integrationAutomation.count({where:{organizationId:org,status:'PUBLISHED',enabled:true}}),this.db().integrationAutomationRun.groupBy({by:['status'],where:{organizationId:org,createdAt:{gte:since}},_count:{_all:true}}),this.db().integrationAutomationApproval.count({where:{organizationId:org,status:'PENDING'}})]);return {publishedWorkflows:workflows,runsByStatus:runs,pendingApprovals:approvals,windowDays:Math.min(days,90)}}
 private async advance(step:any,outcome:string){const edges=await this.db().integrationAutomationEdge.findMany({where:{automationId:step.run.automationId,fromNodeKey:step.node.key,outcome}});if(!edges.length){await this.db().integrationAutomationRun.update({where:{id:step.runId},data:{status:'SUCCEEDED',completedAt:new Date()}});return;}for(const edge of edges){const node=await this.db().integrationAutomationNode.findFirst({where:{automationId:step.run.automationId,key:edge.toNodeKey}});if(!node)continue;const next=await this.db().integrationAutomationStepRun.create({data:{organizationId:step.organizationId,runId:step.runId,nodeId:node.id,status:node.type==='APPROVAL'?'WAITING_APPROVAL':'PENDING',attempt:1}});if(node.type==='APPROVAL')await this.db().integrationAutomationApproval.create({data:{organizationId:step.organizationId,runId:step.runId,stepId:next.id,requestedByUserId:step.run.triggeredByUserId,approverUserId:(node.config as any)?.approverUserId}})}}
 private async requireAutomation(org:string,id:string){const x=await this.db().integrationAutomation.findFirst({where:{id,organizationId:org}});if(!x)throw new NotFoundException('Automation not found');return x}
 private async requireDraft(org:string,id:string){const x=await this.requireAutomation(org,id);if(x.status==='PUBLISHED')throw new ConflictException('Published automation is immutable');return x}
 private async requireRun(org:string,id:string){const x=await this.db().integrationAutomationRun.findFirst({where:{id,organizationId:org}});if(!x)throw new NotFoundException('Run not found');return x}
}
