import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { AcknowledgeInsightDto, CreateInsightSubscriptionDto, CreateManualInsightDto } from './dto/insights-hub.dto';
@Injectable()
export class InsightsHubService {
 constructor(private prisma:PrismaService){}
 list(org:string,q:{status?:string;severity?:string;type?:string;tag?:string}){return this.prisma.enterpriseInsight.findMany({where:{organizationId:org,...(q.status?{status:q.status as any}:{}),...(q.severity?{severity:q.severity as any}:{}),...(q.type?{type:q.type as any}:{}),...(q.tag?{tags:{has:q.tag}}:{})},include:{acknowledgements:{orderBy:{createdAt:'desc'},take:1}},orderBy:[{severity:'desc'},{score:'desc'},{createdAt:'desc'}],take:500})}
 async detail(org:string,id:string){const x=await this.prisma.enterpriseInsight.findFirst({where:{id,organizationId:org},include:{acknowledgements:{orderBy:{createdAt:'desc'}}}});if(!x)throw new NotFoundException('Insight not found');return x}
 createManual(org:string,user:string,d:CreateManualInsightDto){return this.prisma.enterpriseInsight.create({data:{organizationId:org,type:'SIGNAL',sourceType:'MANUAL',title:d.title,summary:d.summary,severity:d.severity,entityType:d.entityType,entityId:d.entityId,score:d.score??50,confidence:d.confidence,impact:(d.impact||{}) as any,evidence:(d.evidence||[]) as any,tags:d.tags||[],createdById:user}})}
 async acknowledge(org:string,user:string,id:string,d:AcknowledgeInsightDto){const x=await this.prisma.enterpriseInsight.findFirst({where:{id,organizationId:org}});if(!x)throw new NotFoundException('Insight not found');return this.prisma.$transaction(async tx=>{const a=await tx.insightAcknowledgement.create({data:{insightId:id,userId:user,note:d.note,status:d.status}});await tx.enterpriseInsight.update({where:{id},data:{status:d.status}});return a})}
 async refresh(org:string,user:string){const [predictions,recommendations]=await Promise.all([this.prisma.predictionResult.findMany({where:{organizationId:org,confidence:{gte:.6}},orderBy:{createdAt:'desc'},take:100}),this.prisma.decisionRecommendation.findMany({where:{organizationId:org,status:{in:['PROPOSED','UNDER_REVIEW']}},orderBy:{createdAt:'desc'},take:100})]);let created=0;for(const p of predictions){await this.prisma.enterpriseInsight.upsert({where:{organizationId_sourceType_sourceId:{organizationId:org,sourceType:'PREDICTION_RESULT',sourceId:p.id}},update:{confidence:p.confidence,updatedAt:new Date()},create:{organizationId:org,type:'PREDICTION',severity:p.confidence>=.85?'HIGH':'MEDIUM',title:`Predictive signal for ${p.entityType}`,summary:`Forecast value ${p.predictedValue.toFixed(2)} with ${(p.confidence*100).toFixed(0)}% confidence.`,sourceType:'PREDICTION_RESULT',sourceId:p.id,entityType:p.entityType,entityId:p.entityId,score:Math.round(p.confidence*100),confidence:p.confidence,evidence:[{predictionResultId:p.id,explanation:p.explanation}] as any,tags:['prediction',p.entityType.toLowerCase()],createdById:user}});created++}for(const r of recommendations){await this.prisma.enterpriseInsight.upsert({where:{organizationId_sourceType_sourceId:{organizationId:org,sourceType:'DECISION_RECOMMENDATION',sourceId:r.id}},update:{status:r.status==='UNDER_REVIEW'?'IN_REVIEW':'NEW',updatedAt:new Date()},create:{organizationId:org,type:'RECOMMENDATION',severity:r.priority==='CRITICAL'?'CRITICAL':r.priority==='HIGH'?'HIGH':'MEDIUM',title:r.title,summary:r.summary,sourceType:'DECISION_RECOMMENDATION',sourceId:r.id,entityType:r.entityType,entityId:r.entityId,score:Math.round(r.confidence*100),confidence:r.confidence,impact:r.expectedImpact,evidence:r.evidence,tags:['recommendation',r.recommendationType.toLowerCase()],createdById:user}});created++}return {processed:predictions.length+recommendations.length,upserted:created}}
 dashboard(org:string){return Promise.all([this.prisma.enterpriseInsight.groupBy({by:['status'],where:{organizationId:org},_count:{_all:true}}),this.prisma.enterpriseInsight.groupBy({by:['severity'],where:{organizationId:org,status:{notIn:['RESOLVED','DISMISSED','EXPIRED']}},_count:{_all:true}})]).then(([byStatus,bySeverity])=>({byStatus,bySeverity}))}
 subscriptions(org:string,user:string){return this.prisma.insightSubscription.findMany({where:{organizationId:org,userId:user},orderBy:{name:'asc'}})}
 createSubscription(org:string,user:string,d:CreateInsightSubscriptionDto){return this.prisma.insightSubscription.create({data:{organizationId:org,userId:user,name:d.name,filters:(d.filters||{}) as any,frequency:d.frequency,channels:d.channels,enabled:d.enabled??true}})}
}
