import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
import { CreateAIModelDto, CreateAIProviderDto, CreatePromptTemplateDto, ExecuteAIDto } from './dto';
import { OpenAICompatibleAdapter } from './providers/openai-compatible.adapter';
@Injectable()
export class AIPlatformService {
 constructor(private readonly prisma:PrismaService, private readonly adapter:OpenAICompatibleAdapter){}
 private db(){return this.prisma as any;}
 providers(org:string){return this.db().aIProvider.findMany({where:{organizationId:org},include:{models:true},orderBy:{createdAt:'desc'}})}
 createProvider(org:string,d:CreateAIProviderDto){return this.db().aIProvider.create({data:{organizationId:org,name:d.name,type:d.type,status:'DRAFT',endpoint:d.endpoint,credentialRef:d.credentialRef,configuration:d.configuration??{}}})}
 models(org:string){return this.db().aIModel.findMany({where:{organizationId:org},include:{provider:true},orderBy:{createdAt:'desc'}})}
 async createModel(org:string,d:CreateAIModelDto){const provider=await this.db().aIProvider.findFirst({where:{id:d.providerId,organizationId:org}});if(!provider)throw new NotFoundException('AI provider not found');return this.db().aIModel.create({data:{organizationId:org,...d,status:'ACTIVE'}})}
 prompts(org:string){return this.db().promptTemplate.findMany({where:{organizationId:org},include:{versions:{orderBy:{version:'desc'}}},orderBy:{createdAt:'desc'}})}
 async createPrompt(org:string,userId:string,d:CreatePromptTemplateDto){return this.db().$transaction(async(tx:any)=>{const template=await tx.promptTemplate.create({data:{organizationId:org,key:d.key,name:d.name,domain:d.domain,status:'DRAFT'}});await tx.promptTemplateVersion.create({data:{organizationId:org,templateId:template.id,version:1,content:d.content,variables:d.variables??[],status:'DRAFT',createdByUserId:userId}});return tx.promptTemplate.findUnique({where:{id:template.id},include:{versions:true}})})}
 usage(org:string){return this.db().aITokenUsage.findMany({where:{organizationId:org},orderBy:{createdAt:'desc'},take:250})}
 costs(org:string){return this.db().aICostRecord.findMany({where:{organizationId:org},orderBy:{createdAt:'desc'},take:250})}
 audit(org:string){return this.db().aIExecutionAudit.findMany({where:{organizationId:org},orderBy:{createdAt:'desc'},take:250})}
 async execute(org:string,userId:string,d:ExecuteAIDto){const correlationId=randomUUID();const started=Date.now();const model=d.modelId?await this.db().aIModel.findFirst({where:{id:d.modelId,organizationId:org,status:'ACTIVE'},include:{provider:true}}):await this.db().aIModel.findFirst({where:{organizationId:org,status:'ACTIVE'},include:{provider:true},orderBy:{createdAt:'asc'}});if(!model)throw new BadRequestException('No active AI model is configured');
 let messages=[...d.messages];let promptVersionId:string|undefined;
 if(d.promptKey){const template=await this.db().promptTemplate.findFirst({where:{organizationId:org,key:d.promptKey,status:'PUBLISHED'},include:{versions:{where:{status:'PUBLISHED'},orderBy:{version:'desc'},take:1}}});if(!template?.versions?.[0])throw new BadRequestException('Published prompt template not found');const v=template.versions[0];let content=v.content;for(const [key,value] of Object.entries(d.variables??{}))content=content.replaceAll(`{{${key}}}`,String(value));messages=[{role:'system',content},...messages];promptVersionId=v.id;}
 try{const response=await this.adapter.execute(model.provider.configuration??{}, {model:model.externalId,messages,maxTokens:d.maxTokens,temperature:d.temperature,correlationId});const promptTokens=response.promptTokens??0,completionTokens=response.completionTokens??0,totalTokens=promptTokens+completionTokens;const cost=this.adapter.estimateCost(promptTokens,completionTokens,{inputPerMillion:model.inputCostPerMillion,outputPerMillion:model.outputCostPerMillion});await this.db().$transaction([this.db().aITokenUsage.create({data:{organizationId:org,userId,module:d.module??'platform',providerId:model.providerId,modelId:model.id,promptVersionId,correlationId,promptTokens,completionTokens,totalTokens}}),this.db().aICostRecord.create({data:{organizationId:org,providerId:model.providerId,modelId:model.id,correlationId,currency:'USD',estimatedCost:cost}}),this.db().aIExecutionAudit.create({data:{organizationId:org,userId,module:d.module??'platform',providerId:model.providerId,modelId:model.id,promptVersionId,correlationId,status:'COMPLETED',durationMs:Date.now()-started,safetyOutcome:'ALLOWED',promptSnapshot:d.storeContent?messages:undefined,responseSnapshot:d.storeContent?response.content:undefined}})]);return{correlationId,model:{id:model.id,name:model.name,provider:model.provider.name},response:response.content,usage:{promptTokens,completionTokens,totalTokens,estimatedCost:cost},finishReason:response.finishReason};}catch(error){await this.db().aIExecutionAudit.create({data:{organizationId:org,userId,module:d.module??'platform',providerId:model.providerId,modelId:model.id,promptVersionId,correlationId,status:'FAILED',durationMs:Date.now()-started,safetyOutcome:'NOT_EVALUATED',errorMessage:error instanceof Error?error.message:'Unknown execution error'}});throw error;}}
 async dashboard(org:string){const [providers,models,prompts,executions,usage,cost]=await Promise.all([this.db().aIProvider.count({where:{organizationId:org,status:'ACTIVE'}}),this.db().aIModel.count({where:{organizationId:org,status:'ACTIVE'}}),this.db().promptTemplate.count({where:{organizationId:org,status:'PUBLISHED'}}),this.db().aIExecutionAudit.count({where:{organizationId:org}}),this.db().aITokenUsage.aggregate({where:{organizationId:org},_sum:{totalTokens:true}}),this.db().aICostRecord.aggregate({where:{organizationId:org},_sum:{estimatedCost:true}})]);return{activeProviders:providers,activeModels:models,publishedPrompts:prompts,totalExecutions:executions,totalTokens:usage._sum.totalTokens??0,estimatedCost:cost._sum.estimatedCost??0,currency:'USD'}}
}
