import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AssessRiskDto, CompleteControlTestDto, CreateControlTestDto, CreateCorrectiveActionDto, CreateFindingDto, CreateRiskDto } from './dto';

@Injectable()
export class RiskAssuranceService {
  constructor(private readonly prisma: PrismaService) {}
  private score(likelihood:number, impact:number, effectiveness=0) { const inherent=likelihood*impact; const residual=Math.max(0, Number((inherent*(1-effectiveness)).toFixed(2))); const level=residual>=20?'CRITICAL':residual>=12?'HIGH':residual>=6?'MEDIUM':residual>=3?'LOW':'VERY_LOW'; return { inherent, residual, level }; }
  risks(organizationId:string) { return this.prisma.riskRecord.findMany({ where:{organizationId}, include:{ assessments:{orderBy:{createdAt:'desc'},take:1}, treatmentPlans:true }, orderBy:[{residualScore:'desc'},{updatedAt:'desc'}] }); }
  createRisk(organizationId:string,d:CreateRiskDto) { const s=this.score(d.likelihood,d.impact,d.controlEffectiveness??0); return this.prisma.riskRecord.create({data:{organizationId,title:d.title,description:d.description,category:d.category,ownerUserId:d.ownerUserId,likelihood:d.likelihood,impact:d.impact,controlEffectiveness:d.controlEffectiveness??0,inherentScore:s.inherent,residualScore:s.residual,level:s.level as any,reviewAt:d.reviewAt?new Date(d.reviewAt):undefined}}); }
  async assess(organizationId:string,id:string,d:AssessRiskDto,assessorUserId:string) { const risk=await this.prisma.riskRecord.findFirst({where:{id,organizationId}}); if(!risk) throw new NotFoundException('Risk not found'); const s=this.score(d.likelihood,d.impact,d.controlEffectiveness); return this.prisma.$transaction([this.prisma.riskAssessment.create({data:{organizationId,riskId:id,assessorUserId,likelihood:d.likelihood,impact:d.impact,controlEffectiveness:d.controlEffectiveness,inherentScore:s.inherent,residualScore:s.residual,level:s.level as any,rationale:d.rationale}}),this.prisma.riskRecord.update({where:{id},data:{likelihood:d.likelihood,impact:d.impact,controlEffectiveness:d.controlEffectiveness,inherentScore:s.inherent,residualScore:s.residual,level:s.level as any,lastAssessedAt:new Date()}})]); }
  heatmap(organizationId:string){ return this.prisma.riskRecord.groupBy({by:['likelihood','impact'],where:{organizationId,status:'OPEN'},_count:{_all:true}}); }
  tests(organizationId:string){ return this.prisma.controlTest.findMany({where:{organizationId},include:{control:true,executions:true},orderBy:{createdAt:'desc'}}); }
  createTest(organizationId:string,d:CreateControlTestDto){ return this.prisma.controlTest.create({data:{organizationId,controlId:d.controlId,type:d.type as any,scheduledAt:d.scheduledAt?new Date(d.scheduledAt):undefined}}); }
  async completeTest(organizationId:string,id:string,d:CompleteControlTestDto,executorUserId:string){ const t=await this.prisma.controlTest.findFirst({where:{id,organizationId}}); if(!t) throw new NotFoundException('Control test not found'); return this.prisma.$transaction([this.prisma.controlTestExecution.create({data:{organizationId,controlTestId:id,executorUserId,result:d.result as any,notes:d.notes,evidenceIds:d.evidenceIds??[],completedAt:new Date()}}),this.prisma.controlTest.update({where:{id},data:{status:d.result as any,lastExecutedAt:new Date()}})]); }
  findings(organizationId:string){ return this.prisma.complianceFinding.findMany({where:{organizationId},include:{actions:true},orderBy:[{severity:'desc'},{createdAt:'desc'}]}); }
  createFinding(organizationId:string,d:CreateFindingDto){ return this.prisma.complianceFinding.create({data:{organizationId,...d,dueAt:d.dueAt?new Date(d.dueAt):undefined,severity:d.severity as any}}); }
  actions(organizationId:string){ return this.prisma.correctiveAction.findMany({where:{organizationId},include:{tasks:true,finding:true},orderBy:{createdAt:'desc'}}); }
  createAction(organizationId:string,d:CreateCorrectiveActionDto){ return this.prisma.correctiveAction.create({data:{organizationId,...d,dueAt:d.dueAt?new Date(d.dueAt):undefined}}); }
  async dashboard(organizationId:string){ const [risks,critical,findings,failedTests,overdueActions]=await Promise.all([this.prisma.riskRecord.count({where:{organizationId,status:'OPEN'}}),this.prisma.riskRecord.count({where:{organizationId,status:'OPEN',level:'CRITICAL'}}),this.prisma.complianceFinding.count({where:{organizationId,status:{not:'CLOSED'}}}),this.prisma.controlTest.count({where:{organizationId,status:'FAILED'}}),this.prisma.correctiveAction.count({where:{organizationId,status:{not:'COMPLETED'},dueAt:{lt:new Date()}}})]); return {risks,critical,openFindings:findings,failedTests,overdueActions}; }
}
