ALTER TABLE "ProjectTask" ADD COLUMN "position" INTEGER NOT NULL DEFAULT 0;
CREATE TABLE "ProjectTaskComment" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "taskId" TEXT NOT NULL, "authorId" TEXT NOT NULL, "body" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ProjectTaskChecklistItem" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "taskId" TEXT NOT NULL, "title" TEXT NOT NULL, "completed" BOOLEAN NOT NULL DEFAULT false, "position" INTEGER NOT NULL DEFAULT 0, "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ExecutionLabel" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "name" TEXT NOT NULL, "color" TEXT NOT NULL DEFAULT '#64748b', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ProjectTaskLabel" ("organizationId" TEXT NOT NULL, "taskId" TEXT NOT NULL, "labelId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("taskId","labelId"));
CREATE TABLE "ProjectTaskAttachment" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "taskId" TEXT NOT NULL, "uploadedById" TEXT NOT NULL, "fileName" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "sizeBytes" INTEGER NOT NULL, "storageKey" TEXT NOT NULL, "downloadUrl" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ProjectTaskDependency" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "predecessorTaskId" TEXT NOT NULL, "successorTaskId" TEXT NOT NULL, "type" "DependencyType" NOT NULL DEFAULT 'FINISH_TO_START', "lagDays" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "ExecutionLabel_organizationId_name_key" ON "ExecutionLabel"("organizationId","name");
CREATE UNIQUE INDEX "ProjectTaskDependency_predecessorTaskId_successorTaskId_type_key" ON "ProjectTaskDependency"("predecessorTaskId","successorTaskId","type");
ALTER TABLE "ProjectTaskComment" ADD CONSTRAINT "ProjectTaskComment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectTaskComment" ADD CONSTRAINT "ProjectTaskComment_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "ProjectTask"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectTaskComment" ADD CONSTRAINT "ProjectTaskComment_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id");
ALTER TABLE "ProjectTaskChecklistItem" ADD CONSTRAINT "ProjectTaskChecklistItem_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectTaskChecklistItem" ADD CONSTRAINT "ProjectTaskChecklistItem_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "ProjectTask"("id") ON DELETE CASCADE;
ALTER TABLE "ExecutionLabel" ADD CONSTRAINT "ExecutionLabel_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectTaskLabel" ADD CONSTRAINT "ProjectTaskLabel_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectTaskLabel" ADD CONSTRAINT "ProjectTaskLabel_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "ProjectTask"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectTaskLabel" ADD CONSTRAINT "ProjectTaskLabel_labelId_fkey" FOREIGN KEY ("labelId") REFERENCES "ExecutionLabel"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectTaskAttachment" ADD CONSTRAINT "ProjectTaskAttachment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectTaskAttachment" ADD CONSTRAINT "ProjectTaskAttachment_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "ProjectTask"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectTaskAttachment" ADD CONSTRAINT "ProjectTaskAttachment_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "User"("id");
ALTER TABLE "ProjectTaskDependency" ADD CONSTRAINT "ProjectTaskDependency_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectTaskDependency" ADD CONSTRAINT "ProjectTaskDependency_predecessorTaskId_fkey" FOREIGN KEY ("predecessorTaskId") REFERENCES "ProjectTask"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectTaskDependency" ADD CONSTRAINT "ProjectTaskDependency_successorTaskId_fkey" FOREIGN KEY ("successorTaskId") REFERENCES "ProjectTask"("id") ON DELETE CASCADE;
