-- Sprint 12.2 Enterprise Approval Engine
CREATE TYPE "ApprovalStrategy" AS ENUM ('SINGLE','SEQUENTIAL','PARALLEL','MAJORITY','CONSENSUS','FIRST_RESPONSE');
CREATE TYPE "ApprovalRequestStatus" AS ENUM ('DRAFT','PENDING','APPROVED','REJECTED','CHANGES_REQUESTED','CANCELLED','EXPIRED');
CREATE TYPE "ApprovalStageStatus" AS ENUM ('PENDING','ACTIVE','APPROVED','REJECTED','CHANGES_REQUESTED','SKIPPED');
CREATE TYPE "ApprovalAssignmentStatus" AS ENUM ('PENDING','APPROVED','REJECTED','CHANGES_REQUESTED','DELEGATED','CANCELLED');
CREATE TYPE "ApprovalDecisionType" AS ENUM ('APPROVE','REJECT','REQUEST_CHANGES');
CREATE TYPE "ApprovalDelegationType" AS ENUM ('TEMPORARY','PERMANENT','OUT_OF_OFFICE','MANAGER');
CREATE TYPE "ApprovalEscalationType" AS ENUM ('REMINDER','MANAGER','ROLE','USER');
-- Generate exact table DDL with `npm run db:migrate` after Prisma validation.
