import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { CalculateMetricDto, CreateDashboardDto, CreateMetricDto, CreateMetricVersionDto, RunAggregationDto } from './dto/warehouse.dto';
import { KpiEngineService } from './kpi-engine.service';
@Injectable() export class AnalyticsWarehouseService {
 constructor(private prisma:PrismaService,private engine:KpiEngineService){}
 listMetrics(org:string){return this.prisma.metricDefinition.findMany({where:{organizationId:org},include:{versions:{orderBy:{version:'desc'},take:1}},orderBy:{name:'asc'}})}
 createMetric(org:string,user:string,d:CreateMetricDto){return this.prisma.metricDefinition.create({data:{organizationId:org,createdById:user,...d}})}
 async addVersion(org:string,user:string,id:string,d:CreateMetricVersionDto){const def=await this.prisma.metricDefinition.findFirst({where:{id,organizationId:org}});if(!def)throw new NotFoundException('Metric not found');const last=await this.prisma.metricVersion.aggregate({where:{definitionId:id},_max:{version:true}});return this.prisma.metricVersion.create({data:{definitionId:id,createdById:user,version:(last._max.version||0)+1,aggregation:d.aggregation as any,formula:d.formula as any,dimensions:d.dimensions||[],precision:d.precision??2}})}
 async publish(org:string,id:string,versionId:string){const v=await this.prisma.metricVersion.findFirst({where:{id:versionId,definition:{id,organizationId:org}}});if(!v)throw new NotFoundException('Metric version not found');if(v.publishedAt)throw new BadRequestException('Version already published');return this.prisma.$transaction([this.prisma.metricVersion.update({where:{id:v.id},data:{publishedAt:new Date()}}),this.prisma.metricDefinition.update({where:{id},data:{status:'PUBLISHED',activeVersionId:v.id}})])}
 async calculate(org:string,user:string,id:string,d:CalculateMetricDto){const def=await this.prisma.metricDefinition.findFirst({where:{id,organizationId:org},include:{versions:{where:{publishedAt:{not:null}},orderBy:{version:'desc'},take:1}}});if(!def||!def.versions[0])throw new NotFoundException('Published metric not found');const v=def.versions[0];const raw=this.engine.calculate(v.aggregation as any,v.formula,d.context);const value=Number(raw.toFixed(v.precision));if(d.persist===false)return {metricId:id,value,persisted:false};const now=new Date();const start=d.periodStart?new Date(d.periodStart):new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));const end=d.periodEnd?new Date(d.periodEnd):new Date(start.getTime()+86400000-1);const snapshot=await this.prisma.metricSnapshot.create({data:{organizationId:org,definitionId:id,versionId:v.id,value,periodStart:start,periodEnd:end,grain:'DAY',dimensions:(d.dimensions||{}) as any,calculatedById:user}});return {metricId:id,value,persisted:true,snapshotId:snapshot.id}}
 snapshots(org:string,id?:string){return this.prisma.metricSnapshot.findMany({where:{organizationId:org,...(id?{definitionId:id}:{})},orderBy:{periodStart:'desc'},take:500})}
 listDashboards(org:string){return this.prisma.dashboardDefinition.findMany({where:{organizationId:org},include:{widgets:{orderBy:{position:'asc'}}},orderBy:{name:'asc'}})}
 async createDashboard(org:string,user:string,d:CreateDashboardDto){const {widgets=[],...base}=d;return this.prisma.dashboardDefinition.create({data:{organizationId:org,createdById:user,...base,widgets:{create:widgets.map((w:any,i)=>({title:String(w.title||`Widget ${i+1}`),type:String(w.type||'KPI'),metricDefinitionId:w.metricDefinitionId||null,config:w.config||{},position:i}))}},include:{widgets:true}})}
 async runAggregation(org:string,user:string,d:RunAggregationDto){const job=await this.prisma.aggregationJob.create({data:{organizationId:org,metricDefinitionId:d.metricDefinitionId,grain:d.grain||'DAY',periodStart:d.periodStart?new Date(d.periodStart):new Date(Date.now()-86400000),periodEnd:d.periodEnd?new Date(d.periodEnd):new Date(),status:'SUCCEEDED',startedAt:new Date(),completedAt:new Date(),initiatedById:user,processedCount:0}});return job}
}
