import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { createHash } from 'crypto';
import { PrismaService } from '../../prisma/prisma.service';
import { BUSINESS_CONNECTOR_CATALOG, getBusinessConnectorAdapter, ProviderKey } from './provider-adapters';
@Injectable() export class BusinessConnectorsService { constructor(private prisma:PrismaService){}
 catalog(){return BUSINESS_CONNECTOR_CATALOG}
 profiles(org:string){return this.prisma.businessConnectorProfile.findMany({where:{organizationId:org},include:{integrationInstance:{include:{definition:true}},mappings:true},orderBy:{updatedAt:'desc'}})}
 async create(org:string,d:any){const instance=await this.prisma.integrationInstance.findFirst({where:{id:d.integrationInstanceId,organizationId:org}});if(!instance)throw new NotFoundException('Integration instance not found');return this.prisma.businessConnectorProfile.create({data:{organizationId:org,integrationInstanceId:d.integrationInstanceId,provider:d.provider,baseUrl:d.baseUrl,accountKey:d.accountKey,projectKeys:d.projectKeys||[],repositoryNames:d.repositoryNames||[],enabledObjects:d.enabledObjects||[],conflictStrategy:d.conflictStrategy||'MANUAL',settings:d.settings||{}}})}
 async mappings(org:string,id:string,d:any){await this.require(org,id);await this.prisma.businessConnectorMapping.deleteMany({where:{organizationId:org,profileId:id}});return this.prisma.businessConnectorMapping.createMany({data:(d.mappings||[]).map((m:any)=>({organizationId:org,profileId:id,objectType:m.objectType,direction:m.direction||'INBOUND',sourceField:m.sourceField,targetField:m.targetField,transform:m.transform,required:!!m.required}))})}
 async preview(org:string,id:string,d:any){const profile=await this.require(org,id);const adapter=getBusinessConnectorAdapter(profile.provider as ProviderKey);const items=(d.items||[]).map((x:any)=>adapter.normalize(x));return {provider:profile.provider,dryRun:true,received:items.length,items:items.map((x:any)=>({...x,raw:undefined})),warnings:items.filter((x:any)=>!x.externalId||!x.title).map((x:any)=>({externalId:x.externalId,message:'External id and title are required'}))}}
 async sync(org:string,id:string,d:any){const profile=await this.require(org,id);const adapter=getBusinessConnectorAdapter(profile.provider as ProviderKey);const execution=await this.prisma.integrationExecution.create({data:{organizationId:org,integrationInstanceId:profile.integrationInstanceId,type:'SYNC',status:'RUNNING',attempt:1,startedAt:new Date(),requestSummary:{provider:profile.provider,count:(d.items||[]).length}}});let succeeded=0,failed=0;for(const raw of d.items||[]){try{const item=adapter.normalize(raw);if(!item.externalId||!item.title)throw new Error('External id and title are required');const checksum=createHash('sha256').update(JSON.stringify(item.raw||raw)).digest('hex');await this.prisma.connectorSyncItem.upsert({where:{profileId_externalType_externalId:{profileId:id,externalType:item.objectType as any,externalId:item.externalId}},update:{executionId:execution.id,status:'SUCCEEDED',checksum,sourceUpdatedAt:item.updatedAt?new Date(item.updatedAt):undefined,payloadSummary:{title:item.title,status:item.status,url:item.url}},create:{organizationId:org,profileId:id,executionId:execution.id,externalId:item.externalId,externalType:item.objectType as any,status:'SUCCEEDED',checksum,sourceUpdatedAt:item.updatedAt?new Date(item.updatedAt):undefined,payloadSummary:{title:item.title,status:item.status,url:item.url}}});succeeded++}catch(e:any){failed++}}
 await this.prisma.integrationExecution.update({where:{id:execution.id},data:{status:failed?'FAILED':'SUCCEEDED',completedAt:new Date(),responseSummary:{succeeded,failed},errorMessage:failed?`${failed} item(s) failed normalization`:undefined}});await this.prisma.integrationInstance.update({where:{id:profile.integrationInstanceId},data:{lastSyncAt:new Date(),status:failed?'ERROR':'ACTIVE'}});return {executionId:execution.id,succeeded,failed}}
 conflicts(org:string,id:string){return this.prisma.connectorConflict.findMany({where:{organizationId:org,profileId:id},orderBy:{createdAt:'desc'}})}
 async resolve(org:string,id:string,conflictId:string,d:any){await this.require(org,id);const conflict=await this.prisma.connectorConflict.findFirst({where:{id:conflictId,organizationId:org,profileId:id}});if(!conflict)throw new NotFoundException('Conflict not found');return this.prisma.connectorConflict.update({where:{id:conflictId},data:{resolution:d.resolution,resolvedByUserId:d.userId,resolvedAt:new Date()}})}
 private async require(org:string,id:string){const row=await this.prisma.businessConnectorProfile.findFirst({where:{id,organizationId:org},include:{integrationInstance:true}});if(!row)throw new NotFoundException('Business connector profile not found');return row}
}
