export type ProviderKey='JIRA'|'AZURE_DEVOPS'|'GITHUB'|'GITLAB'|'SERVICENOW'|'ASANA'|'MONDAY'|'TRELLO';
export interface NormalizedConnectorItem { externalId:string; objectType:string; title:string; description?:string; status?:string; assigneeEmail?:string; updatedAt?:string; url?:string; labels?:string[]; raw?:Record<string,unknown>; }
export interface BusinessConnectorAdapter { provider:ProviderKey; capabilities:string[]; normalize(input:any):NormalizedConnectorItem; buildOutbound(item:Record<string,unknown>):Record<string,unknown>; }
const text=(v:any)=>v==null?undefined:String(v);
const adapters:Record<ProviderKey,BusinessConnectorAdapter>={
 JIRA:{provider:'JIRA',capabilities:['ISSUE','EPIC','STORY','BUG','PROJECT'],normalize:x=>({externalId:text(x.id||x.key)!,objectType:text(x.fields?.issuetype?.name||'ISSUE')!.toUpperCase(),title:text(x.fields?.summary||x.name)!,description:text(x.fields?.description),status:text(x.fields?.status?.name),assigneeEmail:text(x.fields?.assignee?.emailAddress),updatedAt:text(x.fields?.updated),url:text(x.self),labels:x.fields?.labels||[],raw:x}),buildOutbound:i=>({fields:{summary:i.title,description:i.description}})},
 AZURE_DEVOPS:{provider:'AZURE_DEVOPS',capabilities:['WORK_ITEM','EPIC','STORY','BUG','PROJECT'],normalize:x=>({externalId:text(x.id)!,objectType:text(x.fields?.['System.WorkItemType']||'WORK_ITEM')!.toUpperCase().replace(/ /g,'_'),title:text(x.fields?.['System.Title'])!,status:text(x.fields?.['System.State']),assigneeEmail:text(x.fields?.['System.AssignedTo']?.uniqueName),updatedAt:text(x.fields?.['System.ChangedDate']),url:text(x.url),raw:x}),buildOutbound:i=>({'System.Title':i.title,'System.Description':i.description})},
 GITHUB:{provider:'GITHUB',capabilities:['REPOSITORY','ISSUE','PULL_REQUEST'],normalize:x=>({externalId:text(x.id||x.node_id)!,objectType:x.pull_request?'PULL_REQUEST':'ISSUE',title:text(x.title||x.name)!,description:text(x.body||x.description),status:text(x.state),assigneeEmail:text(x.assignee?.email),updatedAt:text(x.updated_at),url:text(x.html_url),labels:(x.labels||[]).map((l:any)=>text(l.name||l)),raw:x}),buildOutbound:i=>({title:i.title,body:i.description})},
 GITLAB:{provider:'GITLAB',capabilities:['PROJECT','ISSUE','PULL_REQUEST'],normalize:x=>({externalId:text(x.id)!,objectType:x.source_branch?'PULL_REQUEST':'ISSUE',title:text(x.title||x.name)!,description:text(x.description),status:text(x.state),assigneeEmail:text(x.assignee?.email),updatedAt:text(x.updated_at),url:text(x.web_url),labels:x.labels||[],raw:x}),buildOutbound:i=>({title:i.title,description:i.description})},
 SERVICENOW:{provider:'SERVICENOW',capabilities:['INCIDENT','CHANGE_REQUEST','TASK'],normalize:x=>({externalId:text(x.sys_id||x.number)!,objectType:text(x.sys_class_name||'INCIDENT')!.toUpperCase(),title:text(x.short_description)!,description:text(x.description),status:text(x.state),assigneeEmail:text(x.assigned_to?.email||x.assigned_to),updatedAt:text(x.sys_updated_on),raw:x}),buildOutbound:i=>({short_description:i.title,description:i.description})},
 ASANA:{provider:'ASANA',capabilities:['PROJECT','TASK'],normalize:x=>({externalId:text(x.gid)!,objectType:x.resource_type==='project'?'PROJECT':'TASK',title:text(x.name)!,description:text(x.notes),status:x.completed?'completed':'open',assigneeEmail:text(x.assignee?.email),updatedAt:text(x.modified_at),url:text(x.permalink_url),raw:x}),buildOutbound:i=>({name:i.title,notes:i.description})},
 MONDAY:{provider:'MONDAY',capabilities:['BOARD','TASK'],normalize:x=>({externalId:text(x.id)!,objectType:x.board?'TASK':'BOARD',title:text(x.name)!,status:text(x.state),updatedAt:text(x.updated_at),url:text(x.url),raw:x}),buildOutbound:i=>({item_name:i.title,column_values:i.fields||{}})},
 TRELLO:{provider:'TRELLO',capabilities:['BOARD','TASK'],normalize:x=>({externalId:text(x.id)!,objectType:x.idBoard&&x.idList?'TASK':'BOARD',title:text(x.name)!,description:text(x.desc),status:x.closed?'closed':'open',updatedAt:text(x.dateLastActivity),url:text(x.url),labels:(x.labels||[]).map((l:any)=>text(l.name)),raw:x}),buildOutbound:i=>({name:i.title,desc:i.description})}
};
export const getBusinessConnectorAdapter=(provider:ProviderKey)=>adapters[provider];
export const BUSINESS_CONNECTOR_CATALOG=Object.values(adapters).map(a=>({provider:a.provider,capabilities:a.capabilities,supports:['pull','push','preview','webhook','conflict-detection']}));
