'use client';
import Link from 'next/link';
import { use, useEffect, useState } from 'react';
import { AdminShell } from '../../../../components/admin-shell';
import { api } from '../../../../lib/api';
const label=(v:string)=>v.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function ObjectiveExecution({params}:{params:Promise<{id:string}>}){const {id}=use(params);const [data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{api(`/execution/objectives/${id}/traceability`).then(setData).catch(e=>setError(e.message))},[id]);if(!data)return <AdminShell title="Objective execution" subtitle="Loading traceability…">{error&&<p className="formError">{error}</p>}</AdminShell>;return <AdminShell title={data.objective.title} subtitle={`${data.objective.cycle.name} · Strategy-to-execution traceability`} action={<Link className="buttonLink secondary" href={`/okrs/${id}`}>Back to objective</Link>}>
<section className="metrics executionMetrics"><article><p>Objective progress</p><strong>{Math.round(data.objective.progress)}%</strong><span>{label(data.objective.status)}</span></article><article><p>Direct delivery contribution</p><strong>{Math.round(data.rollup.directContribution)}%</strong><span>Weighted project delivery</span></article><article><p>Linked projects</p><strong>{data.rollup.linkedProjects}</strong><span>Across objective and key results</span></article><article><p>Exposed projects</p><strong>{data.rollup.exposedProjects}</strong><span>At risk or off track</span></article></section>
<section className="panel"><h2>Projects directly supporting this objective</h2>{data.directProjects.map((x:any)=><div className="workItem" key={x.id}><span><Link href={`/execution/projects/${x.project.id}`}><strong>{x.project.key} · {x.project.name}</strong></Link><small>{label(x.contributionType)} · {Number(x.weight)}% weight · {Math.round(x.effectiveContribution)}% effective contribution</small></span><i className={`status health-${x.project.health.toLowerCase()}`}>{label(x.project.health)}</i></div>)}{!data.directProjects.length&&<p className="muted">No projects directly linked to this objective.</p>}</section>
<section className="panel"><h2>Key-result delivery</h2>{data.keyResults.map((kr:any)=><article key={kr.id} className="traceGroup"><div className="panelHead"><div><h3>{kr.title}</h3><p>{Math.round(kr.progress)}% KR progress · {Math.round(kr.deliveryContribution)}% weighted delivery contribution</p></div></div>{kr.projects.map((x:any)=><div className="workItem" key={x.id}><span><Link href={`/execution/projects/${x.project.id}`}><strong>{x.project.key} · {x.project.name}</strong></Link><small>{label(x.contributionType)} · {Number(x.weight)}% weight · {Math.round(x.effectiveContribution)}% effective</small></span><i className={`status health-${x.project.health.toLowerCase()}`}>{label(x.project.health)}</i></div>)}{!kr.projects.length&&<p className="muted">No projects linked to this key result.</p>}</article>)}</section>
</AdminShell>}
