CREATE TYPE "EnterpriseAnnouncementStatus" AS ENUM ('DRAFT','SCHEDULED','PUBLISHED','ARCHIVED');
CREATE TYPE "EnterpriseAnnouncementSeverity" AS ENUM ('INFORMATION','SUCCESS','WARNING','CRITICAL');
CREATE TYPE "CommunicationCampaignStatus" AS ENUM ('DRAFT','SCHEDULED','SENDING','SENT','CANCELLED');
CREATE TABLE "EnterpriseAnnouncement" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"title" TEXT NOT NULL,"content" TEXT NOT NULL,"severity" "EnterpriseAnnouncementSeverity" NOT NULL DEFAULT 'INFORMATION',"status" "EnterpriseAnnouncementStatus" NOT NULL DEFAULT 'DRAFT',"audienceUserIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],"audienceDepartmentIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],"requiresAcknowledgement" BOOLEAN NOT NULL DEFAULT false,"createdByUserId" TEXT NOT NULL,"publishAt" TIMESTAMP(3),"publishedAt" TIMESTAMP(3),"expiresAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AnnouncementAcknowledgement" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"announcementId" TEXT NOT NULL,"userId" TEXT NOT NULL,"note" TEXT,"acknowledgedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AnnouncementAcknowledgement_announcementId_fkey" FOREIGN KEY ("announcementId") REFERENCES "EnterpriseAnnouncement"("id") ON DELETE CASCADE);
CREATE UNIQUE INDEX "AnnouncementAcknowledgement_announcementId_userId_key" ON "AnnouncementAcknowledgement"("announcementId","userId");
CREATE TABLE "CommunicationCampaign" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"subject" TEXT NOT NULL,"content" TEXT NOT NULL,"channels" TEXT[] NOT NULL,"audienceUserIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],"audienceDepartmentIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],"status" "CommunicationCampaignStatus" NOT NULL DEFAULT 'DRAFT',"createdByUserId" TEXT NOT NULL,"scheduledAt" TIMESTAMP(3),"sentAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DigitalWorkplacePreference" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"showAnnouncements" BOOLEAN NOT NULL DEFAULT true,"showActivity" BOOLEAN NOT NULL DEFAULT true,"showDocuments" BOOLEAN NOT NULL DEFAULT true,"showWorkspaces" BOOLEAN NOT NULL DEFAULT true,"feedPageSize" INTEGER NOT NULL DEFAULT 20,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "DigitalWorkplacePreference_organizationId_userId_key" ON "DigitalWorkplacePreference"("organizationId","userId");
