'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { AdminShell } from '../../../components/admin-shell';
import { api } from '../../../lib/api';
type Summary={headline:string;capacityHours:number;allocatedHours:number;utilizationPercent:number;forecastCost:number;overallocatedResources:number;benchResources:number;teamsAtRisk:number;skillsAtRisk:number};
type Resource={id:string;displayName:string;jobTitle?:string;teams:string[];capacityHours:number;allocatedHours:number;remainingHours:number;utilizationPercent:number;workloadState:string;forecastCost:number};
type Team={name:string;resources:number;capacityHours:number;allocatedHours:number;utilizationPercent:number;forecastCost:number;overallocated:number;bench:number};
type Skill={id:string;name:string;category?:string;resources:number;advancedResources:number;verifiedResources:number;availableResources:number};
type Hiring={skillId:string;skillName:string;qualifiedResources:number;availableQualifiedResources:number;urgency:string;reason:string};
type Analytics={from:string;to:string;currency:string;summary:Summary;resources:Resource[];teams:Team[];skills:Skill[];hiringSignals:Hiring[];bottlenecks:Resource[];bench:Resource[]};
const date=(d:Date)=>d.toISOString().slice(0,10);
export default function WorkforceAnalyticsPage(){const now=new Date(),future=new Date(now);future.setDate(future.getDate()+84);const[from,setFrom]=useState(date(now)),[to,setTo]=useState(date(future)),[data,setData]=useState<Analytics|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const available=useMemo(()=>Math.round((data?.summary.capacityHours||0)-(data?.summary.allocatedHours||0)),[data]);
async function load(){setBusy(true);try{setError('');setData(await api<Analytics>(`/resource-management/analytics/workforce?from=${from}&to=${to}`))}catch(e){setError(e instanceof Error?e.message:'Unable to load workforce analytics')}finally{setBusy(false)}}useEffect(()=>{load()},[]);
return <AdminShell title="Executive workforce analytics" subtitle="Understand utilization, cost, capability concentration, bottlenecks, bench, and hiring signals across the workforce." action={<Link className="buttonLink" href="/resources">Back to resources</Link>}>
{error&&<div className="formError">{error}</div>}<section className="panel"><div className="executionInlineForm"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={load} disabled={busy}>{busy?'Analyzing…':'Refresh analytics'}</button></div></section>
<section className="metrics executionMetrics"><article><p>Forecast utilization</p><strong>{Math.round(data?.summary.utilizationPercent||0)}%</strong><span>{Math.round(data?.summary.allocatedHours||0)} / {Math.round(data?.summary.capacityHours||0)} hours</span></article><article><p>Workforce cost</p><strong>{Math.round(data?.summary.forecastCost||0).toLocaleString()}</strong><span>{data?.currency||'SAR'} selected-horizon forecast</span></article><article><p>Bottlenecks</p><strong>{data?.summary.overallocatedResources??'—'}</strong><span>{data?.summary.teamsAtRisk||0} teams above capacity</span></article><article><p>Available capacity</p><strong>{available}h</strong><span>{data?.summary.benchResources||0} bench resources</span></article></section>
<section className="panel tablePanel"><div className="panelHead"><div><h2>Executive attention</h2><p>{data?.summary.headline||'Workforce analytics are loading.'}</p></div></div><div className="executionTable"><div className="executionRow executionHead"><span>Resource</span><span>Team</span><span>Demand</span><span>Capacity</span><span>Utilization</span><span>Forecast cost</span></div>{data?.bottlenecks.length?data.bottlenecks.map(r=><div className="executionRow" key={r.id}><span><strong>{r.displayName}</strong><small>{r.jobTitle||'Role not set'}</small></span><span>{r.teams.join(', ')||'Unassigned'}</span><span>{Math.round(r.allocatedHours)}h</span><span>{Math.round(r.capacityHours)}h</span><span><strong className="negative">{Math.round(r.utilizationPercent)}%</strong></span><span>{Math.round(r.forecastCost).toLocaleString()} {data.currency}</span></div>):<p className="emptyState">No resource bottlenecks in the selected horizon.</p>}</div></section>
<section className="panel tablePanel"><div className="panelHead"><div><h2>Team workload</h2><p>Capacity, demand, bench, cost, and overload by resource team.</p></div></div><div className="executionTable"><div className="executionRow executionHead"><span>Team</span><span>Resources</span><span>Utilization</span><span>Demand</span><span>Bench</span><span>Forecast cost</span></div>{data?.teams.map(t=><div className="executionRow" key={t.name}><span><strong>{t.name}</strong></span><span>{t.resources}</span><span><strong className={t.utilizationPercent>100?'negative':''}>{Math.round(t.utilizationPercent)}%</strong></span><span>{Math.round(t.allocatedHours)} / {Math.round(t.capacityHours)}h</span><span>{t.bench}</span><span>{Math.round(t.forecastCost).toLocaleString()} {data.currency}</span></div>)}</div></section>
<section className="cardGrid executionCards"><article className="panel"><h2>Capability concentration</h2><p>Skills with limited advanced or expert coverage.</p>{data?.skills.filter(s=>s.advancedResources<=1).slice(0,8).map(s=><div className="riskLine" key={s.id}><span><strong>{s.name}</strong><small>{s.category||'Uncategorized'}</small></span><span>{s.advancedResources} advanced · {s.verifiedResources} verified</span></div>)}</article><article className="panel"><h2>Hiring signals</h2><p>Capability risks combining scarce skills and workforce demand.</p>{data?.hiringSignals.slice(0,8).map(s=><div className="riskLine" key={s.skillId}><span><strong>{s.skillName}</strong><small>{s.reason}</small></span><i className="status">{s.urgency}</i></div>)}</article><article className="panel"><h2>Bench opportunities</h2><p>Resources below 25% forecast utilization.</p>{data?.bench.slice(0,8).map(r=><div className="riskLine" key={r.id}><span><strong>{r.displayName}</strong><small>{r.jobTitle||r.teams.join(', ')||'Resource'}</small></span><span>{Math.round(r.utilizationPercent)}% · {Math.round(r.remainingHours)}h free</span></div>)}</article></section>
</AdminShell>}
