import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { CreateDecisionPolicyDto, CreateDecisionPolicyVersionDto, DecideRecommendationDto, GenerateRecommendationDto, RecommendationDisposition, SimulateDecisionDto } from './dto/decision-intelligence.dto';
import { DecisionEngineService } from './decision-engine.service';
@Injectable()
export class DecisionIntelligenceService {
 constructor(private prisma:PrismaService,private engine:DecisionEngineService){}
 listPolicies(org:string){return this.prisma.decisionPolicy.findMany({where:{organizationId:org},include:{versions:{orderBy:{version:'desc'},take:1}},orderBy:{name:'asc'}})}
 createPolicy(org:string,user:string,d:CreateDecisionPolicyDto){return this.prisma.decisionPolicy.create({data:{organizationId:org,createdById:user,...d}})}
 async addVersion(org:string,user:string,id:string,d:CreateDecisionPolicyVersionDto){const policy=await this.prisma.decisionPolicy.findFirst({where:{id,organizationId:org}});if(!policy)throw new NotFoundException('Decision policy not found');const last=await this.prisma.decisionPolicyVersion.aggregate({where:{policyId:id},_max:{version:true}});return this.prisma.decisionPolicyVersion.create({data:{policyId:id,createdById:user,version:(last._max.version||0)+1,configuration:d.configuration as any,minimumConfidence:d.minimumConfidence??.6}})}
 async publish(org:string,id:string,versionId:string){const v=await this.prisma.decisionPolicyVersion.findFirst({where:{id:versionId,policy:{id,organizationId:org}}});if(!v)throw new NotFoundException('Decision policy version not found');if(v.publishedAt)throw new BadRequestException('Version already published');return this.prisma.$transaction([this.prisma.decisionPolicyVersion.update({where:{id:v.id},data:{publishedAt:new Date()}}),this.prisma.decisionPolicy.update({where:{id},data:{status:'PUBLISHED',activeVersionId:v.id}})])}
 async generate(org:string,user:string,id:string,d:GenerateRecommendationDto){const policy=await this.prisma.decisionPolicy.findFirst({where:{id,organizationId:org,status:'PUBLISHED'},include:{versions:{where:{publishedAt:{not:null}},orderBy:{version:'desc'},take:1}}});if(!policy||!policy.versions[0])throw new NotFoundException('Published decision policy not found');const v=policy.versions[0];const confidence=this.engine.validateConfidence(d.confidence,v.minimumConfidence);if(d.predictionResultId){const result=await this.prisma.predictionResult.findFirst({where:{id:d.predictionResultId,organizationId:org}});if(!result)throw new NotFoundException('Prediction result not found');}
 return this.prisma.decisionRecommendation.create({data:{organizationId:org,policyId:id,versionId:v.id,predictionResultId:d.predictionResultId,title:d.title,summary:d.summary,recommendationType:policy.recommendationType,priority:d.priority??'MEDIUM',entityType:d.entityType,entityId:d.entityId,confidence,evidence:d.evidence as any,expectedImpact:d.expectedImpact as any,proposedActions:d.proposedActions as any,alternatives:(d.alternatives||[]) as any,rationale:(d.rationale||{}) as any,expiresAt:d.expiresAt?new Date(d.expiresAt):null,createdById:user}})}
 listRecommendations(org:string,status?:string,type?:string){return this.prisma.decisionRecommendation.findMany({where:{organizationId:org,...(status?{status:status as any}:{}),...(type?{recommendationType:type as any}:{})},include:{policy:{select:{key:true,name:true}},decisions:{orderBy:{decidedAt:'desc'},take:1}},orderBy:[{priority:'desc'},{createdAt:'desc'}],take:500})}
 async detail(org:string,id:string){const item=await this.prisma.decisionRecommendation.findFirst({where:{id,organizationId:org},include:{policy:true,version:true,decisions:{orderBy:{decidedAt:'desc'}},simulations:{orderBy:{createdAt:'desc'}}}});if(!item)throw new NotFoundException('Recommendation not found');return item;}
 async decide(org:string,user:string,id:string,d:DecideRecommendationDto){const item=await this.prisma.decisionRecommendation.findFirst({where:{id,organizationId:org}});if(!item)throw new NotFoundException('Recommendation not found');const statusMap={ACCEPT:'ACCEPTED',REJECT:'REJECTED',DEFER:'DEFERRED',MARK_APPLIED:'APPLIED'} as const;return this.prisma.$transaction(async tx=>{const decision=await tx.recommendationDecision.create({data:{recommendationId:id,disposition:d.disposition,comment:d.comment,decidedById:user}});await tx.decisionRecommendation.update({where:{id},data:{status:statusMap[d.disposition] as any}});return decision;});}
 async simulate(org:string,user:string,policyId:string,recommendationId:string|undefined,d:SimulateDecisionDto){const policy=await this.prisma.decisionPolicy.findFirst({where:{id:policyId,organizationId:org,status:'PUBLISHED'},include:{versions:{where:{publishedAt:{not:null}},orderBy:{version:'desc'},take:1}}});if(!policy||!policy.versions[0])throw new NotFoundException('Published decision policy not found');if(recommendationId){const r=await this.prisma.decisionRecommendation.findFirst({where:{id:recommendationId,organizationId:org,policyId}});if(!r)throw new NotFoundException('Recommendation not found');}const result=this.engine.simulate(d.baseline,d.changes,d.confidence);return this.prisma.decisionSimulation.create({data:{organizationId:org,policyId,versionId:policy.versions[0].id,recommendationId,scenarioName:d.scenarioName,baseline:d.baseline as any,changes:d.changes as any,projectedOutcome:result.projectedOutcome as any,confidence:result.confidence,explanation:result.explanation as any,createdById:user}})}
 dashboard(org:string){return this.prisma.decisionRecommendation.groupBy({by:['status'],where:{organizationId:org},_count:{_all:true}})}
}
