'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { AdminShell } from '../../../components/admin-shell';
import { api } from '../../../lib/api';
type Skill={id:string;name:string};
type Candidate={resourceId:string;displayName:string;jobTitle?:string;matchScore:number;utilizationPercent:number;availableHours:number;matchedSkills:{name:string;proficiency:string;verified:boolean}[]};
export default function ResourceAssistantPage(){
 const[skills,setSkills]=useState<Skill[]>([]),[selected,setSelected]=useState<string[]>([]),[hours,setHours]=useState('20'),[context,setContext]=useState(''),[tab,setTab]=useState<'staffing'|'gaps'|'conflicts'|'summary'>('staffing'),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{api<Skill[]>('/resource-management/skills').then(setSkills).catch(e=>setError(e.message))},[]);
 const toggle=(id:string)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 async function run(e:FormEvent){e.preventDefault();setBusy(true);setError('');setResult(null);try{
  const today=new Date(),later=new Date(today);later.setDate(later.getDate()+56);
  const route=tab==='staffing'?'/ai/resources/staffing-recommendations':tab==='gaps'?'/ai/resources/skill-gaps':tab==='conflicts'?'/ai/resources/conflicts/resolve':'/ai/resources/workforce-summary';
  const body=tab==='staffing'?{skillIds:selected,requiredHoursPerWeek:Number(hours),context}:tab==='gaps'?{skillIds:selected,forecastDemandHours:Number(hours)*8}:tab==='conflicts'?{from:today.toISOString().slice(0,10),to:later.toISOString().slice(0,10)}:{detail:'standard'};
  setResult(await api(route,{method:'POST',body:JSON.stringify(body)}));
 }catch(e){setError(e instanceof Error?e.message:'Unable to generate recommendation')}finally{setBusy(false)}}
 return <AdminShell title="AI Resource Planner" subtitle="Use explainable skill, capacity, and allocation evidence to support staffing and workforce decisions." action={<Link className="buttonLink" href="/resources">Back to resources</Link>}>
  {error&&<div className="formError">{error}</div>}
  <section className="panel"><div className="enterpriseTabs"><button className={tab==='staffing'?'active secondary':'secondary'} onClick={()=>{setTab('staffing');setResult(null)}}>Staffing</button><button className={tab==='gaps'?'active secondary':'secondary'} onClick={()=>{setTab('gaps');setResult(null)}}>Skill gaps</button><button className={tab==='conflicts'?'active secondary':'secondary'} onClick={()=>{setTab('conflicts');setResult(null)}}>Conflict resolution</button><button className={tab==='summary'?'active secondary':'secondary'} onClick={()=>{setTab('summary');setResult(null)}}>Workforce summary</button></div>
  <form onSubmit={run} className="assistantForm"><h2>{tab==='staffing'?'Find the best-fit resources':tab==='gaps'?'Assess capability gaps':tab==='conflicts'?'Recommend workload rebalancing':'Draft an executive workforce update'}</h2>{['staffing','gaps'].includes(tab)&&<><p>Select the capabilities required for the work.</p><div className="chipList">{skills.map(s=><button type="button" key={s.id} className={selected.includes(s.id)?'chip selected':'chip'} onClick={()=>toggle(s.id)}>{s.name}</button>)}</div><label>{tab==='staffing'?'Required hours per week':'Forecast demand hours per week'}<input type="number" min="1" value={hours} onChange={e=>setHours(e.target.value)}/></label></>}{tab==='staffing'&&<label>Planning context<textarea value={context} onChange={e=>setContext(e.target.value)} placeholder="Critical milestone, delivery constraints, location, or other decision context"/></label>}<button disabled={busy||(['staffing','gaps'].includes(tab)&&!selected.length)}>{busy?'Analyzing…':'Generate recommendation'}</button></form></section>
  {result&&<section className="panel"><div className="panelHead"><div><h2>{result.headline||result.recommendation||result.rationale||'AI recommendation'}</h2><p>Generation {result.generationId}</p></div></div>{result.capacitySummary&&<p>{result.capacitySummary}</p>}{result.candidates&&<div className="executionTable"><div className="executionRow executionHead"><span>Candidate</span><span>Match</span><span>Availability</span><span>Utilization</span><span>Evidence</span><span>Decision</span></div>{result.candidates.map((c:Candidate)=><div className="executionRow" key={c.resourceId}><span><strong>{c.displayName}</strong><small>{c.jobTitle||'Role not set'}</small></span><span><strong>{c.matchScore}%</strong></span><span>{Math.round(c.availableHours)}h</span><span>{Math.round(c.utilizationPercent)}%</span><span>{c.matchedSkills?.map(s=>`${s.name} (${s.proficiency})`).join(', ')||'No matched skills'}</span><span>Review</span></div>)}</div>}{result.gaps&&<div className="cardGrid executionCards">{result.gaps.map((g:any)=><article className="panel entityCard" key={g.skillId}><h3>{g.skillName}</h3><strong className={g.gap?'negative':''}>{g.gap?'Coverage gap':'Covered'}</strong><p>{g.availableResources} available / {g.qualifiedResources} qualified</p></article>)}</div>}{result.rebalancingActions&&<div><h3>Recommended actions</h3>{result.rebalancingActions.map((a:any,i:number)=><article className="insight" key={i}><strong>{a.action}</strong><p>{a.evidence}</p></article>)}</div>}{result.strengths&&<div><h3>Workforce strengths</h3><ul>{result.strengths.map((x:string)=><li key={x}>{x}</li>)}</ul></div>}{result.exposures&&<div><h3>Exposures</h3><ul>{result.exposures.map((x:string)=><li key={x}>{x}</li>)}</ul></div>}{result.nextActions&&<div><h3>Next actions</h3><ul>{result.nextActions.map((x:string)=><li key={x}>{x}</li>)}</ul></div>}<p className="muted">Recommendations are advisory. Assignments and allocation changes require explicit approval.</p></section>}
 </AdminShell>
}
