'use client';
import { useEffect,useState } from 'react';
import { AdminShell } from '../../components/admin-shell';
import { api,API_URL } from '../../lib/api';

type Trend={cycle:{name:string};points:Array<{date:string;progress:number}>};
type Breakdown={groupBy:string;groups:Array<{label:string;objectives:number;averageProgress:number;atRisk:number;completionRate:number}>};
type Health={owners:Array<{owner:string;keyResults:number;current:number;stale:number;never:number;coverage:number}>};
function TrendChart({points}:{points:Trend['points']}){const w=760,h=220,p=28;const coords=points.map((x,i)=>({x:p+(i*(w-2*p)/Math.max(points.length-1,1)),y:h-p-(x.progress/100)*(h-2*p)}));const path=coords.map((c,i)=>`${i?'L':'M'} ${c.x} ${c.y}`).join(' ');return <svg className="trendChart" viewBox={`0 0 ${w} ${h}`} role="img"><line x1={p} x2={w-p} y1={h-p} y2={h-p}/><line x1={p} x2={p} y1={p} y2={h-p}/><path d={path}/>{coords.map((c,i)=><circle key={i} cx={c.x} cy={c.y} r="4"/> )}</svg>}
export default function ReportsPage(){const [trend,setTrend]=useState<Trend|null>(null),[breakdown,setBreakdown]=useState<Breakdown|null>(null),[health,setHealth]=useState<Health|null>(null),[groupBy,setGroupBy]=useState('scope'),[error,setError]=useState('');const load=(g=groupBy)=>Promise.all([api<Trend>('/analytics/progress-trend'),api<Breakdown>(`/analytics/breakdown?groupBy=${g}`),api<Health>('/analytics/check-in-health')]).then(([a,b,c])=>{setTrend(a);setBreakdown(b);setHealth(c)}).catch(e=>setError(e.message));useEffect(()=>{load()},[]);const download=async()=>{const token=localStorage.getItem('achievex_access_token');const r=await fetch(`${API_URL}/api/v1/analytics/export.csv`,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!r.ok)throw new Error('Export failed');const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='achievex-okr-report.csv';a.click();URL.revokeObjectURL(url)};return <AdminShell title="Reports & analytics" subtitle="Trends, execution health, adoption, and export-ready OKR reporting" action={<button onClick={()=>download().catch(e=>setError(e.message))}>Export CSV</button>}>{error&&<div className="formError">{error}</div>}{trend&&<div className="grid reportGrid"><article className="panel"><div className="panelHead"><div><h2>Progress trend</h2><p>{trend.cycle.name} weekly measured progress</p></div></div><TrendChart points={trend.points}/><div className="chartLabels"><span>{trend.points[0]?.date}</span><span>{trend.points.at(-1)?.date}</span></div></article><article className="panel"><div className="panelHead"><div><h2>Latest progress</h2><p>Measured from submitted check-ins</p></div></div><div className="bigMetric"><strong>{trend.points.at(-1)?.progress??0}%</strong><span>average KR progress</span></div></article></div>}
{breakdown&&<article className="panel"><div className="panelHead"><div><h2>Performance breakdown</h2><p>Compare execution across organizational dimensions</p></div><select value={groupBy} onChange={e=>{setGroupBy(e.target.value);load(e.target.value)}}><option value="scope">Scope</option><option value="department">Department</option><option value="team">Team</option><option value="owner">Owner</option></select></div><div className="reportTable"><div className="reportRow reportHead"><span>Group</span><span>Objectives</span><span>Progress</span><span>At risk</span><span>Completion</span></div>{breakdown.groups.map(g=><div className="reportRow" key={g.label}><strong>{g.label}</strong><span>{g.objectives}</span><span>{g.averageProgress}%</span><span>{g.atRisk}</span><span>{g.completionRate}%</span></div>)}</div></article>}
{health&&<article className="panel"><div className="panelHead"><div><h2>Check-in health</h2><p>Accountability and update freshness by owner</p></div></div><div className="reportTable healthTable"><div className="reportRow reportHead"><span>Owner</span><span>Key results</span><span>Current</span><span>Stale</span><span>Never</span><span>Coverage</span></div>{health.owners.map(o=><div className="reportRow" key={o.owner}><strong>{o.owner}</strong><span>{o.keyResults}</span><span>{o.current}</span><span>{o.stale}</span><span>{o.never}</span><span>{o.coverage}%</span></div>)}</div></article>}</AdminShell>}
