ALTER TYPE "NotificationChannel" ADD VALUE IF NOT EXISTS 'SLACK';
ALTER TYPE "NotificationChannel" ADD VALUE IF NOT EXISTS 'TEAMS';
CREATE TYPE "SlaPolicyStatus" AS ENUM ('DRAFT','ACTIVE','ARCHIVED');
CREATE TYPE "SlaTargetType" AS ENUM ('RESPONSE','COMPLETION');
CREATE TYPE "SlaClockStatus" AS ENUM ('RUNNING','PAUSED','MET','BREACHED','CANCELLED');
CREATE TYPE "SlaEscalationStatus" AS ENUM ('PENDING','TRIGGERED','CANCELLED');
CREATE TABLE "NotificationTemplate" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"channel" "NotificationChannel" NOT NULL,"subjectTemplate" TEXT,"bodyTemplate" TEXT NOT NULL,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "NotificationTemplate_organizationId_key_channel_key" ON "NotificationTemplate"("organizationId","key","channel");
ALTER TABLE "NotificationTemplate" ADD CONSTRAINT "NotificationTemplate_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
CREATE TABLE "NotificationRoute" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"eventName" TEXT NOT NULL,"channels" "NotificationChannel"[] NOT NULL,"recipientExpression" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "NotificationRoute_organizationId_eventName_key" ON "NotificationRoute"("organizationId","eventName");
ALTER TABLE "NotificationRoute" ADD CONSTRAINT "NotificationRoute_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
CREATE TABLE "SlaPolicy" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"status" "SlaPolicyStatus" NOT NULL DEFAULT 'DRAFT',"targetType" "SlaTargetType" NOT NULL,"targetMinutes" INTEGER NOT NULL,"warningMinutes" INTEGER,"escalationAfterMinutes" INTEGER,"businessHoursOnly" BOOLEAN NOT NULL DEFAULT false,"appliesToEntityType" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "SlaPolicy_organizationId_key_key" ON "SlaPolicy"("organizationId","key");
ALTER TABLE "SlaPolicy" ADD CONSTRAINT "SlaPolicy_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
CREATE TABLE "SlaClock" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"policyId" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT NOT NULL,"ownerUserId" TEXT,"status" "SlaClockStatus" NOT NULL DEFAULT 'RUNNING',"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"warningAt" TIMESTAMP(3),"dueAt" TIMESTAMP(3) NOT NULL,"pausedAt" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"breachedAt" TIMESTAMP(3),"elapsedMinutes" INTEGER NOT NULL DEFAULT 0,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "SlaClock_organizationId_status_dueAt_idx" ON "SlaClock"("organizationId","status","dueAt");
ALTER TABLE "SlaClock" ADD CONSTRAINT "SlaClock_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "SlaClock" ADD CONSTRAINT "SlaClock_policyId_fkey" FOREIGN KEY ("policyId") REFERENCES "SlaPolicy"("id") ON DELETE RESTRICT;
CREATE TABLE "SlaEscalation" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"clockId" TEXT NOT NULL,"level" INTEGER NOT NULL,"status" "SlaEscalationStatus" NOT NULL DEFAULT 'PENDING',"targetType" TEXT NOT NULL,"targetValue" TEXT NOT NULL,"scheduledAt" TIMESTAMP(3) NOT NULL,"triggeredAt" TIMESTAMP(3),"notificationId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "SlaEscalation_clockId_level_key" ON "SlaEscalation"("clockId","level");
ALTER TABLE "SlaEscalation" ADD CONSTRAINT "SlaEscalation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "SlaEscalation" ADD CONSTRAINT "SlaEscalation_clockId_fkey" FOREIGN KEY ("clockId") REFERENCES "SlaClock"("id") ON DELETE CASCADE;
