import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AddCommunityMemberDto, AddWorkspaceMemberDto, CreateAnnouncementDto, CreateCommunityDto, CreateWorkspaceDto, LinkWorkspaceResourceDto, UpdateWorkspaceDto } from './dto';
@Injectable()
export class WorkspaceCommunityService {
 constructor(private readonly prisma:PrismaService){}
 private db(){return this.prisma as any;}
 private async workspace(org:string,id:string){const row=await this.db().teamWorkspace.findFirst({where:{id,organizationId:org},include:{members:true,communities:true,resources:true,announcements:{orderBy:{createdAt:'desc'}}}});if(!row)throw new NotFoundException('Workspace not found');return row;}
 private membership(workspace:any,userId:string){return workspace.members.find((m:any)=>m.userId===userId&&!m.leftAt);}
 private requireAccess(workspace:any,userId:string){if(workspace.visibility==='PUBLIC'||this.membership(workspace,userId))return;throw new ForbiddenException('Workspace access denied');}
 private requireAdmin(workspace:any,userId:string){const m=this.membership(workspace,userId);if(!m||!['OWNER','ADMIN'].includes(m.role))throw new ForbiddenException('Workspace administration requires owner or admin role');}
 async listWorkspaces(org:string,userId:string){const rows=await this.db().teamWorkspace.findMany({where:{organizationId:org,status:'ACTIVE'},include:{members:true,_count:{select:{communities:true,resources:true,announcements:true}}},orderBy:{updatedAt:'desc'}});return rows.filter((w:any)=>w.visibility!=='PRIVATE'||this.membership(w,userId));}
 async createWorkspace(org:string,userId:string,d:CreateWorkspaceDto){const ids=[...new Set([userId,...(d.memberUserIds??[])])];return this.db().teamWorkspace.create({data:{organizationId:org,name:d.name,description:d.description,visibility:d.visibility??'INTERNAL',createdByUserId:userId,members:{create:ids.map(id=>({organizationId:org,userId:id,role:id===userId?'OWNER':'MEMBER'}))}},include:{members:true}});}
 async getWorkspace(org:string,userId:string,id:string){const row=await this.workspace(org,id);this.requireAccess(row,userId);return row;}
 async updateWorkspace(org:string,userId:string,id:string,d:UpdateWorkspaceDto){const row=await this.workspace(org,id);this.requireAdmin(row,userId);return this.db().teamWorkspace.update({where:{id},data:d});}
 async addWorkspaceMember(org:string,userId:string,id:string,d:AddWorkspaceMemberDto){const row=await this.workspace(org,id);this.requireAdmin(row,userId);return this.db().workspaceMember.upsert({where:{workspaceId_userId:{workspaceId:id,userId:d.userId}},update:{role:d.role??'MEMBER',leftAt:null},create:{organizationId:org,workspaceId:id,userId:d.userId,role:d.role??'MEMBER'}});}
 async removeWorkspaceMember(org:string,userId:string,id:string,targetUserId:string){const row=await this.workspace(org,id);this.requireAdmin(row,userId);const owners=row.members.filter((m:any)=>m.role==='OWNER'&&!m.leftAt);if(targetUserId===userId&&owners.length===1)throw new BadRequestException('The final workspace owner cannot leave');return this.db().workspaceMember.update({where:{workspaceId_userId:{workspaceId:id,userId:targetUserId}},data:{leftAt:new Date()}});}
 async linkResource(org:string,userId:string,id:string,d:LinkWorkspaceResourceDto){const row=await this.workspace(org,id);this.requireAdmin(row,userId);return this.db().workspaceResource.upsert({where:{workspaceId_resourceType_resourceId:{workspaceId:id,resourceType:d.resourceType,resourceId:d.resourceId}},update:{label:d.label},create:{organizationId:org,workspaceId:id,resourceType:d.resourceType,resourceId:d.resourceId,label:d.label,linkedByUserId:userId}});}
 async announce(org:string,userId:string,id:string,d:CreateAnnouncementDto){const row=await this.workspace(org,id);this.requireAdmin(row,userId);return this.db().workspaceAnnouncement.create({data:{organizationId:org,workspaceId:id,title:d.title,content:d.content,authorUserId:userId,expiresAt:d.expiresAt?new Date(d.expiresAt):null}});}
 async createCommunity(org:string,userId:string,d:CreateCommunityDto){if(d.workspaceId){const w=await this.workspace(org,d.workspaceId);this.requireAdmin(w,userId);}return this.db().community.create({data:{organizationId:org,workspaceId:d.workspaceId,name:d.name,description:d.description,membershipPolicy:d.membershipPolicy??'OPEN',createdByUserId:userId,members:{create:{organizationId:org,userId,role:'OWNER'}}},include:{members:true}});}
 async listCommunities(org:string,userId:string){return this.db().community.findMany({where:{organizationId:org,status:'ACTIVE',OR:[{membershipPolicy:'OPEN'},{members:{some:{userId,leftAt:null}}}]},include:{members:true,_count:{select:{members:true}}},orderBy:{updatedAt:'desc'}});}
 private async community(org:string,id:string){const row=await this.db().community.findFirst({where:{id,organizationId:org},include:{members:true,workspace:true}});if(!row)throw new NotFoundException('Community not found');return row;}
 async addCommunityMember(org:string,userId:string,id:string,d:AddCommunityMemberDto){const c=await this.community(org,id);const actor=c.members.find((m:any)=>m.userId===userId&&!m.leftAt);if(!actor||!['OWNER','MODERATOR'].includes(actor.role))throw new ForbiddenException('Community moderation permission required');return this.db().communityMember.upsert({where:{communityId_userId:{communityId:id,userId:d.userId}},update:{role:d.role??'MEMBER',leftAt:null},create:{organizationId:org,communityId:id,userId:d.userId,role:d.role??'MEMBER'}});}
}
