-- Sprint 15.2 and 15.3 migration boundary.
-- Generate final table/index/FK SQL through Prisma after schema validation against PostgreSQL.
CREATE TYPE "RiskRecordStatus" AS ENUM ('OPEN','MONITORING','ACCEPTED','MITIGATED','CLOSED');
CREATE TYPE "RiskLevel" AS ENUM ('VERY_LOW','LOW','MEDIUM','HIGH','CRITICAL');
CREATE TYPE "ControlTestType" AS ENUM ('MANUAL','AUTOMATED','SAMPLING','CONTINUOUS');
CREATE TYPE "ControlTestStatus" AS ENUM ('SCHEDULED','RUNNING','PASSED','FAILED','PARTIAL','CANCELLED');
CREATE TYPE "FindingSeverity" AS ENUM ('INFORMATIONAL','LOW','MEDIUM','HIGH','CRITICAL');
CREATE TYPE "FindingStatus" AS ENUM ('OPEN','TRIAGED','ASSIGNED','RESOLVED','CLOSED');
CREATE TYPE "CorrectiveActionStatus" AS ENUM ('OPEN','IN_PROGRESS','BLOCKED','COMPLETED','VERIFIED','CANCELLED');
CREATE TYPE "CertificationCampaignType" AS ENUM ('ORGANIZATION','DEPARTMENT','BUSINESS_UNIT','APPLICATION','ROLE','PRIVILEGED_ACCESS');
CREATE TYPE "CertificationCampaignStatus" AS ENUM ('DRAFT','SCHEDULED','RUNNING','COMPLETED','CANCELLED');
CREATE TYPE "CertificationReviewStatus" AS ENUM ('PENDING','APPROVED','REVOKED','DELEGATED','EXPIRED');
CREATE TYPE "CertificationDecisionType" AS ENUM ('APPROVED','REVOKED','DELEGATED','JUSTIFICATION_REQUIRED','EXCEPTION');
CREATE TYPE "SoDSeverity" AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');
CREATE TYPE "SoDViolationStatus" AS ENUM ('OPEN','MITIGATED','EXCEPTED','RESOLVED');
CREATE TYPE "AccessRequestStatus" AS ENUM ('SUBMITTED','IN_REVIEW','APPROVED','REJECTED','PROVISIONED','COMPLETED','CANCELLED');
CREATE TYPE "PrivilegedAssignmentStatus" AS ENUM ('REQUESTED','APPROVED','ACTIVE','EXPIRED','REVOKED');
