import { Injectable, NotFoundException } from '@nestjs/common'; import { PrismaService } from '../prisma/prisma.service'; import { CreateAccessRequestDto, CreateCampaignDto, CreatePrivilegedAssignmentDto, CreateSoDRuleDto, DecisionDto } from './dto';
@Injectable() export class IdentityGovernanceService { constructor(private readonly prisma:PrismaService){}
 campaigns(org:string){return this.prisma.accessCertificationCampaign.findMany({where:{organizationId:org},include:{reviews:true},orderBy:{createdAt:'desc'}})}
 async createCampaign(org:string,d:CreateCampaignDto,createdBy:string){return this.prisma.accessCertificationCampaign.create({data:{organizationId:org,name:d.name,type:d.type as any,scopeRef:d.scopeRef,dueAt:new Date(d.dueAt),createdByUserId:createdBy,reviewerUserIds:d.reviewerUserIds??[],status:'DRAFT'}})}
 reviews(org:string,reviewer?:string){return this.prisma.accessCertificationReview.findMany({where:{organizationId:org,...(reviewer?{reviewerUserId:reviewer}:{})},include:{campaign:true,decisions:true},orderBy:{createdAt:'desc'}})}
 async decide(org:string,id:string,d:DecisionDto,userId:string){const r=await this.prisma.accessCertificationReview.findFirst({where:{id,organizationId:org}});if(!r)throw new NotFoundException('Review not found');return this.prisma.$transaction([this.prisma.accessCertificationDecision.create({data:{organizationId:org,reviewId:id,decidedByUserId:userId,decision:d.decision as any,justification:d.justification,delegatedToUserId:d.delegatedToUserId}}),this.prisma.accessCertificationReview.update({where:{id},data:{status:d.decision==='DELEGATED'?'DELEGATED':d.decision==='REVOKED'?'REVOKED':'APPROVED',completedAt:new Date()}})]);}
 sod(org:string){return this.prisma.soDRule.findMany({where:{organizationId:org},include:{violations:true},orderBy:{createdAt:'desc'}})}
 createRule(org:string,d:CreateSoDRuleDto){return this.prisma.soDRule.create({data:{organizationId:org,...d,severity:d.severity as any}})}
 violations(org:string){return this.prisma.soDViolation.findMany({where:{organizationId:org},include:{rule:true,exceptions:true},orderBy:[{severity:'desc'},{detectedAt:'desc'}]})}
 accessRequests(org:string,userId?:string){return this.prisma.accessRequest.findMany({where:{organizationId:org,...(userId?{requesterUserId:userId}:{})},include:{approvals:true},orderBy:{createdAt:'desc'}})}
 requestAccess(org:string,userId:string,d:CreateAccessRequestDto){return this.prisma.accessRequest.create({data:{organizationId:org,requesterUserId:userId,entitlement:d.entitlement,application:d.application,justification:d.justification,expiresAt:d.expiresAt?new Date(d.expiresAt):undefined,status:'SUBMITTED'}})}
 privileged(org:string){return this.prisma.privilegedAssignment.findMany({where:{organizationId:org},orderBy:{createdAt:'desc'}})}
 assignPrivileged(org:string,d:CreatePrivilegedAssignmentDto,requestedBy:string){return this.prisma.privilegedAssignment.create({data:{organizationId:org,roleName:d.roleName,userId:d.userId,requestedByUserId:requestedBy,startsAt:new Date(d.startsAt),expiresAt:new Date(d.expiresAt),breakGlass:d.breakGlass??false,justification:d.justification,status:'REQUESTED'}})}
 async dashboard(org:string){const [campaigns,pending,violations,privileged,requests]=await Promise.all([this.prisma.accessCertificationCampaign.count({where:{organizationId:org,status:{in:['SCHEDULED','RUNNING']}}}),this.prisma.accessCertificationReview.count({where:{organizationId:org,status:'PENDING'}}),this.prisma.soDViolation.count({where:{organizationId:org,status:'OPEN'}}),this.prisma.privilegedAssignment.count({where:{organizationId:org,status:'ACTIVE',expiresAt:{gt:new Date()}}}),this.prisma.accessRequest.count({where:{organizationId:org,status:{in:['SUBMITTED','IN_REVIEW']}}})]);return{activeCampaigns:campaigns,pendingReviews:pending,openSoDViolations:violations,activePrivilegedAssignments:privileged,pendingAccessRequests:requests}}
}
