'use client';
import Link from 'next/link';
import { use, useEffect, useState } from 'react';
import { AdminShell } from '../../../../../components/admin-shell';
import { api } from '../../../../../lib/api';
type Task={id:string;title:string;status:string;priority:string;dueDate?:string;position:number;assignee?:{firstName:string;lastName:string};labels:{label:{id:string;name:string;color:string}}[];checklist:{completed:boolean}[];_count:{comments:number;attachments:number}};
type Board={projectId:string;columns:{status:string;tasks:Task[]}[];total:number};
const label=(v:string)=>v.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function ProjectBoard({params}:{params:Promise<{id:string}>}){const {id}=use(params);const [board,setBoard]=useState<Board|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState('');async function load(){try{setBoard(await api<Board>(`/execution/projects/${id}/board`))}catch(e){setError(e instanceof Error?e.message:'Unable to load board')}}useEffect(()=>{load()},[id]);async function move(task:Task,status:string){setBusy(task.id);try{const target=board?.columns.find(c=>c.status===status);await api(`/execution/tasks/${task.id}/reorder`,{method:'PATCH',body:JSON.stringify({status,position:target?.tasks.length||0})});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to move task')}finally{setBusy('')}}return <AdminShell title="Project board" subtitle="Lightweight strategic delivery workflow" action={<Link className="buttonLink secondary" href={`/execution/projects/${id}`}>Project details</Link>}>{error&&<div className="formError">{error}</div>}{!board?<section className="panel">Loading board…</section>:<section className="kanbanBoard">{board.columns.filter(c=>c.status!=='CANCELLED').map(col=><article className="kanbanColumn" key={col.status}><header><h2>{label(col.status)}</h2><span>{col.tasks.length}</span></header><div className="kanbanCards">{col.tasks.map(task=><div className="kanbanCard" key={task.id}><Link href={`/execution/tasks/${task.id}`}><strong>{task.title}</strong></Link><div className="taskLabels">{task.labels.map(x=><i key={x.label.id} style={{borderColor:x.label.color}}>{x.label.name}</i>)}</div><small>{task.assignee?`${task.assignee.firstName} ${task.assignee.lastName}`:'Unassigned'} · {label(task.priority)}</small><small>{task.checklist.filter(x=>x.completed).length}/{task.checklist.length} checklist · {task._count.comments} comments · {task._count.attachments} files</small><select disabled={busy===task.id} value={task.status} onChange={e=>move(task,e.target.value)}><option value="TODO">To do</option><option value="IN_PROGRESS">In progress</option><option value="BLOCKED">Blocked</option><option value="DONE">Done</option></select></div>)}{!col.tasks.length&&<p className="emptyState">No tasks</p>}</div></article>)}</section>}</AdminShell>}
