'use client';
import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { AdminShell } from '../../../components/admin-shell';
import { api } from '../../../lib/api';
type Allocation={id:string;title:string;startsAt:string;endsAt:string;allocationPercent:number;hoursPerWeek?:number|null;project?:{key:string;name:string}|null;program?:{name:string}|null};
type Resource={id:string;displayName:string;jobTitle?:string;timezone:string;teams:string[];leave:{id:string;startsAt:string;endsAt:string;availableHours:number;reason?:string}[];allocations:Allocation[]};
type Schedule={from:string;to:string;timezone:string;resources:Resource[]};
const iso=(d:Date)=>d.toISOString().slice(0,10);
export default function SchedulePage(){const today=new Date(),later=new Date(today);later.setDate(later.getDate()+42);const[from,setFrom]=useState(iso(today)),[to,setTo]=useState(iso(later)),[data,setData]=useState<Schedule|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Allocation|null>(null),[draft,setDraft]=useState({startsAt:'',endsAt:'',resourceId:''});
 const days=useMemo(()=>{const a=new Date(from),b=new Date(to);return Math.max(1,Math.floor((b.getTime()-a.getTime())/86400000)+1)},[from,to]);
 const position=(date:string)=>Math.max(0,Math.min(100,(new Date(date).getTime()-new Date(from).getTime())/86400000/days*100));
 async function load(){setBusy(true);try{setError('');setData(await api<Schedule>(`/resource-management/schedule?from=${from}&to=${to}`))}catch(e){setError(e instanceof Error?e.message:'Unable to load schedule')}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 function open(a:Allocation,r:string){setEditing(a);setDraft({startsAt:a.startsAt.slice(0,10),endsAt:a.endsAt.slice(0,10),resourceId:r})}
 async function save(){if(!editing)return;setBusy(true);try{await api(`/resource-management/allocations/${editing.id}/schedule`,{method:'PATCH',body:JSON.stringify(draft)});setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to reschedule allocation')}finally{setBusy(false)}}
 return <AdminShell title="Enterprise scheduling" subtitle="Plan allocations, leave, and delivery commitments on a time-zone-aware resource timeline." action={<Link className="buttonLink" href="/resources">Back to resources</Link>}>
 {error&&<div className="formError">{error}</div>}
 <section className="panel"><div className="executionInlineForm"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={load} disabled={busy}>{busy?'Loading…':'Refresh timeline'}</button><Link className="buttonLink" href="/resources/calendars">Calendar administration</Link></div></section>
 <section className="panel tablePanel"><div className="panelHead"><div><h2>Resource timeline</h2><p>Select an allocation to move or resize it. Leave is shown separately from planned work.</p></div></div><div className="scheduleTimeline">{data?.resources.map(r=><div className="scheduleRow" key={r.id}><div className="scheduleResource"><strong>{r.displayName}</strong><small>{r.jobTitle||r.teams.join(', ')||r.timezone}</small></div><div className="scheduleTrack">{r.leave.map(x=><div className="scheduleLeave" key={x.id} style={{left:`${position(x.startsAt)}%`,width:`${Math.max(2,position(x.endsAt)-position(x.startsAt))}%`}} title={x.reason||'Unavailable'}>Leave</div>)}{r.allocations.map(a=><button key={a.id} className="scheduleAllocation" style={{left:`${position(a.startsAt)}%`,width:`${Math.max(3,position(a.endsAt)-position(a.startsAt))}%`}} onClick={()=>open(a,r.id)} title={`${a.title} · ${a.allocationPercent}%`}><strong>{a.title}</strong><small>{a.allocationPercent}%</small></button>)}</div></div>)}</div></section>
 {editing&&<section className="panel"><div className="panelHead"><div><h2>Reschedule {editing.title}</h2><p>Changes are validated and recorded as domain events.</p></div></div><div className="executionInlineForm"><label>Resource<select value={draft.resourceId} onChange={e=>setDraft({...draft,resourceId:e.target.value})}>{data?.resources.map(r=><option key={r.id} value={r.id}>{r.displayName}</option>)}</select></label><label>Start<input type="date" value={draft.startsAt} onChange={e=>setDraft({...draft,startsAt:e.target.value})}/></label><label>End<input type="date" value={draft.endsAt} onChange={e=>setDraft({...draft,endsAt:e.target.value})}/></label><button onClick={save} disabled={busy}>Save schedule</button><button className="secondaryButton" onClick={()=>setEditing(null)}>Cancel</button></div></section>}
 </AdminShell>}
