'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { AdminShell } from '../../components/admin-shell';import { api } from '../../lib/api';
type Overview={resources:number;teams:number;skills:number;allocations:number;capacityHours:number;allocatedHours:number;utilizationPercent:number;overallocatedResources:number};
type Resource={id:string;displayName:string;jobTitle?:string;status:string;capacityHoursPerWeek:string;skills:{skill:{name:string};proficiency:string}[];teamMemberships:{team:{name:string}}[];capacity:{allocatedHours:number;utilizationPercent:number;overallocated:boolean}};
type Team={id:string;name:string;memberships:{resource:{displayName:string}}[]};type Skill={id:string;name:string;category?:string;_count:{resources:number}};
export default function ResourcesPage(){const[o,setO]=useState<Overview|null>(null),[resources,setResources]=useState<Resource[]>([]),[teams,setTeams]=useState<Team[]>([]),[skills,setSkills]=useState<Skill[]>([]),[tab,setTab]=useState<'resources'|'teams'|'skills'>('resources'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[resourceForm,setResourceForm]=useState({displayName:'',jobTitle:'',email:'',capacityHoursPerWeek:'40'}),[teamName,setTeamName]=useState(''),[skillForm,setSkillForm]=useState({name:'',category:''});
async function load(){try{setError('');const[a,b,c,d]=await Promise.all([api<Overview>('/resource-management/overview'),api<Resource[]>('/resource-management/resources'),api<Team[]>('/resource-management/teams'),api<Skill[]>('/resource-management/skills')]);setO(a);setResources(b);setTeams(c);setSkills(d)}catch(e){setError(e instanceof Error?e.message:'Unable to load resources')}}useEffect(()=>{load()},[]);
async function createResource(e:FormEvent){e.preventDefault();setBusy(true);try{await api('/resource-management/resources',{method:'POST',body:JSON.stringify({...resourceForm,capacityHoursPerWeek:Number(resourceForm.capacityHoursPerWeek),email:resourceForm.email||undefined,jobTitle:resourceForm.jobTitle||undefined})});setResourceForm({displayName:'',jobTitle:'',email:'',capacityHoursPerWeek:'40'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create resource')}finally{setBusy(false)}}
async function createTeam(e:FormEvent){e.preventDefault();setBusy(true);try{await api('/resource-management/teams',{method:'POST',body:JSON.stringify({name:teamName})});setTeamName('');await load()}finally{setBusy(false)}}
async function createSkill(e:FormEvent){e.preventDefault();setBusy(true);try{await api('/resource-management/skills',{method:'POST',body:JSON.stringify(skillForm)});setSkillForm({name:'',category:''});await load()}finally{setBusy(false)}}
return <AdminShell title="Resource management" subtitle="Build the workforce foundation for capacity planning, staffing, skills intelligence, and allocation governance." action={<div className="actionGroup"><Link className="buttonLink secondary" href="/resources/analytics">Workforce analytics</Link><Link className="buttonLink secondary" href="/resources/assistant">AI Resource Planner</Link><Link className="buttonLink" href="/resources/capacity">Open capacity planning</Link></div>}>{error&&<div className="formError">{error}</div>}<section className="metrics executionMetrics"><article><p>Active resources</p><strong>{o?.resources??'—'}</strong><span>{o?.teams??0} resource teams</span></article><article><p>Utilization</p><strong>{Math.round(o?.utilizationPercent??0)}%</strong><span>{Math.round(o?.allocatedHours??0)} / {Math.round(o?.capacityHours??0)} hours</span></article><article><p>Overallocation</p><strong>{o?.overallocatedResources??'—'}</strong><span>Requires workload review</span></article><article><p>Skills catalog</p><strong>{o?.skills??'—'}</strong><span>{o?.allocations??0} active allocations</span></article></section><div className="enterpriseTabs"><button className={tab==='resources'?'active secondary':'secondary'} onClick={()=>setTab('resources')}>Resources</button><button className={tab==='teams'?'active secondary':'secondary'} onClick={()=>setTab('teams')}>Teams</button><button className={tab==='skills'?'active secondary':'secondary'} onClick={()=>setTab('skills')}>Skills</button></div>
{tab==='resources'&&<><section className="panel"><div className="panelHead"><div><h2>Add resource</h2><p>Create an employee, contractor, or delivery-capacity profile.</p></div></div><form className="executionInlineForm" onSubmit={createResource}><input required placeholder="Display name" value={resourceForm.displayName} onChange={e=>setResourceForm({...resourceForm,displayName:e.target.value})}/><input placeholder="Job title" value={resourceForm.jobTitle} onChange={e=>setResourceForm({...resourceForm,jobTitle:e.target.value})}/><input type="email" placeholder="Email" value={resourceForm.email} onChange={e=>setResourceForm({...resourceForm,email:e.target.value})}/><input type="number" min="0" placeholder="Hours/week" value={resourceForm.capacityHoursPerWeek} onChange={e=>setResourceForm({...resourceForm,capacityHoursPerWeek:e.target.value})}/><button disabled={busy}>Create</button></form></section><section className="panel tablePanel"><div className="executionTable"><div className="executionRow executionHead"><span>Resource</span><span>Team</span><span>Skills</span><span>Capacity</span><span>Utilization</span><span>Status</span></div>{resources.map(r=><div className="executionRow" key={r.id}><span><strong>{r.displayName}</strong><small>{r.jobTitle||'Role not set'}</small></span><span>{r.teamMemberships.map(x=>x.team.name).join(', ')||'Unassigned'}</span><span>{r.skills.map(x=>x.skill.name).slice(0,3).join(', ')||'No skills'}</span><span>{r.capacity.allocatedHours} / {Number(r.capacityHoursPerWeek)}h</span><span><strong className={r.capacity.overallocated?'negative':''}>{Math.round(r.capacity.utilizationPercent)}%</strong></span><span><i className="status">{r.status.replaceAll('_',' ')}</i></span></div>)}</div></section></>}
{tab==='teams'&&<><section className="panel"><form className="executionInlineForm" onSubmit={createTeam}><input required placeholder="Resource team name" value={teamName} onChange={e=>setTeamName(e.target.value)}/><button disabled={busy}>Create team</button></form></section><section className="cardGrid executionCards">{teams.map(t=><article className="panel entityCard" key={t.id}><div className="entityIcon team">RT</div><h2>{t.name}</h2><p>{t.memberships.length} members</p><div>{t.memberships.slice(0,4).map(m=>m.resource.displayName).join(', ')||'No members assigned'}</div></article>)}</section></>}
{tab==='skills'&&<><section className="panel"><form className="executionInlineForm" onSubmit={createSkill}><input required placeholder="Skill name" value={skillForm.name} onChange={e=>setSkillForm({...skillForm,name:e.target.value})}/><input placeholder="Category" value={skillForm.category} onChange={e=>setSkillForm({...skillForm,category:e.target.value})}/><button disabled={busy}>Create skill</button></form></section><section className="cardGrid executionCards">{skills.map(s=><article className="panel entityCard" key={s.id}><div className="entityIcon">SK</div><h2>{s.name}</h2><p>{s.category||'Uncategorized'}</p><div><span>Resource coverage</span><strong>{s._count.resources}</strong></div></article>)}</section></>}</AdminShell>}
