import { IsArray, IsEnum, IsNumber, IsObject, IsOptional, IsString, Max, Min } from 'class-validator';
export enum RecommendationType { REPRIORITIZE_INITIATIVE='REPRIORITIZE_INITIATIVE', REALLOCATE_RESOURCES='REALLOCATE_RESOURCES', ESCALATE_APPROVAL='ESCALATE_APPROVAL', ADJUST_OBJECTIVE='ADJUST_OBJECTIVE', RECOMMEND_HIRING='RECOMMEND_HIRING', RECOMMEND_AUTOMATION='RECOMMEND_AUTOMATION', ADJUST_BUDGET='ADJUST_BUDGET', MITIGATE_RISK='MITIGATE_RISK' }
export enum RecommendationPriority { LOW='LOW', MEDIUM='MEDIUM', HIGH='HIGH', CRITICAL='CRITICAL' }
export enum RecommendationDisposition { ACCEPT='ACCEPT', REJECT='REJECT', DEFER='DEFER', MARK_APPLIED='MARK_APPLIED' }
export class CreateDecisionPolicyDto { @IsString() key!:string; @IsString() name!:string; @IsOptional() @IsString() description?:string; @IsEnum(RecommendationType) recommendationType!:RecommendationType; }
export class CreateDecisionPolicyVersionDto { @IsObject() configuration!:Record<string,unknown>; @IsOptional() @IsNumber() @Min(0) @Max(1) minimumConfidence?:number; }
export class GenerateRecommendationDto { @IsString() entityType!:string; @IsString() entityId!:string; @IsString() title!:string; @IsString() summary!:string; @IsOptional() @IsString() predictionResultId?:string; @IsNumber() @Min(0) @Max(1) confidence!:number; @IsOptional() @IsEnum(RecommendationPriority) priority?:RecommendationPriority; @IsArray() evidence!:Record<string,unknown>[]; @IsObject() expectedImpact!:Record<string,unknown>; @IsArray() proposedActions!:Record<string,unknown>[]; @IsOptional() @IsArray() alternatives?:Record<string,unknown>[]; @IsOptional() @IsObject() rationale?:Record<string,unknown>; @IsOptional() @IsString() expiresAt?:string; }
export class DecideRecommendationDto { @IsEnum(RecommendationDisposition) disposition!:RecommendationDisposition; @IsOptional() @IsString() comment?:string; }
export class SimulateDecisionDto { @IsString() scenarioName!:string; @IsObject() baseline!:Record<string,number>; @IsObject() changes!:Record<string,number>; @IsOptional() @IsNumber() @Min(0) @Max(1) confidence?:number; }
