import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { createHash, randomBytes } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
import { CreateApiApplicationDto, CreateApiProductDto, GenerateSdkDto, PublishApiVersionDto, RecordUsageDto, RotateApiCredentialDto } from './dto';

@Injectable()
export class DeveloperPlatformService {
  constructor(private readonly prisma: PrismaService) {}
  async overview(org:string){const [applications,products,activeCredentials,usage]=await Promise.all([this.prisma.apiApplication.count({where:{organizationId:org}}),this.prisma.apiProduct.count({where:{organizationId:org}}),this.prisma.apiCredential.count({where:{organizationId:org,status:'ACTIVE'}}),this.prisma.apiUsageRecord.aggregate({where:{organizationId:org,occurredAt:{gte:new Date(Date.now()-30*86400000)}},_count:true,_avg:{durationMs:true},_sum:{units:true}})]);return {rest:{version:'v2',status:'foundation'},graphql:{status:'schema-first foundation'},openapi:{version:'3.1.0'},applications,products,activeCredentials,requests30d:usage._count,averageLatencyMs:Math.round(usage._avg.durationMs||0),units30d:usage._sum.units||0}}
  applications(org:string){return this.prisma.apiApplication.findMany({where:{organizationId:org},include:{credentials:{select:{id:true,prefix:true,status:true,scopes:true,lastUsedAt:true,expiresAt:true,createdAt:true}}},orderBy:{createdAt:'desc'}})}
  createApplication(org:string,d:CreateApiApplicationDto){if(!d.name?.trim())throw new BadRequestException('Application name is required');return this.prisma.apiApplication.create({data:{organizationId:org,name:d.name.trim(),description:d.description,redirectUris:d.redirectUris||[],requestedScopes:d.scopes||[],status:'ACTIVE'}})}
  async issueCredential(org:string,id:string,d:RotateApiCredentialDto){const app=await this.prisma.apiApplication.findFirst({where:{id,organizationId:org}});if(!app)throw new NotFoundException('API application not found');const secret=`ax_live_${randomBytes(24).toString('base64url')}`;const prefix=secret.slice(0,15);const row=await this.prisma.apiCredential.create({data:{organizationId:org,applicationId:id,name:`${app.name} credential`,prefix,secretHash:createHash('sha256').update(secret).digest('hex'),scopes:app.requestedScopes,status:'ACTIVE',expiresAt:d.expiresAt?new Date(d.expiresAt):undefined}});return {id:row.id,prefix:row.prefix,secret,scopes:row.scopes,expiresAt:row.expiresAt,warning:'This secret is returned once and is not retrievable.'}}
  async revokeCredentials(org:string,id:string){const app=await this.prisma.apiApplication.findFirst({where:{id,organizationId:org}});if(!app)throw new NotFoundException('API application not found');return this.prisma.apiCredential.updateMany({where:{organizationId:org,applicationId:id,status:'ACTIVE'},data:{status:'REVOKED',revokedAt:new Date()}})}
  products(org:string){return this.prisma.apiProduct.findMany({where:{organizationId:org},include:{versions:{orderBy:{createdAt:'desc'}}},orderBy:{name:'asc'}})}
  createProduct(org:string,d:CreateApiProductDto){return this.prisma.apiProduct.create({data:{organizationId:org,name:d.name,slug:d.slug,description:d.description,audience:d.audience||'PRIVATE',defaultVersion:d.version||'v2',scopes:d.scopes||[],status:'DRAFT'}})}
  async publishVersion(org:string,id:string,d:PublishApiVersionDto){const product=await this.prisma.apiProduct.findFirst({where:{id,organizationId:org}});if(!product)throw new NotFoundException('API product not found');return this.prisma.apiProductVersion.create({data:{organizationId:org,apiProductId:id,version:d.version,lifecycle:d.lifecycle||'DRAFT',changelog:d.changelog,sunsetAt:d.sunsetAt?new Date(d.sunsetAt):undefined,schemaUrl:`/api/v1/developer-platform/openapi?product=${product.slug}&version=${d.version}`}})}
  async usage(org:string,days:number){const since=new Date(Date.now()-days*86400000);const [summary,byRoute]=await Promise.all([this.prisma.apiUsageRecord.aggregate({where:{organizationId:org,occurredAt:{gte:since}},_count:true,_avg:{durationMs:true},_sum:{units:true}}),this.prisma.apiUsageRecord.groupBy({by:['route','method'],where:{organizationId:org,occurredAt:{gte:since}},_count:true,_avg:{durationMs:true},orderBy:{_count:{route:'desc'}},take:20})]);return {days,requests:summary._count,units:summary._sum.units||0,averageLatencyMs:Math.round(summary._avg.durationMs||0),routes:byRoute}}
  recordUsage(org:string,d:RecordUsageDto){return this.prisma.apiUsageRecord.create({data:{organizationId:org,applicationId:d.applicationId,apiProductId:d.apiProductId,route:d.route,method:d.method,statusCode:d.statusCode,durationMs:d.durationMs,requestId:d.requestId,units:d.units||1}})}
  openApiManifest(){return {openapi:'3.1.0',info:{title:'AchieveX Public API',version:'2.0.0'},servers:[{url:'/api/v2'}],security:[{apiKey:[]}],components:{securitySchemes:{apiKey:{type:'apiKey',in:'header',name:'X-AchieveX-API-Key'}}},paths:{'/objectives':{get:{summary:'List objectives',operationId:'listObjectives'}},'/projects':{get:{summary:'List projects',operationId:'listProjects'}},'/analytics/metrics':{get:{summary:'List metric definitions',operationId:'listMetrics'}}}}}
  graphQlSchema(){return {status:'foundation',schema:`scalar JSON\nscalar DateTime\ntype Objective { id: ID!, title: String!, status: String! }\ntype Project { id: ID!, name: String!, status: String! }\ntype Query { objectives(limit: Int = 25): [Objective!]!, projects(limit: Int = 25): [Project!]! }`,note:'Runtime resolvers and persisted-query enforcement require the deployment GraphQL adapter.'}}
  generateSdk(d:GenerateSdkDto){const generators:any={typescript:'openapi-generator-cli generate -g typescript-fetch',python:'openapi-generator-cli generate -g python',java:'openapi-generator-cli generate -g java',csharp:'openapi-generator-cli generate -g csharp'};return {language:d.language,apiVersion:d.apiVersion||'v2',status:'generation-plan',command:`${generators[d.language]} -i openapi.json -o sdk/${d.language}`,note:'SDK generation is deterministic from the published OpenAPI document and runs in CI, not inside the API process.'}}
  marketplace(org:string){return this.prisma.apiProduct.findMany({where:{organizationId:org,status:{in:['PUBLISHED','DEPRECATED']},audience:{in:['PARTNER','PUBLIC']}},include:{versions:{where:{lifecycle:{in:['BETA','STABLE','DEPRECATED']}},orderBy:{createdAt:'desc'}}}})}
}
