'use client';
import Link from 'next/link';
import { FormEvent, use, useEffect, useState } from 'react';
import { AdminShell } from '../../../../components/admin-shell';
import { api } from '../../../../lib/api';

type Project={id:string;key:string;name:string;description?:string;status:string;health:string;priority:string;progress:string;budget?:string;actualCost:string;startDate?:string;targetDate?:string;owner:{firstName:string;lastName:string};sponsor?:{firstName:string;lastName:string};portfolio?:{name:string};program?:{name:string};variance:{budgetVariance:number;budgetVariancePercent:number;scheduleProgress:number;scheduleVariancePoints:number;daysRemaining:number|null};healthDetails:{score:number;signals:{overdueTasks:number;overdueMilestones:number;criticalIssues:number;highRisks:number}};milestones:{id:string;name:string;status:string;plannedDate:string}[];tasks:{id:string;title:string;status:string;priority:string;dueDate?:string}[];risks:{id:string;title:string;status:string;probability:string;impact:string}[];issues:{id:string;title:string;status:string;severity:string}[];activities:{id:string;action:string;createdAt:string;actor?:{firstName:string;lastName:string}}[]};
const label=(v:string)=>v?.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const money=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n||0);
export default function ProjectDetail({params}:{params:Promise<{id:string}>}){const {id}=use(params);const [p,setP]=useState<Project|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState({progress:'',actualCost:'',targetDate:''}),[milestone,setMilestone]=useState({name:'',ownerId:'',plannedDate:''}),[task,setTask]=useState({title:'',dueDate:'',priority:'MEDIUM'});
 async function load(){try{const x=await api<Project>(`/execution/projects/${id}`);setP(x);setEdit({progress:String(Number(x.progress)),actualCost:String(Number(x.actualCost)),targetDate:x.targetDate?.slice(0,10)||''});setMilestone(m=>({...m,ownerId:(x as any).owner?.id||''}))}catch(e){setError(e instanceof Error?e.message:'Unable to load project')}} useEffect(()=>{load()},[id]);
 async function update(e:FormEvent){e.preventDefault();setBusy(true);try{await api(`/execution/projects/${id}`,{method:'PATCH',body:JSON.stringify({progress:Number(edit.progress),actualCost:Number(edit.actualCost),targetDate:edit.targetDate||undefined})});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update')}finally{setBusy(false)}}
 async function transition(status:string){setBusy(true);try{await api(`/execution/projects/${id}/transition`,{method:'POST',body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:'Transition failed')}finally{setBusy(false)}}
 async function recalc(){setBusy(true);try{await api(`/execution/projects/${id}/recalculate-health`,{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:'Recalculation failed')}finally{setBusy(false)}}
 async function addMilestone(e:FormEvent){e.preventDefault();setBusy(true);try{await api(`/execution/projects/${id}/milestones`,{method:'POST',body:JSON.stringify({...milestone,ownerId:(p as any)?.owner?.id,plannedDate:milestone.plannedDate})});setMilestone({name:'',ownerId:'',plannedDate:''});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to add milestone')}finally{setBusy(false)}}
 async function addTask(e:FormEvent){e.preventDefault();setBusy(true);try{await api(`/execution/projects/${id}/tasks`,{method:'POST',body:JSON.stringify({...task,dueDate:task.dueDate||undefined})});setTask({title:'',dueDate:'',priority:'MEDIUM'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to add task')}finally{setBusy(false)}}
 if(!p)return <AdminShell title="Project" subtitle="Loading delivery details…">{error?<div className="formError">{error}</div>:<section className="panel">Loading…</section>}</AdminShell>;
 const transitions:Record<string,string[]>={DRAFT:['PLANNED','CANCELLED'],PLANNED:['ACTIVE','ON_HOLD','CANCELLED'],ACTIVE:['ON_HOLD','COMPLETED','CANCELLED'],ON_HOLD:['ACTIVE','CANCELLED'],COMPLETED:[],CANCELLED:[]};
 return <AdminShell title={`${p.key} · ${p.name}`} subtitle={p.description||'Project delivery workspace'} action={<div className="actionGroup"><Link className="buttonLink" href={`/execution/projects/${id}/board`}>Open board</Link><Link className="buttonLink" href={`/execution/projects/${id}/traceability`}>Strategy links</Link><Link className="buttonLink" href={`/execution/projects/${id}/assistant`}>AI assistant</Link><Link className="buttonLink secondary" href="/execution">Back to portfolio</Link></div>}>
  {error&&<div className="formError">{error}</div>}
  <section className="projectHero panel"><div><div className="projectBadges"><i className="status">{label(p.status)}</i><i className={`status health-${p.health.toLowerCase()}`}>{label(p.health)}</i><i className="status">{label(p.priority)}</i></div><p>{p.portfolio?.name||'No portfolio'} {p.program?`/ ${p.program.name}`:''}</p><small>Owner: {p.owner.firstName} {p.owner.lastName}{p.sponsor?` · Sponsor: ${p.sponsor.firstName} ${p.sponsor.lastName}`:''}</small></div><div className="projectScore"><strong>{Math.round(Number(p.progress))}%</strong><span>delivery progress</span></div></section>
  <section className="metrics executionMetrics"><article><p>Schedule variance</p><strong className={p.variance.scheduleVariancePoints<-10?'negative':''}>{Math.round(p.variance.scheduleVariancePoints)} pts</strong><span>{p.variance.daysRemaining===null?'No target':`${p.variance.daysRemaining} days remaining`}</span></article><article><p>Budget variance</p><strong className={p.variance.budgetVariancePercent>10?'negative':''}>{p.variance.budgetVariancePercent>0?'+':''}{Math.round(p.variance.budgetVariancePercent)}%</strong><span>{money(Number(p.actualCost))} actual / {money(Number(p.budget||0))} budget</span></article><article><p>Health score</p><strong>{p.healthDetails.score}</strong><span>{p.healthDetails.signals.overdueTasks} overdue tasks · {p.healthDetails.signals.overdueMilestones} milestones</span></article><article><p>Open exposure</p><strong>{p.healthDetails.signals.highRisks+p.healthDetails.signals.criticalIssues}</strong><span>{p.healthDetails.signals.highRisks} high risks · {p.healthDetails.signals.criticalIssues} critical issues</span></article></section>
  <section className="two-column executionDetail"><article className="panel"><div className="panelHead"><div><h2>Delivery controls</h2><p>Update progress and actual cost; health recalculates automatically.</p></div><button className="secondary" onClick={recalc} disabled={busy}>Recalculate health</button></div><form className="projectForm compactForm" onSubmit={update}><div className="formGrid"><label>Progress %<input type="number" min="0" max="100" value={edit.progress} onChange={e=>setEdit({...edit,progress:e.target.value})}/></label><label>Actual cost<input type="number" min="0" value={edit.actualCost} onChange={e=>setEdit({...edit,actualCost:e.target.value})}/></label></div><label>Target date<input type="date" value={edit.targetDate} onChange={e=>setEdit({...edit,targetDate:e.target.value})}/></label><button disabled={busy}>Save delivery update</button></form><div className="transitionBar"><strong>Status workflow</strong>{transitions[p.status].map(s=><button className="secondary" key={s} onClick={()=>transition(s)} disabled={busy}>{label(s)}</button>)}</div></article><article className="panel"><h2>Health signals</h2><div className="signalList"><span><b>Overdue tasks</b><strong>{p.healthDetails.signals.overdueTasks}</strong></span><span><b>Overdue milestones</b><strong>{p.healthDetails.signals.overdueMilestones}</strong></span><span><b>High exposure risks</b><strong>{p.healthDetails.signals.highRisks}</strong></span><span><b>Critical issues</b><strong>{p.healthDetails.signals.criticalIssues}</strong></span></div></article></section>
  <section className="two-column executionDetail"><article className="panel"><div className="panelHead"><div><h2>Milestones</h2><p>Major delivery checkpoints.</p></div></div><form className="executionInlineForm" onSubmit={addMilestone}><input required placeholder="Milestone name" value={milestone.name} onChange={e=>setMilestone({...milestone,name:e.target.value})}/><input required type="date" value={milestone.plannedDate} onChange={e=>setMilestone({...milestone,plannedDate:e.target.value})}/><button disabled={busy}>Add</button></form>{p.milestones.map(m=><div className="workItem" key={m.id}><span><strong>{m.name}</strong><small>{new Date(m.plannedDate).toLocaleDateString()}</small></span><i className="status">{label(m.status)}</i></div>)}</article><article className="panel"><div className="panelHead"><div><h2>Tasks</h2><p>Lightweight execution tracking.</p></div></div><form className="projectForm compactForm" onSubmit={addTask}><input required placeholder="Task title" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><div className="formGrid"><input type="date" value={task.dueDate} onChange={e=>setTask({...task,dueDate:e.target.value})}/><select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></div><button disabled={busy}>Add task</button></form>{p.tasks.slice(0,8).map(t=><div className="workItem" key={t.id}><span><strong>{t.title}</strong><small>{t.dueDate?new Date(t.dueDate).toLocaleDateString():'No due date'} · {label(t.priority)}</small></span><i className="status">{label(t.status)}</i></div>)}</article></section>
  <section className="two-column executionDetail"><article className="panel"><h2>Risks & issues</h2>{[...p.risks.map(r=>({id:r.id,title:r.title,meta:`${label(r.probability)} probability · ${label(r.impact)} impact`,status:r.status})),...p.issues.map(i=>({id:i.id,title:i.title,meta:`${label(i.severity)} severity`,status:i.status}))].map(x=><div className="workItem" key={x.id}><span><strong>{x.title}</strong><small>{x.meta}</small></span><i className="status">{label(x.status)}</i></div>)}</article><article className="panel"><h2>Activity</h2>{p.activities.slice(0,10).map(a=><div className="timeline" key={a.id}><i/><div><strong>{label(a.action.replaceAll('.',' '))}</strong><small>{a.actor?`${a.actor.firstName} ${a.actor.lastName} · `:''}{new Date(a.createdAt).toLocaleString()}</small></div></div>)}</article></section>
 </AdminShell>}
